import { useId, useState } from 'react';
import { chipInput, chips, pokerUnits, stateLabel, units, UNITS_PER_CHIP, type LobbyFilters, type LobbyIntent, type PokerLobbyProps } from './poker-ui-types';
import { Modal } from '../ui';
import { PokerArt } from './PokerArt';
import { assetUrl, assetSrcSet, gameArt } from '../game-hall-assets';
import './poker-ui.css';
import './poker-salon.css';

const nameSegmenter=new Intl.Segmenter(undefined,{granularity:'grapheme'});
function validName(value:string):boolean {
  const name=value.trim();if(!name)return false;let count=0;
  for(const _ of nameSegmenter.segment(name))if(++count>40)return false;
  return true;
}
const validPassword=(value:string)=>value.length>0&&new TextEncoder().encode(value).length<=128;

export function PokerLobby(p: PokerLobbyProps) {
  const [panel,setPanel]=useState<'rules'|'fairness'|'entry'|null>(null);
  const cover=gameArt('texas-holdem');
  const id=useId(),s=p.snapshot,context={...p.authority.scope};
  const ready=p.authority.read_state==='FRESH'&&context.user_id===s.viewer.user_id;
  const available=units(s.viewer.available_chips_units),canEnter=ready&&!p.entry_pending&&!p.entry_blocked&&s.service.state==='READY'&&s.service.production_ready&&s.viewer.can_join&&!s.active_session;
  const canCreate=canEnter&&s.viewer.can_create&&s.viewer.owned_open_table_id===null;
  const rows=s.tables,canRefresh=p.authority.read_state!=='LOADING';
  const readLabel={FRESH:'HTTP 已更新',LOADING:'HTTP 刷新中',STALE:'HTTP 数据已过期',ERROR:'HTTP 读取失败'}[p.authority.read_state];
  const changeFilters=(next:LobbyFilters)=>p.onFiltersChange({...next,cursor:null});
  const send=(intent:LobbyIntent)=>p.onIntent(intent,context);
  const flow=p.flow, selected=flow.kind==='JOIN'?s.tables.find(t=>t.table_id===flow.table_id):undefined;
  const accessReady=canEnter&&selected?.visibility==='PASSWORD'&&selected.can_request_access;
  const joinReady=canEnter&&!!selected&&(selected.can_join||accessReady);
  const min=selected?pokerUnits(selected.minimum_buyin_units):undefined,max=selected?pokerUnits(selected.maximum_buyin_units):undefined;
  const buyIn=flow.kind==='JOIN'?chipInput(flow.draft.buy_in_chips):undefined;
  const reserved=flow.kind==='JOIN' && flow.reservation?.valid && flow.reservation.seat_no===flow.draft.seat_no;
  const buyValid=flow.kind==='JOIN' && joinReady && flow.access_granted && flow.can_buy_in && !!reserved &&
    buyIn!==undefined && available!==undefined && min!==undefined && max!==undefined && buyIn>=min && buyIn<=max && buyIn<=available;
  const createValid=flow.kind==='CREATE' && canCreate && validName(flow.draft.name) &&
    Number.isInteger(flow.draft.max_seats) && flow.draft.max_seats>=2 && flow.draft.max_seats<=9 &&
    s.blind_presets.some(x=>x.id===flow.draft.blind_preset_id) &&
    s.create_options.access_modes.includes(flow.draft.visibility) &&
    (flow.draft.visibility==='PUBLIC'||validPassword(flow.draft.password)) &&
    (!flow.draft.chat_enabled||s.create_options.chat_configurable);

  return <section className="pk-ui pk-lobby pk-salon" aria-label="Poker 大厅">
    <PokerArt name="room" className="pk-salon-backdrop"/>
    <header className="pk-lobby-heading"><div><p className="pk-eyebrow">CHALDEA · MOONLIT POKER SALON</p><h1>Poker <span>月下牌室</span></h1><p className="pk-subtitle">找到一张桌，认真打好每一手。No-Limit Texas Hold’em</p></div><PokerArt name="crest" className="pk-salon-mark" sizes="90px"/></header>
    {s.active_session && <section className="pk-session-banner" aria-label="当前牌桌会话"><div><span className="pk-eyebrow">YOUR ACTIVE TABLE</span><h2>{s.active_session.table_name}</h2><p>{s.active_session.table_id} · 桌上筹码 {chips(s.active_session.stack_units)} Chips · 已承诺 {chips(s.active_session.committed_units)} Chips · 在桌资产 {chips(s.active_session.poker_in_play_units)} Chips · {s.active_session.state==='ACTIVE'?'会话进行中':'会话待复核'}</p><small>已有唯一牌桌会话。请先回桌；离座由安全结算流程完成。</small></div><button className="pk-primary" disabled={!s.active_session.can_reconnect||!ready||p.entry_pending} onClick={()=>{if(s.active_session?.can_reconnect&&ready&&!p.entry_pending)send({type:'reconnect',table_id:s.active_session.table_id,session_id:s.active_session.session_id});}}>回到当前牌桌</button></section>}
    <div className="pk-lobby-summary"><div className="pk-service"><span className="pk-status-dot" aria-hidden="true"/><span>{s.service.state==='READY'?'牌室开放':s.service.state==='MAINTENANCE'?'牌室维护中':'等待服务状态'}<small>{readLabel}</small></span></div><div><span className="pk-caption">可用娱乐筹码</span><strong>{chips(s.viewer.available_chips_units)}</strong><small>Chips</small></div><div><span className="pk-caption">Poker In Play</span><strong>{chips(s.viewer.poker_in_play_units)}</strong><small>尚在牌桌中的资产</small></div><div className="pk-summary-links"><button disabled={p.entry_pending} onClick={()=>{if(!p.entry_pending)send({type:'wallet'});}}>查看钱包 ↗</button><button disabled={p.entry_pending} onClick={()=>{if(!p.entry_pending)send({type:'history'});}}>牌局历史 ↗</button></div></div>
    {p.notice&&<p className="pk-notice" role="status">{p.notice}</p>}
    {p.entry_pending&&<p className="pk-notice" role="status">请求结果待确认；等待权威状态，不重复提交。</p>}
    <div className={`pk-lobby-layout${flow.kind!=='NONE'?' pk-with-flow':''}`}>
      <div className="pk-table-network">
        <div className="pk-section-heading"><div><p className="pk-eyebrow">FIND YOUR TABLE</p><h2>牌桌网络 <span className="pk-count">{rows.length}</span></h2></div><button className="pk-primary" disabled={!canCreate} onClick={()=>{if(canCreate)p.onFlowChange('CREATE');}}>创建牌桌</button></div>
        <div className="pk-filter-main"><label htmlFor={`${id}-search`}>搜索牌桌<input id={`${id}-search`} type="search" value={p.filters.query} placeholder="Table ID 或牌桌名称" onChange={e=>changeFilters({...p.filters,query:e.target.value})}/></label><label htmlFor={`${id}-sort`}>排序<select id={`${id}-sort`} value={p.filters.sort} onChange={e=>changeFilters({...p.filters,sort:e.target.value as typeof p.filters.sort})}><option value="NEAR_FULL">接近满桌优先</option><option value="LOW_BLIND">低盲注优先</option><option value="HIGH_BLIND">高盲注优先</option></select></label><button disabled={!canRefresh} onClick={()=>{if(canRefresh)send({type:'refresh'});}}>刷新列表</button></div>
        <details className="pk-filter-details"><summary>筛选牌桌 <span>盲注 / 人数 / 状态</span></summary><div className="pk-filter-grid">
          <label>访问方式<select value={p.filters.visibility} onChange={e=>changeFilters({...p.filters,visibility:e.target.value as typeof p.filters.visibility})}><option value="ALL">全部牌桌</option><option value="PUBLIC">公开牌桌</option><option value="PASSWORD">密码牌桌</option></select></label>
          <label>最多座位<select value={p.filters.max_seats} onChange={e=>changeFilters({...p.filters,max_seats:e.target.value==='ALL'?'ALL':Number(e.target.value)})}><option value="ALL">全部人数</option>{Array.from({length:8},(_,i)=><option key={i+2} value={i+2}>{i+2} 人桌</option>)}</select></label>
          <label>盲注档位<select value={p.filters.blind_preset_id} onChange={e=>changeFilters({...p.filters,blind_preset_id:e.target.value})}><option value="ALL">全部盲注</option>{s.blind_presets.map(x=><option key={x.id} value={x.id}>{chips(x.small_blind_units)} / {chips(x.big_blind_units)}</option>)}</select></label>
          <label>牌桌状态<select value={p.filters.lifecycle_state} onChange={e=>changeFilters({...p.filters,lifecycle_state:e.target.value})}><option value="ALL">全部状态</option>{['WAITING','IN_HAND','PAUSED'].map(s=><option key={s} value={s}>{stateLabel(s)}</option>)}</select></label>
          <label className="pk-check"><input type="checkbox" checked={p.filters.open_seats_only} onChange={e=>changeFilters({...p.filters,open_seats_only:e.target.checked})}/>只看有空座</label><label className="pk-check"><input type="checkbox" checked={p.filters.spectators_only} onChange={e=>changeFilters({...p.filters,spectators_only:e.target.checked})}/>允许观战</label>
        </div></details>
        <div className="pk-network-scroll" tabIndex={0} aria-label="可用牌桌列表滚动区域"><table className="pk-network-list"><caption className="pk-sr-only">可用牌桌列表</caption><thead><tr><th>牌桌</th><th>盲注 / 买入</th><th>座位 / 状态</th><th><span className="pk-sr-only">操作</span></th></tr></thead><tbody>{rows.map(t=>{const owner=s.viewer.owned_open_table_id===t.table_id,canOpen=canEnter&&(t.can_join||t.visibility==='PASSWORD'&&t.can_request_access);return <tr key={t.table_id}><td>{cover&&<img className="pk-room-cover" src={assetUrl(cover.src)} srcSet={assetSrcSet(cover)} sizes="180px" width={cover.width} height={cover.height} alt=""/>}<strong className="pk-table-name">{t.name}</strong><small>{t.table_id} <span className="pk-access">{t.visibility==='PASSWORD'?'◇ 密码':'公开'}</span></small><small>{t.allow_spectators?'允许观战':'不开放观战'} · {t.chat_enabled?'聊天开放':'聊天关闭'}</small></td><td data-label="盲注"><strong>{chips(t.small_blind_units)} / {chips(t.big_blind_units)} <span className="pk-unit">Chips</span></strong><small>{chips(t.minimum_buyin_units)} – {chips(t.maximum_buyin_units)} 买入</small><small>无 Ante</small></td><td><strong>{t.occupied_seats}<span className="pk-unit"> / {t.max_seats} 席</span></strong><small>{stateLabel(t.lifecycle_state)}</small><small className="pk-room-seats">空座 {t.open_seat_numbers.join('、')||'暂无'} · 以预留结果为准</small></td><td><div className="pk-row-actions"><button disabled={!canOpen} onClick={()=>{if(canOpen)send({type:'open_table',table_id:t.table_id});}}>{t.visibility==='PASSWORD'&&!t.can_join?'验证并查看':'查看座位'} <span aria-hidden="true">↗</span></button>{(t.allow_spectators||owner)&&<button className="pk-quiet" disabled={!ready||p.entry_pending||!!s.active_session||!t.can_spectate} onClick={()=>{if(ready&&!p.entry_pending&&!s.active_session&&t.can_spectate)send({type:'spectate',table_id:t.table_id});}}>{owner?'管理':'观战'}</button>}</div></td></tr>;})}</tbody></table></div>
        {rows.length===0&&<div className="pk-empty" role="status"><PokerArt name="crest" className="pk-empty-crest" sizes="80px"/><h3>暂时没有符合条件的牌桌</h3><p>调整筛选，或在允许创建时开一张新桌。</p></div>}
        <nav className="pk-quick-row" aria-label="大厅分页"><button disabled={!ready||!p.filters.cursor} onClick={()=>{if(ready&&p.filters.cursor)changeFilters(p.filters);}}>首页</button><button disabled={!ready||!s.page.next_cursor} onClick={()=>{if(ready&&s.page.next_cursor)p.onFiltersChange({...p.filters,cursor:s.page.next_cursor});}}>下一页</button><label>每页<select value={p.filters.limit} onChange={e=>changeFilters({...p.filters,limit:Number(e.target.value)})}>{[10,25,50,100].map(n=><option key={n} value={n}>{n} 桌</option>)}</select></label></nav>
        <p className="pk-footnote">买入后等待大盲 · 创建牌桌不扣款 · 仅使用娱乐筹码</p>
      </div>
      {flow.kind==='NONE'&&<aside className="pk-flow pk-create-invitation" aria-label="创建牌桌区域"><PokerArt name="crest" sizes="150px"/><p className="pk-eyebrow">CREATE A POKER TABLE</p><h2>一桌星光，等你入席</h2><p>{s.active_session?'你的牌局仍在继续，回到当前牌桌即可。':'设定盲注与席位，邀同伴在星夜下开始下一手。'}</p><button className="pk-primary pk-full" disabled={!canCreate} onClick={()=>{if(canCreate)p.onFlowChange('CREATE');}}>设定新牌桌</button><small>创建不扣款 · 随后选择座位与买入</small></aside>}
      {flow.kind==='CREATE'&&<aside className="pk-flow" aria-label="创建牌桌表单"><div className="pk-section-heading"><h2>创建牌桌</h2><button className="pk-quiet" disabled={p.entry_pending} onClick={()=>{if(!p.entry_pending)p.onFlowChange('NONE');}}>收起</button></div><p>预设桌规，专注牌局。首笔买入后，座位与经济设置锁定。</p><form onSubmit={e=>{e.preventDefault();if(createValid)send({type:'create',name:flow.draft.name.trim(),visibility:flow.draft.visibility,...(flow.draft.visibility==='PASSWORD'?{password:flow.draft.password}:{}),max_seats:flow.draft.max_seats,blind_preset_id:flow.draft.blind_preset_id,allow_spectators:flow.draft.allow_spectators,chat_enabled:flow.draft.chat_enabled});}}><fieldset disabled={!canCreate}>
        <label>牌桌名称<input value={flow.draft.name} onChange={e=>p.onCreateDraftChange({...flow.draft,name:e.target.value})}/></label><div className="pk-form-pair"><label>访问方式<select value={flow.draft.visibility} onChange={e=>{const visibility=e.target.value as 'PUBLIC'|'PASSWORD';if(s.create_options.access_modes.includes(visibility))p.onCreateDraftChange({...flow.draft,visibility,password:visibility==='PUBLIC'?'':flow.draft.password});}}><option value="PUBLIC">公开</option>{s.create_options.access_modes.includes('PASSWORD')&&<option value="PASSWORD">密码保护</option>}</select></label><label>座位数<select value={flow.draft.max_seats} onChange={e=>p.onCreateDraftChange({...flow.draft,max_seats:Number(e.target.value)})}>{Array.from({length:8},(_,i)=><option key={i+2} value={i+2}>{i+2} 人</option>)}</select></label></div>
        {flow.draft.visibility==='PASSWORD'&&<label>牌桌密码<input type="password" autoComplete="new-password" maxLength={128} value={flow.draft.password} onChange={e=>p.onCreateDraftChange({...flow.draft,password:e.target.value})}/></label>}
        <label>盲注预设<select value={flow.draft.blind_preset_id} onChange={e=>p.onCreateDraftChange({...flow.draft,blind_preset_id:e.target.value})}>{s.blind_presets.map(x=><option key={x.id} value={x.id}>{chips(x.small_blind_units)} / {chips(x.big_blind_units)} Chips · 无 Ante</option>)}</select></label>
        <label className="pk-check"><input type="checkbox" checked={flow.draft.allow_spectators} onChange={e=>p.onCreateDraftChange({...flow.draft,allow_spectators:e.target.checked})}/>允许观战</label><label className="pk-check"><input type="checkbox" checked={flow.draft.chat_enabled} disabled={!s.create_options.chat_configurable} onChange={e=>{if(s.create_options.chat_configurable)p.onCreateDraftChange({...flow.draft,chat_enabled:e.target.checked});}}/>开放纯文字聊天</label><p className="pk-footnote">首手庄位由公平随机确定。仅服务端开始牌局，本表单不扣款或入座。</p><button className="pk-primary pk-full" disabled={!createValid} type="submit">确认创建牌桌</button>
      </fieldset></form></aside>}
      {flow.kind==='JOIN'&&<aside className="pk-flow" aria-label="座位与买入"><div className="pk-section-heading"><h2>{selected?.name??'牌桌暂不可用'}</h2><button className="pk-quiet" disabled={p.entry_pending} onClick={()=>{if(!p.entry_pending)p.onFlowChange('NONE');}}>收起</button></div><p className="pk-eyebrow">选择座位 → 预留 → 确认买入</p>
        {!flow.access_granted?<form onSubmit={e=>{e.preventDefault();if(accessReady&&validPassword(flow.draft.password))send({type:'access',table_id:flow.table_id,password:flow.draft.password});}}><label>访问牌桌密码<input type="password" autoComplete="off" maxLength={128} disabled={!accessReady} value={flow.draft.password} onChange={e=>p.onJoinDraftChange({...flow.draft,password:e.target.value})}/></label><button type="submit" disabled={!accessReady||!validPassword(flow.draft.password)}>验证密码</button></form>:<>
          {selected?.can_spectate&&<button className="pk-primary pk-full" disabled={!ready||p.entry_pending||!!s.active_session} onClick={()=>{if(ready&&!p.entry_pending&&!s.active_session)send({type:'spectate',table_id:flow.table_id});}}>以观战身份进入牌桌</button>}
          <div className="pk-seat-picker" aria-label="可选座位">{flow.seats.map(s=><button key={s.seat_no} className={flow.reservation?.seat_no===s.seat_no?'pk-seat-chosen':''} aria-label={`预留 ${s.seat_no} 号座位`} disabled={!joinReady||!flow.can_reserve||!s.available||s.seat_no<1||s.seat_no>(selected?.max_seats??0)} onClick={()=>{if(joinReady&&flow.can_reserve&&s.available&&s.seat_no>=1&&s.seat_no<=(selected?.max_seats??0))send({type:'reserve',table_id:flow.table_id,seat_no:s.seat_no});}}><span>{s.seat_no.toString().padStart(2,'0')}</span><small>{flow.reservation?.seat_no===s.seat_no?'已预留':s.available?'空座':'占用'}</small></button>)}</div>
          {flow.reservation&&<p className="pk-notice" role="status">{flow.reservation.valid?`${flow.reservation.seat_no} 号座位已预留`:'座位预留已失效'}<small>服务端截止 <time dateTime={flow.reservation.expires_at}>{flow.reservation.expires_at}</time></small></p>}
          <form onSubmit={e=>{e.preventDefault();if(buyValid&&flow.reservation&&flow.draft.seat_no!==undefined&&buyIn!==undefined)send({type:'buyin',table_id:flow.table_id,reservation_id:flow.reservation.reservation_id,seat_no:flow.draft.seat_no,amount_units:buyIn.toString(),entry_mode:'WAIT_FOR_BB'});}}><label htmlFor={`${id}-buy`}>买入筹码<input id={`${id}-buy`} inputMode="numeric" pattern="[0-9]*" disabled={!joinReady} value={flow.draft.buy_in_chips} aria-describedby={`${id}-buy-hint`} onChange={e=>p.onJoinDraftChange({...flow.draft,buy_in_chips:e.target.value})}/></label><p id={`${id}-buy-hint`} className="pk-footnote">{chips(min?.toString())}–{chips(max?.toString())} Chips（服务端买入范围）· 只接受整筹码</p>
          <div className="pk-quick-row">{[{name:'最低买入',value:min},{name:'最高买入',value:max}].map(({name,value})=><button key={name} type="button" disabled={!joinReady||value===undefined||available===undefined||available<value} onClick={()=>{if(joinReady&&value!==undefined&&available!==undefined&&available>=value)p.onJoinDraftChange({...flow.draft,buy_in_chips:(value/UNITS_PER_CHIP).toString()});}}>{name}</button>)}</div>
          {available!==undefined&&min!==undefined&&available<min&&<p className="pk-notice">可用筹码不足最低买入。<button type="button" disabled={p.entry_pending} onClick={()=>{if(!p.entry_pending)send({type:'rewards'});}}>查看奖励中心</button></p>}
          <p>新入桌后等待大盲；本手途中不发私牌。仅确认成功后才形成桌上筹码。</p><button className="pk-primary pk-full" type="submit" disabled={!buyValid}>确认买入并等待大盲</button></form>
        </>}
      </aside>}
    </div>
    <footer className="pk-utility-bar" aria-label="大厅工具"><div><button onClick={()=>setPanel('rules')}>游戏规则</button><button onClick={()=>setPanel('fairness')}>公平说明</button>{p.details&&<button onClick={()=>setPanel('entry')}>入桌状态</button>}</div><small>在星光之下，认真打好每一手。</small></footer>
    {panel&&<Modal title={panel==='rules'?'游戏规则':panel==='fairness'?'公平说明':'入桌状态'} onClose={()=>setPanel(null)}><div className="pk-modal-copy">
      {panel==='entry'?p.details:panel==='rules'?<><p>无限注德州扑克 · 2–9 人桌 · 无 Ante。</p><p>创建与买入分开。选择座位、预留成功并确认买入后，等待大盲入局；已有会话时请先返回当前牌桌。</p><p>下注/加注输入本轮总额，合法行动与金额均以服务端为准。标准高牌型比较，A2345 为五高，花色不破同分。</p><p>暂停入桌不会中断现有牌局。安全关闭后先结算与出金，关闭的牌桌从大厅移除，历史记录保留。</p></>:<><p>首手庄位公平随机，后续依规则轮转。每手公开种子与牌序的哈希承诺；未公开私牌、种子与牌序不会向其他玩家展示。</p><p>规则与算法版本来自当前服务端：</p><dl>{s.ruleset?Object.entries(s.ruleset).map(([key,value])=><div key={key}><dt>{key}</dt><dd>{value}</dd></div>):<dd>规则版本读取中</dd>}</dl><p>结算后通过牌局历史查看公开记录与检验详情。</p></>}
    </div></Modal>}
  </section>;
}
