package games

import (
	"encoding/hex"
	"math"
	"reflect"
	"strings"
	"testing"
	"time"

	bj "github.com/cy4268/momiao/internal/games/blackjack"
	"github.com/cy4268/momiao/internal/games/fairness"
	"github.com/cy4268/momiao/internal/games/slot"
)

func TestZeroEdgeConfigurations(t *testing.T) {
	ids := map[string]string{"dice": "019a5b00-0000-7000-8000-000000000001", "scratch": "019a5b00-0000-7000-8000-000000000002", "summon": "019a5b00-0000-7000-8000-000000000003"}
	dice, _ := DiceV2(ids["dice"])
	scratch, _ := NewScratchConfig(ids["scratch"], "scratch-prize-fair-v2", []Prize{{0, "LOSS", 50000}, {1, "BREAK_EVEN", 23500}, {2, "T2", 18500}, {3, "T3", 5000}, {5, "T5", 2000}, {10, "T10", 800}, {25, "T25", 180}, {100, "TOP", 20}})
	summon, _ := NewSummonConfig(ids["summon"], "summon-prize-fair-v2", []Prize{{0, "T0", 55850}, {1, "T1", 29000}, {2, "T2", 10000}, {5, "T3", 4000}, {20, "T4", 1050}, {100, "T5", 100}})
	for _, c := range []Config{dice, scratch, summon} {
		stats, err := c.Statistics()
		if err != nil || stats.RTP.RatString() != "1" {
			t.Fatalf("%s RTP = %v (%v)", c.binding.Game, stats.RTP, err)
		}
	}
	seed := make([]byte, 32)
	commitment, _ := fairness.SeedCommitment(seed)
	fair := FairRound{ID: [16]byte{0, 0, 0, 0, 0, 0, 0x70, 0, 0x80}, Game: "dice", ClientSeed: "zero-edge-test", StreamVersion: fairness.StreamVersion, AlgorithmVersion: DiceAlgorithm, ConfigVersion: dice.binding.Version, ConfigHash: dice.binding.Hash, ServerSeedHash: commitment}
	foundTriple := false
	for nonce := int64(0); nonce < 10_000; nonce++ {
		fair.Nonce = nonce
		rolled, err := RollDice(seed, fair, dice, Big)
		if err != nil {
			t.Fatal(err)
		}
		if rolled.Triple {
			if rolled.Reward.PayoutMultiplier != 1 || rolled.Reward.Outcome != BreakEven {
				t.Fatal("v2 triple did not return the wager")
			}
			foundTriple = true
			break
		}
	}
	if !foundTriple {
		t.Fatal("deterministic triple fixture not found")
	}
	paytable := slot.FairConfig().Paytable
	if paytable[1][0] != 10 || paytable[2][2] != 175 || paytable[6][0] != 115 {
		t.Fatal("fair slot paytable mismatch")
	}
	state := bj.State{Phase: bj.Settled, InitialWagerUnits: 10_000_000, TotalStakeUnits: 10_000_000, TotalPayoutUnits: 10_000_000, CreatedAt: time.Unix(1, 0)}
	bonus, err := blackjackFairReturn(nil, FairRound{}, bj.FairRulesetVersion, state.InitialWagerUnits)
	if err != nil || bonus != 37_079 || addBlackjackFairReturn(&state, bonus) != nil || state.FairReturnUnits != bonus || state.TotalPayoutUnits != 10_037_079 {
		t.Fatal("blackjack fair return mismatch", bonus, err, state)
	}
}

func TestConfigCanonicalHashesIndependentVectors(t *testing.T) {
	// Generated by an independent Python hashlib/json implementation of the
	// documented envelope and typed payloads, not by the Go hasher under test.
	for _, tc := range []struct {
		make func(string) (Config, error)
		want string
	}{
		{DiceV1, "849610640163e4f80097687440a772e4739ead6b84a2339b18a6a1285645f449"},
		{ScratchV1, "1ec38f8e9a18960ccf267f09723b5136e101af9af0f7f740debcad9ec7224471"},
		{SummonV1, "b7df2196e05885cd6ecedcf6617eb8e1ed73e6e403469212e078729b3044ba13"},
	} {
		c, err := tc.make("fixture-v1")
		if err != nil {
			t.Fatal(err)
		}
		b := c.Binding()
		if hex.EncodeToString(b.Hash[:]) != tc.want {
			t.Fatalf("%s hash: %x", b.Game, b.Hash)
		}
	}
}

func TestFrozenConfigurationsAndExactStatistics(t *testing.T) {
	for _, tc := range []struct {
		name string
		make func(string) (Config, error)
		want []string
	}{
		{"dice", DiceV1, []string{"35/36", "37/72", "0", "35/72", "0"}},
		{"scratch", ScratchV1, []string{"24/25", "27/50", "39/200", "53/200", "1/5000"}},
		{"summon", SummonV1, []string{"24/25", "1197/2000", "1/4", "303/2000", "1/1000"}},
	} {
		t.Run(tc.name, func(t *testing.T) {
			c, err := tc.make("fixture-v1")
			if err != nil {
				t.Fatal(err)
			}
			b := c.Binding()
			if b.Game != tc.name || b.Version != "fixture-v1" || b.Hash == ([32]byte{}) {
				t.Fatal("missing config identity", b)
			}
			stats, err := c.Statistics()
			if err != nil {
				t.Fatal(err)
			}
			got := []string{stats.RTP.RatString(), stats.Loss.RatString(), stats.BreakEven.RatString(), stats.Win.RatString(), stats.Top.RatString()}
			if !reflect.DeepEqual(got, tc.want) {
				t.Fatalf("statistics: %v, want %v", got, tc.want)
			}
		})
	}
	if _, err := (Config{}).Statistics(); err == nil {
		t.Fatal("zero config accepted")
	}
}

func TestConfigurationValidationAndImmutability(t *testing.T) {
	for _, makeConfig := range []func(string) (Config, error){DiceV1, ScratchV1, SummonV1} {
		for _, version := range []string{"", "bad version", "a\x00b", "版本", strings.Repeat("x", 129)} {
			if _, err := makeConfig(version); err == nil {
				t.Fatal("invalid config version accepted")
			}
		}
	}
	for _, tc := range []struct {
		makeDefault func(string) (Config, error)
		makeCustom  func(string, string, []Prize) (Config, error)
	}{
		{ScratchV1, NewScratchConfig},
		{SummonV1, NewSummonConfig},
	} {
		base, _ := tc.makeDefault("fixture-v1")
		for name, mutate := range map[string]func([]Prize) []Prize{
			"empty":                  func(p []Prize) []Prize { return nil },
			"missing tier":           func(p []Prize) []Prize { return p[1:] },
			"duplicate tier":         func(p []Prize) []Prize { p[1].Tier = p[0].Tier; return p },
			"unknown tier":           func(p []Prize) []Prize { p[1].Tier = "UNKNOWN"; return p },
			"negative weight":        func(p []Prize) []Prize { p[0].Weight = -1; return p },
			"weight overflow":        func(p []Prize) []Prize { p[0].Weight = math.MaxInt64; return p },
			"total too small":        func(p []Prize) []Prize { p[0].Weight--; return p },
			"total too large":        func(p []Prize) []Prize { p[0].Weight++; return p },
			"negative multiplier":    func(p []Prize) []Prize { p[0].Multiplier = -1; return p },
			"unsupported multiplier": func(p []Prize) []Prize { p[0].Multiplier = 1; return p },
		} {
			t.Run(base.Binding().Game+"/"+name, func(t *testing.T) {
				if _, err := tc.makeCustom("fixture-v2", "custom-prize-v2", mutate(base.Prizes())); err == nil {
					t.Fatal("invalid table accepted")
				}
			})
		}
		p := base.Prizes()
		p[0].Weight--
		p[1].Weight++
		if _, err := tc.makeCustom("fixture-v2", base.Binding().PrizeTableVersion, p); err == nil {
			t.Fatal("changed frozen v1 table accepted under its original identity")
		}
		if _, err := tc.makeCustom("fixture-v2", "", p); err == nil {
			t.Fatal("empty prize version accepted")
		}
		custom, err := tc.makeCustom("fixture-v2", "custom-prize-v2", p)
		if err != nil || custom.Binding().Hash == base.Binding().Hash {
			t.Fatal("new version/table not bound", err)
		}
		hash := custom.Binding().Hash
		p[0].Weight = 0
		publicCopy := custom.Prizes()
		publicCopy[0].Weight = 0
		if custom.Prizes()[0].Weight != base.Prizes()[0].Weight-1 || custom.Binding().Hash != hash {
			t.Fatal("configuration aliases mutable caller data")
		}
		// Alternative table order is preserved and changes its hash and mapping.
		p = base.Prizes()
		p[0], p[1] = p[1], p[0]
		reordered, err := tc.makeCustom("fixture-v2", "custom-prize-v2", p)
		if err != nil || reordered.Prizes()[0].Tier != p[0].Tier || reordered.Binding().Hash == hash {
			t.Fatal("configured table order lost", err)
		}
		for i := range p {
			p[i].Weight = 0
		}
		p[0].Weight = 100000
		if _, err := tc.makeCustom("fixture-v3", "custom-prize-v3", p); err != nil {
			t.Fatalf("valid zero-weight tiers rejected: %v", err)
		}
	}
}

func TestWeightedChoiceExhaustiveIntervals(t *testing.T) {
	// Every possible uniform prize sample is checked against independently
	// specified interval counts. This catches off-by-one cumulative comparisons.
	for _, tc := range []struct {
		make func(string) (Config, error)
		want map[string]int
	}{
		{ScratchV1, map[string]int{"LOSS": 54000, "BREAK_EVEN": 19500, "T2": 18500, "T3": 5000, "T5": 2000, "T10": 800, "T25": 180, "TOP": 20}},
		{SummonV1, map[string]int{"T0": 59850, "T1": 25000, "T2": 10000, "T3": 4000, "T4": 1050, "T5": 100}},
	} {
		c, _ := tc.make("fixture-v1")
		counts := map[string]int{}
		for sample := uint64(0); sample < 100000; sample++ {
			prize, err := c.prizeAt(sample)
			if err != nil {
				t.Fatal(err)
			}
			counts[prize.Tier]++
		}
		if !reflect.DeepEqual(counts, tc.want) {
			t.Fatal(counts, tc.want)
		}
		for _, sample := range []uint64{100000, math.MaxUint64} {
			if _, err := c.prizeAt(sample); err == nil {
				t.Fatal("invalid sample accepted")
			}
		}
	}
	// Zero-weight entries, including the first and last, are never selected.
	base, _ := SummonV1("fixture-v1")
	p := base.Prizes()
	for i := range p {
		p[i].Weight = 0
	}
	p[2].Weight = 100000
	c, _ := NewSummonConfig("fixture-v2", "custom-prize-v2", p)
	for _, sample := range []uint64{0, 99999} {
		got, err := c.prizeAt(sample)
		if err != nil || got.Tier != "T2" {
			t.Fatal(got, err)
		}
	}
}
