import { ApiClient, ApiError } from '../api';

export type OpsPrincipal={principal_id:string;newapi_user_id:string;base_role:'SUPER_ADMIN'|'OPERATOR'|'AUDITOR';status:'ACTIVE';authz_epoch:string;version:string;scopes:string[];permissions:string[]};
export type OpsDescriptor={operation_type:string;risk_level:'LEVEL_1_ROUTINE'|'LEVEL_2_IMPACTFUL'|'LEVEL_3_CRITICAL';required_permission:string;allowed_roles:string[];target_type:string;input_schema_version:string;impact_schema_version:string;requires_reason:boolean;requires_fresh_auth:boolean;confirmation_mode:'NONE'|'EXPLICIT'|'TYPED';supports_schedule:boolean;execution_mode:'SAME_DATABASE'|'DURABLE_REMOTE';available:boolean};
export type OpsBootstrap={principal:OpsPrincipal;registry_version:string;operations:OpsDescriptor[]};
export type OpsTarget={type:string;id:string;expected_version:string};
export type OpsImpact={target:OpsTarget;environment:string;current_state:Record<string,unknown>;proposed_change:Record<string,unknown>;before?:Record<string,unknown>;delta?:Record<string,unknown>;after?:Record<string,unknown>;affected_users?:number;affected_items?:number;blocking_facts:string[];continuing_accepted_work:string[];related_ids:string[];unavailable_measurements:string[]};
export type OpsOperation={operation_id:string;operation_type:string;actor_newapi_user_id:string;actor_authz_epoch_snapshot:string;target:OpsTarget;environment:string;impact_preview:OpsImpact;impact_hash:string;confirmation_mode:'NONE'|'EXPLICIT'|'TYPED';requires_fresh_auth:boolean;state:string;state_version:string;reason:string;failure_code?:string;result:Record<string,unknown>;created_at:string;updated_at:string;related_business_id?:string};
export type OpsPrepared={operation:OpsOperation;descriptor:OpsDescriptor;confirmation_phrase?:string;fresh_challenge?:{challenge_id:string;challenge_token:string;expires_at:string}};
export type OpsOperationView={operation:OpsOperation;timeline:{event_id:string;state:string;substate?:string;state_version:string;failure_code?:string;occurred_at:string}[];audit_id?:string};
export type OpsCommand={operation_type:string;target:OpsTarget;input:Record<string,unknown>;reason:string};
export const opsID=(value:unknown):value is string=>typeof value==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/.test(value);
export const opsVersion=(value:unknown):value is string=>typeof value==='string'&&/^[1-9][0-9]{0,18}$/.test(value);
const operationStates=['PREPARED','AUTHORIZED','EXECUTING','SUCCEEDED','FAILED_NO_EFFECT','RECOVERING','NEEDS_REVIEW','CANCELLED'];
const record=(value:unknown):value is Record<string,unknown>=>!!value&&typeof value==='object'&&!Array.isArray(value);
const strings=(value:unknown):value is string[]=>Array.isArray(value)&&value.length<=1000&&value.every(item=>typeof item==='string');
function checkImpact(value:OpsImpact){return record(value)&&record(value.current_state)&&record(value.proposed_change)&&strings(value.blocking_facts)&&strings(value.continuing_accepted_work)&&strings(value.related_ids)&&strings(value.unavailable_measurements)&&['before','delta','after'].every(key=>value[key as 'before'|'delta'|'after']===undefined||record(value[key as 'before'|'delta'|'after']));}
export function checkOperation(value:OpsOperation){if(!value||!opsID(value.operation_id)||typeof value.operation_type!=='string'||!opsVersion(value.actor_newapi_user_id)||!opsVersion(value.actor_authz_epoch_snapshot)||!opsVersion(value.state_version)||!value.target||typeof value.target.id!=='string'||typeof value.target.type!=='string'||!['DEVELOPMENT','STAGING','PRODUCTION'].includes(value.environment)||!checkImpact(value.impact_preview)||!/^[0-9a-f]{64}$/.test(value.impact_hash)||!operationStates.includes(value.state)||typeof value.reason!=='string'||!['NONE','EXPLICIT','TYPED'].includes(value.confirmation_mode)||typeof value.requires_fresh_auth!=='boolean'||!record(value.result)||!Number.isFinite(Date.parse(value.created_at))||!Number.isFinite(Date.parse(value.updated_at)))throw new ApiError('操作响应格式异常，请按原编号查询。');return value;}
export function checkOperationView(value:OpsOperationView){checkOperation(value?.operation);if(!Array.isArray(value.timeline)||value.timeline.some(event=>!event||!opsID(event.event_id)||!opsVersion(event.state_version)||!operationStates.includes(event.state)||!Number.isFinite(Date.parse(event.occurred_at))))throw new ApiError('操作时间线格式异常。');return value;}
export function canAcknowledgeOpsReview(value:OpsOperationView|undefined){return !!value&&value.operation.state==='NEEDS_REVIEW'&&value.operation.result.remote_receipt_accepted===true&&value.operation.result.remote_receipt_state==='NEEDS_REVIEW'&&typeof value.operation.result.remote_receipt_hash==='string'&&/^[0-9a-f]{64}$/.test(value.operation.result.remote_receipt_hash)&&opsID(value.audit_id);}
export function checkPrincipal(value:OpsPrincipal){
 if(!value||!opsID(value.principal_id)||!opsVersion(value.newapi_user_id)||!['SUPER_ADMIN','OPERATOR','AUDITOR'].includes(value.base_role)||value.status!=='ACTIVE'||!opsVersion(value.authz_epoch)||!opsVersion(value.version)||!Array.isArray(value.scopes)||value.scopes.some(scope=>typeof scope!=='string')||!Array.isArray(value.permissions)||value.permissions.some(permission=>typeof permission!=='string')||new Set(value.permissions).size!==value.permissions.length)throw new ApiError('运营身份响应格式异常。');
 return value;
}
export async function readOpsBootstrap(client:ApiClient):Promise<OpsBootstrap>{
 const data=await client.request<OpsBootstrap>('/api/v1/ops/bootstrap');
 if(!data||typeof data.registry_version!=='string'||!Array.isArray(data.operations))throw new ApiError('运营入口暂不可用。');
 checkPrincipal(data.principal);
 if(data.operations.some(item=>!item||typeof item.operation_type!=='string'||!/^[A-Z][A-Z0-9_]{0,127}$/.test(item.operation_type)||!['LEVEL_1_ROUTINE','LEVEL_2_IMPACTFUL','LEVEL_3_CRITICAL'].includes(item.risk_level)||typeof item.required_permission!=='string'||!strings(item.allowed_roles)||typeof item.target_type!=='string'||typeof item.input_schema_version!=='string'||typeof item.impact_schema_version!=='string'||typeof item.requires_reason!=='boolean'||typeof item.requires_fresh_auth!=='boolean'||typeof item.supports_schedule!=='boolean'||typeof item.available!=='boolean'||!['NONE','EXPLICIT','TYPED'].includes(item.confirmation_mode)||!['SAME_DATABASE','DURABLE_REMOTE'].includes(item.execution_mode))||new Set(data.operations.map(item=>item.operation_type)).size!==data.operations.length)throw new ApiError('运营操作目录响应格式异常。');
 return data;
}
const messages:Record<string,string>={OPS_FORBIDDEN:'你没有这项运营权限。',AUTHORIZATION_STALE:'运营权限已变更，请刷新页面后重新核对。',PREVIEW_STALE:'操作影响已变化，请返回编辑后重新预览。',OPS_CONFIRMATION_REQUIRED:'请完成本次操作的确认。',FRESH_AUTH_REQUIRED:'请先完成本次操作的身份验证。',OPS_OPERATION_CONFLICT:'该操作编号已绑定其他内容，请核对原操作。',OPS_CAPABILITY_UNAVAILABLE:'该运营能力暂不可用。',LAST_SUPER_ADMIN_REQUIRED:'必须保留至少一位有效的最高管理员。',OPERATION_ENVIRONMENT_MISMATCH:'当前环境与操作预览不一致，请重新核对。'};
export function opsError(error:unknown):string{return error instanceof ApiError?(Object.hasOwn(messages,error.code)?messages[error.code]:error.message):error instanceof Error?error.message:'运营请求失败，请重新加载。';}
