import { useEffect, useState, type FormEvent } from 'react';
import { Alert, Empty, Loading, useResource } from '../ui';
import { opsError, opsID, opsVersion } from './ops-api';
import { OpsMutationPanel, useOpsMutation } from './OpsMutation';
import { opsState } from './OpsOperationDetail';
import { useOps } from './OpsShell';

type Principal={principal_id:string;newapi_user_id:string;base_role:'SUPER_ADMIN'|'OPERATOR'|'AUDITOR';status:'ACTIVE'|'DISABLED';authz_epoch:string;version:string;scopes:string[]};
const scopeNames:Record<string,string>={ANNOUNCEMENTS:'公告',GAMES:'游戏',MODELS:'模型',POKER:'Poker',RANKINGS:'排行榜',RECORDS:'记录与支持',REWARDS:'奖励',USERS_IDENTITY:'用户身份'};
const actions:Record<string,string>={CREATE:'新增运营身份',CHANGE_ROLE:'更改角色',CHANGE_SCOPES:'更改授权范围',DISABLE:'停用身份',ENABLE:'重新启用'};
export function OpsAccessControl(){
 const {client,bootstrap,reload}=useOps();const mutation=useOpsMutation();const [target,setTarget]=useState<Principal>(),[action,setAction]=useState('CREATE'),[user,setUser]=useState(''),[role,setRole]=useState<Principal['base_role']>('OPERATOR'),[scopes,setScopes]=useState<string[]>([]),[reason,setReason]=useState(''),[error,setError]=useState('');
 const resource=useResource(async()=>{try{const value=await client.request<{items:Principal[]}>(`/api/v1/ops/admin-principals?authz_epoch=${bootstrap.principal.authz_epoch}`);if(!value||!Array.isArray(value.items)||value.items.some(item=>!item||!opsID(item.principal_id)||!opsVersion(item.newapi_user_id)||!opsVersion(item.version)||!opsVersion(item.authz_epoch)||!['SUPER_ADMIN','OPERATOR','AUDITOR'].includes(item.base_role)||!['ACTIVE','DISABLED'].includes(item.status)||!Array.isArray(item.scopes)||item.scopes.some(scope=>!scopeNames[scope])))throw new Error('运营身份列表格式异常。');return value.items;}catch(error){throw new Error(opsError(error));}},[client,bootstrap.principal.authz_epoch]);
 const state=mutation.receipt?.operation.state,id=mutation.receipt?.operation.operation_id;
 useEffect(()=>{if(state==='SUCCEEDED'){resource.reload();if(target?.principal_id===bootstrap.principal.principal_id)reload()}},[state,id]);
 const writable=bootstrap.principal.permissions.includes('access_control.write'),blocked=!!mutation.pending||mutation.busy;
 function select(item:Principal){setTarget(item);setUser(item.newapi_user_id);setRole(item.base_role);setScopes([...item.scopes]);setAction('CHANGE_ROLE');setReason('');setError('')}
 function create(){setTarget(undefined);setUser('');setRole('OPERATOR');setScopes([]);setAction('CREATE');setReason('');setError('')}
 function submit(event:FormEvent){event.preventDefault();setError('');if(!reason.trim()){setError('请填写本次权限变更的原因。');return}const input:Record<string,unknown>={action};if(action==='CREATE'){if(!opsVersion(user.trim())){setError('请输入有效的账户编号。');return}input.newapi_user_id=user.trim();input.base_role=role;input.scopes=role==='OPERATOR'?scopes:[]}else if(action==='CHANGE_ROLE')input.base_role=role;else if(action==='CHANGE_SCOPES')input.scopes=scopes;
  mutation.prepare({operation_type:'ACCESS_CONTROL_CHANGE',target:{type:'ADMIN_PRINCIPAL',id:target?.principal_id||crypto.randomUUID(),expected_version:target?.version||'1'},input,reason:reason.trim()});
 }
 return <><header className="page-heading"><div><p className="eyebrow">OPERATIONS / ACCESS CONTROL</p><h1>访问控制</h1><p>管理平台运营身份、角色和业务范围。</p></div><button onClick={resource.reload} disabled={resource.loading||blocked}>重新核对权限</button></header>{writable&&<section className="panel"><h2>{target?`管理账户 ${target.newapi_user_id}`:'新增运营身份'}</h2><form onSubmit={submit}><fieldset disabled={blocked}><legend>权限设置</legend>{target?<><label>操作<select value={action} onChange={event=>setAction(event.target.value)}><option value="CHANGE_ROLE">更改角色</option>{target.base_role==='OPERATOR'&&<option value="CHANGE_SCOPES">更改授权范围</option>}<option value={target.status==='ACTIVE'?'DISABLE':'ENABLE'}>{target.status==='ACTIVE'?'停用身份':'重新启用'}</option></select></label><button type="button" onClick={create}>改为新增身份</button></>:<label>已有平台账户编号<input value={user} onChange={event=>setUser(event.target.value)} inputMode="numeric" maxLength={19} required/></label>}{['CREATE','CHANGE_ROLE'].includes(action)&&<label>角色<select value={role} onChange={event=>setRole(event.target.value as Principal['base_role'])}><option value="OPERATOR">运营人员</option><option value="AUDITOR">审计员</option><option value="SUPER_ADMIN">最高管理员</option></select></label>}{(action==='CREATE'&&role==='OPERATOR'||action==='CHANGE_SCOPES')&&<fieldset><legend>运营范围</legend>{Object.entries(scopeNames).map(([key,label])=><label key={key}><input type="checkbox" checked={scopes.includes(key)} onChange={event=>setScopes(old=>event.target.checked?[...old,key]:old.filter(item=>item!==key))}/>{label}</label>)}</fieldset>}<p className="hint">审计员仅有读取权限。系统会保留至少一位有效的最高管理员，并在权限变化后重新核对后续请求。</p><label>变更原因<textarea value={reason} onChange={event=>setReason(event.target.value)} rows={3} maxLength={500} required/></label><button type="submit">预览{actions[action]}</button></fieldset></form>{error&&<Alert>{error}</Alert>}</section>}<OpsMutationPanel mutation={mutation}/><section className="panel"><h2>运营身份</h2>{resource.loading?<Loading/>:resource.error?<Alert>{resource.error}</Alert>:resource.data?.length?<div className="table-wrap" role="region" aria-label="运营身份列表" tabIndex={0}><table><thead><tr><th>账户</th><th>角色与状态</th><th>运营范围</th><th>权限版本</th>{writable&&<th>管理</th>}</tr></thead><tbody>{resource.data.map(item=><tr key={item.principal_id}><td>{item.newapi_user_id}</td><td>{opsState[item.base_role]} · {opsState[item.status]}</td><td>{item.base_role==='OPERATOR'?item.scopes.map(scope=>scopeNames[scope]).join('、')||'未分配业务范围':item.base_role==='AUDITOR'?'审计只读':'最高管理员权限'}</td><td>{item.authz_epoch}</td>{writable&&<td><button onClick={()=>select(item)} disabled={blocked}>管理</button></td>}</tr>)}</tbody></table></div>:<Empty title="未读取到运营身份">请核对当前环境和授权状态。</Empty>}</section></>;
}
