import { useState, type FormEvent } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Alert, Empty, Loading, useResource } from '../ui';
import { opsError, opsID, opsVersion } from './ops-api';
import { OpsFacts, opsState, opsTime } from './OpsOperationDetail';
import { useOps } from './OpsShell';

type Audit={audit_id:string;actor_newapi_user_id:string;actor_role:string;action:string;target_type:string;target_id:string;before_snapshot:Record<string,unknown>;after_snapshot:Record<string,unknown>;reason:string;operation_id:string;result:Record<string,unknown>;environment:string;occurred_at:string};
function checkAudit(value:Audit){if(!value||!opsID(value.audit_id)||!opsID(value.operation_id)||!opsVersion(value.actor_newapi_user_id)||typeof value.action!=='string'||typeof value.target_id!=='string'||!Number.isFinite(Date.parse(value.occurred_at))||!['DEVELOPMENT','STAGING','PRODUCTION'].includes(value.environment))throw new Error('审计响应格式异常。');return value;}
export function OpsAudit(){
 const {client,bootstrap}=useOps();const [operation,setOperation]=useState(''),[actor,setActor]=useState(''),[target,setTarget]=useState(''),[query,setQuery]=useState(''),[error,setError]=useState('');
 const resource=useResource(async()=>{try{const value=await client.request<{items:Audit[]}>(`/api/v1/ops/audit?authz_epoch=${bootstrap.principal.authz_epoch}&limit=50${query}`);if(!value||!Array.isArray(value.items))throw new Error('审计列表格式异常。');return value.items.map(checkAudit);}catch(error){throw new Error(opsError(error));}},[client,bootstrap.principal.authz_epoch,query]);
 function filter(event:FormEvent){event.preventDefault();if(operation&&!opsID(operation.trim())||actor&&!opsVersion(actor.trim())){setError('请核对操作编号和账户编号。');return}setError('');const next=new URLSearchParams();if(operation.trim())next.set('operation_id',operation.trim());if(actor.trim())next.set('actor_newapi_user_id',actor.trim());if(target.trim())next.set('target_id',target.trim());setQuery(next.size?'&'+next.toString():'');}
 return <><header className="page-heading ops-system-heading"><div><p className="eyebrow">OPERATIONS / AUDIT</p><h1>审计记录</h1><p>核对管理操作的执行者、目标、变更前后状态和处理结果。</p></div><button onClick={resource.reload} disabled={resource.loading}>刷新记录</button></header><section className="panel ops-system-list"><form className="filters" onSubmit={filter}><label>操作编号<input value={operation} onChange={event=>setOperation(event.target.value)} maxLength={36}/></label><label>执行账户<input value={actor} onChange={event=>setActor(event.target.value)} inputMode="numeric" maxLength={19}/></label><label>目标编号<input value={target} onChange={event=>setTarget(event.target.value)} maxLength={128}/></label><button type="submit">筛选</button></form>{error&&<Alert>{error}</Alert>}{resource.loading?<Loading/>:resource.error?<Alert>{resource.error}</Alert>:resource.data?.length?<><div className="table-wrap" role="region" aria-label="审计记录" tabIndex={0}><table><thead><tr><th>时间</th><th>操作</th><th>执行账户</th><th>目标</th><th>详情</th></tr></thead><tbody>{resource.data.map(item=><tr key={item.audit_id}><td>{opsTime(item.occurred_at)}</td><td>{item.action}</td><td>{item.actor_newapi_user_id}</td><td>{item.target_id}</td><td><Link to={`/ops/audit/${item.audit_id}`}>查看审计</Link></td></tr>)}</tbody></table></div><p className="hint">显示符合筛选条件的最新 50 条记录。可按原操作编号缩小范围。</p></>:<Empty title="没有匹配的审计记录">调整筛选条件后重试。</Empty>}</section></>;
}
export function OpsAuditDetail(){
 const {auditID=''}=useParams();const {client,bootstrap}=useOps();const resource=useResource(async()=>{if(!opsID(auditID))throw new Error('审计编号无效。');try{return checkAudit(await client.request<Audit>(`/api/v1/ops/audit/${auditID}?authz_epoch=${bootstrap.principal.authz_epoch}`));}catch(error){throw new Error(opsError(error));}},[client,bootstrap.principal.authz_epoch,auditID]);
 const item=resource.data;
 return <><header className="page-heading ops-system-heading"><div><p className="eyebrow">OPERATIONS / AUDIT DETAIL</p><h1>审计详情</h1><Link to="/ops/audit">返回审计记录</Link></div><button onClick={resource.reload} disabled={resource.loading}>重新读取</button></header>{resource.loading?<Loading/>:resource.error?<Alert>{resource.error}</Alert>:item&&<><section className="panel ops-system-audit-summary"><dl className="ops-impact"><div><dt>执行账户</dt><dd>{item.actor_newapi_user_id} · {opsState[item.actor_role]||item.actor_role}</dd></div><div><dt>操作</dt><dd>{item.action}</dd></div><div><dt>目标</dt><dd>{item.target_id}</dd></div><div><dt>环境与时间</dt><dd>{opsState[item.environment]} · {opsTime(item.occurred_at)}</dd></div></dl><p>原因：{item.reason}</p><Link to={`/ops/operations/${item.operation_id}`}>查看原操作及时间线 →</Link></section><section className="panel ops-system-audit-evidence"><h2>变更快照与处理结果</h2><div className="ops-system-snapshot-grid"><div><h3>变更前</h3><OpsFacts value={item.before_snapshot}/></div><div><h3>变更后</h3><OpsFacts value={item.after_snapshot}/></div><div><h3>处理结果</h3><OpsFacts value={item.result}/></div></div></section></>}</>;
}
