import { useState } from 'react';
import { Alert, Loading, useResource } from '../ui';
import { OpsMutationPanel, useOpsMutation } from './OpsMutation';
import { OpsFacts, opsTime } from './OpsOperationDetail';
import { opsAmount, opsInt64, opsRecord, opsTimestamp } from './OpsEconomy';
import { useOps } from './OpsShell';

const campaignID='01995000-2026-7000-8000-000000000927';
const phases:Record<string,string>={DRAFT:'尚未开始',SNAPSHOT_PREPARING:'资格快照进行中',SNAPSHOT_READY:'资格已封存',GRANTED:'勋章已授予',RESET_PREPARING:'重置预检进行中',RESET_READY:'等待单独确认重置',RESET_RUNNING:'重置进行中',COMPLETED:'重置完成'};
type View={id:string;version:string;phase:string;cutoff_at:string|null;reset_cutoff_at:string|null;target_count:string;completed_count:string;eligible_count:string;blocking_facts:string[];native_unchanged:boolean;policy_activated_at:string|null;rankings_published_at:string|null;accounts:{user_id:string;eligible:boolean;qualification_units:string;reset_state:string;reset_before:unknown;reset_after:unknown;reset_receipt:unknown}[];next_user_id?:string};
function readView(value:unknown):View{
 if(!opsRecord(value)||value.id!==campaignID||!opsInt64(value.version)||typeof value.phase!=='string'||!phases[value.phase]||(['target_count','completed_count','eligible_count'] as const).some(k=>!opsInt64(value[k]))||typeof value.native_unchanged!=='boolean'||!Array.isArray(value.blocking_facts)||value.blocking_facts.some(x=>typeof x!=='string')||!Array.isArray(value.accounts)||value.accounts.length>50||(['cutoff_at','reset_cutoff_at','policy_activated_at','rankings_published_at'] as const).some(k=>value[k]!==null&&!opsTimestamp(value[k]))||value.accounts.some(a=>!opsRecord(a)||!opsInt64(a.user_id)||typeof a.eligible!=='boolean'||!(a.qualification_units===''||opsInt64(a.qualification_units)))||value.next_user_id!==undefined&&!opsInt64(value.next_user_id))throw new Error('活动状态响应异常，请重新读取。');
 return value as unknown as View;
}
export function OpsGamblerCampaign(){
 const {client,bootstrap}=useOps(),mutation=useOpsMutation();
 const [after,setAfter]=useState(''),[maintenance,setMaintenance]=useState(''),[evidence,setEvidence]=useState(''),[backup,setBackup]=useState(''),[reason,setReason]=useState('');
 const status=useResource(async()=>readView(await client.request<unknown>(`/api/v1/ops/economy/gambler-campaigns/${campaignID}${after?'?after_user='+after:''}`)),[client,after,mutation.receipt?.operation.state]);
 const view=status.data;
 const actions=view?({DRAFT:[['GAMBLER_SNAPSHOT_PREPARE','预览资格快照']],SNAPSHOT_READY:[['GAMBLER_MEDALS_GRANT','预览勋章授予'],['GAMBLER_REAUTHORIZE','预览续授权与换维护窗口']],GRANTED:[['GAMBLER_RESET_PREPARE','预览重置预检']],SNAPSHOT_PREPARING:[['GAMBLER_REAUTHORIZE','预览续授权与换维护窗口']],RESET_PREPARING:[['GAMBLER_REAUTHORIZE','预览续授权与换维护窗口']],RESET_RUNNING:[['GAMBLER_REAUTHORIZE','预览续授权与换维护窗口']],RESET_READY:[['GAMBLER_RESET_START','预览并单独确认重置'],['GAMBLER_REAUTHORIZE','预览续授权与换维护窗口']],COMPLETED:view.policy_activated_at?[]:[['ECONOMY_POLICY_ACTIVATE','预览新政策激活'],['GAMBLER_REAUTHORIZE','预览续授权与换维护窗口']]} as Record<string,string[][]>)[view.phase]||[]:[];
 function prepare(action:string){if(!view)return;const preparatory=action.endsWith('_PREPARE')||action==='GAMBLER_REAUTHORIZE';mutation.prepare({operation_type:action,target:{type:'GAMBLER_CAMPAIGN',id:campaignID,expected_version:view.version},input:preparatory?{maintenance_id:maintenance.trim(),native_pause_evidence:evidence.trim(),...(action==='GAMBLER_RESET_PREPARE'?{backup_reference:backup.trim()}:{})}:{},reason:reason.trim()})}
 return <section className="panel ops-business-campaign"><div className="section-heading"><div><p className="eyebrow">ONE-TIME / GAMBLER</p><h2>赌怪 · 永久勋章与资产重置</h2></div><button onClick={status.reload} disabled={status.loading}>刷新活动状态</button></div><p>资格按封存时统一资产严格超过十亿判定，授予后永久保留。重置是独立操作：每人 Reserve 变为 10,000 API Credits，可用筹码变为 0；原生可用额度保持原值。</p><p className="hint">先建立所需维护窗口、暂停 Native 模型新消费并排空在途请求；填写的是停流与备份凭据的引用，不是密码或密钥。页面不会自行启动活动。预览差额以原生单位展示，500,000 单位等于 1 API Credit 或 1 筹码。</p>{status.loading?<Loading/>:status.error?<Alert>{status.error}</Alert>:view&&<><dl className="ops-impact"><div><dt>阶段 / 版本</dt><dd>{phases[view.phase]} · {view.version}</dd></div><div><dt>资格截止</dt><dd>{view.cutoff_at?opsTime(view.cutoff_at):'尚未冻结'}</dd></div><div><dt>符合资格</dt><dd>{view.eligible_count} 人</dd></div><div><dt>本阶段目标 / 已重置</dt><dd>{view.target_count} / {view.completed_count}</dd></div><div><dt>Native 核对</dt><dd>{view.native_unchanged?'原值保留；逐批复核':'发现变化，活动已停止推进'}</dd></div><div><dt>政策 / 榜单</dt><dd>{view.policy_activated_at?'已激活':'尚未激活'} / {view.rankings_published_at?'已刷新':'等待完成并开放榜单发布'}</dd></div></dl>{view.blocking_facts.length>0&&<Alert><strong>未决项</strong><ul>{view.blocking_facts.map(f=><li key={f}>{f}</li>)}</ul></Alert>}<div className="ops-business-adjustment-form"><fieldset disabled={!!mutation.pending}><label>维护窗口编号<input value={maintenance} onChange={e=>setMaintenance(e.target.value)} maxLength={36}/></label><label>Native 停流与排空依据<input value={evidence} onChange={e=>setEvidence(e.target.value)} maxLength={256}/></label><label>重置前备份引用<input value={backup} onChange={e=>setBackup(e.target.value)} maxLength={256}/></label><label>操作原因<textarea value={reason} onChange={e=>setReason(e.target.value)} maxLength={1000}/></label>{actions.filter(([action])=>bootstrap.operations.some(o=>o.operation_type===action&&o.available&&bootstrap.principal.permissions.includes(o.required_permission))).map(([action,label])=><button key={action} disabled={!reason.trim()} onClick={()=>prepare(action)}>{label}</button>)}</fieldset></div><details><summary>私有账户资格、差额与审计回执</summary><div className="table-wrap"><table><thead><tr><th>账户</th><th>封存资产</th><th>资格</th><th>重置状态 / 回执</th></tr></thead><tbody>{view.accounts.map(a=><tr key={a.user_id}><td>{a.user_id}</td><td>{a.qualification_units?opsAmount(a.qualification_units):'待观察'}</td><td>{a.eligible?'符合':'未授予'}</td><td>{a.reset_state}<details><summary>查看差额与回执</summary><OpsFacts value={{before:a.reset_before,after:a.reset_after,receipt:a.reset_receipt}}/></details></td></tr>)}</tbody></table></div>{after&&<button onClick={()=>setAfter('')}>首页</button>}{view.next_user_id&&<button onClick={()=>setAfter(view.next_user_id!)}>下一页</button>}</details></>}<OpsMutationPanel mutation={mutation}/></section>;
}
