import { useEffect, useState, type FormEvent } from 'react';
import { z } from 'zod';
import { Alert, Loading, useResource } from '../ui';
import { OpsFacts, opsTime } from './OpsOperationDetail';
import { OpsMutationPanel, useOpsMutation } from './OpsMutation';
import { opsError } from './ops-api';
import { useOps } from './OpsShell';

const decimal=z.string().regex(/^(0|[1-9][0-9]{0,18})$/),time=z.string().refine(value=>Number.isFinite(Date.parse(value))),uuid=z.string().uuid();
const editableSchema=z.object({type:z.enum(['SCRATCH_V1','SUMMON_V1']),prize_table_version:z.string(),prizes:z.array(z.object({tier:z.string(),multiplier:decimal,weight:decimal})).min(1).max(32)});
const configSchema=z.object({config_version_id:uuid,version_number:decimal,status:z.enum(['DRAFT','VALIDATED','PREVIEWED','ACTIVE','SUPERSEDED']),config_schema_version:z.string(),ruleset_version:z.string(),algorithm_version:z.string(),config_hash:z.string().regex(/^[0-9a-f]{64}$/),created_at:time,validated_at:time.nullish(),previewed_at:time.nullish(),activated_at:time.nullish(),editable_config:editableSchema.optional()});
const gameSchema=z.object({game_slug:z.enum(['dice','scratch','summon','slot','blackjack','poker']),title:z.string(),sort_order:decimal,version:decimal,publication_state:z.enum(['DRAFT','PUBLISHED','COMING_SOON','RETIRED']),configured_runtime_state:z.enum(['AVAILABLE','MAINTENANCE','UNAVAILABLE']),implementation_key:z.string(),active_config:configSchema.nullish(),rounds_24h:decimal,needs_review_rounds:decimal});
const overviewSchema=z.object({generated_at:time,games:z.array(gameSchema).max(20)});
const detailSchema=z.object({generated_at:time,game:gameSchema,config_versions:z.array(configSchema).max(100),validation_artifacts:z.array(z.record(z.string(),z.json())).max(100),baseline_locked:z.literal(true)});
const labels:Record<string,string>={DRAFT:'草稿',PUBLISHED:'已发布',COMING_SOON:'即将开放',RETIRED:'已退役',AVAILABLE:'可用',MAINTENANCE:'维护中',UNAVAILABLE:'不可用',VALIDATED:'已验证',PREVIEWED:'已预览',ACTIVE:'当前生效',SUPERSEDED:'历史版本'};
export function OpsGames(){
 const {client,bootstrap}=useOps(),mutation=useOpsMutation();const [slug,setSlug]=useState(''),[selectedConfig,setSelectedConfig]=useState(''),[error,setError]=useState('');
 const epoch=bootstrap.principal.authz_epoch,blocked=!!mutation.pending||mutation.busy;
 const overview=useResource(async()=>{try{return overviewSchema.parse(await client.request(`/api/v1/ops/games?authz_epoch=${epoch}`))}catch(error){throw new Error(opsError(error))}},[client,epoch]);
 const detail=useResource(async()=>{if(!slug)return null;try{const value=detailSchema.parse(await client.request(`/api/v1/ops/games/${slug}?authz_epoch=${epoch}`));if(value.game.game_slug!==slug)throw new Error('游戏编号不一致。');return value}catch(error){throw new Error(opsError(error))}},[client,epoch,slug]);
 const game=detail.data?.game,config=detail.data?.config_versions.find(item=>item.config_version_id===selectedConfig);
 const can=(type:string)=>bootstrap.operations.some(item=>item.operation_type===type&&item.available&&bootstrap.principal.permissions.includes(item.required_permission));
 useEffect(()=>{if(mutation.receipt?.operation.state==='SUCCEEDED'){overview.reload();detail.reload()}},[mutation.receipt?.operation.operation_id,mutation.receipt?.operation.state]);
 function change(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!game)return;const form=new FormData(event.currentTarget),type=String(form.get('operation_type')),reason=String(form.get('reason')||'').trim();let input:Record<string,unknown>;
  if(type==='GAME_METADATA_UPDATE'){const order=String(form.get('sort_order'));if(!/^(0|[1-9][0-9]{0,8})$/.test(order)){setError('展示顺序应为非负整数。');return}input={title:String(form.get('title')).trim(),sort_order:order}}
  else if(type==='GAME_PUBLICATION_SET')input={publication_state:String(form.get('publication_state'))};else input={configured_runtime_state:String(form.get('configured_runtime_state'))};
  setError('');mutation.prepare({operation_type:type,target:{type:'game',id:game.game_slug,expected_version:game.version},input,reason});
 }
 function configAction(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!game||!config)return;const form=new FormData(event.currentTarget),type=String(form.get('operation_type'));mutation.prepare({operation_type:type,target:{type:'game_config',id:config.config_version_id,expected_version:config.version_number},input:{game_slug:game.game_slug},reason:String(form.get('reason')||'').trim()})}
 function saveDraft(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!game||!config?.editable_config||config.status!=='DRAFT')return;const form=new FormData(event.currentTarget);try{const edited=editableSchema.parse({...config.editable_config,prize_table_version:String(form.get('prize_table_version')||'').trim(),prizes:config.editable_config.prizes.map((prize,index)=>({...prize,weight:String(form.get(`weight_${index}`)||'')}))});setError('');mutation.prepare({operation_type:'GAME_CONFIG_DRAFT_SAVE',target:{type:'game_config',id:config.config_version_id,expected_version:config.version_number},input:{game_slug:game.game_slug,config:edited},reason:String(form.get('reason')||'').trim()})}catch{setError('请检查奖池版本与各档整数权重。')}}
 return <><header className="page-heading"><div><p className="eyebrow">OPERATIONS / GAMES</p><h1>游戏管理</h1><p>核对发布状态、运行开关与配置版本；已受理的游戏仍按原配置恢复和结算。</p></div><button onClick={overview.reload} disabled={overview.loading||blocked}>刷新列表</button></header>
 <OpsMutationPanel mutation={mutation}/>{error&&<Alert>{error}</Alert>}
 <section className="panel">{overview.loading?<Loading/>:overview.error?<Alert>{overview.error}</Alert>:overview.data&&<><p className="hint">观察时间：{opsTime(overview.data.generated_at)}</p><div className="table-wrap" role="region" aria-label="游戏运行状态" tabIndex={0}><table><thead><tr><th>游戏</th><th>发布 / 运行</th><th>最近 24 小时</th><th>需要核对</th><th>配置</th></tr></thead><tbody>{overview.data.games.map(item=><tr key={item.game_slug}><td><button disabled={blocked} onClick={()=>{setSlug(item.game_slug);setSelectedConfig('')}}>{item.title}</button><small>{item.game_slug}</small></td><td>{labels[item.publication_state]} / {labels[item.configured_runtime_state]}</td><td>{item.rounds_24h} 局</td><td>{item.needs_review_rounds} 局</td><td>{item.active_config?labels[item.active_config.status]:'未配置'}</td></tr>)}</tbody></table></div>{!overview.data.games.length&&<p>暂无可管理的游戏。</p>}</>}</section>
 {slug&&<section className="panel"><div className="section-heading"><h2>游戏详情</h2><button disabled={detail.loading||blocked} onClick={detail.reload}>刷新详情</button></div>{detail.loading?<Loading/>:detail.error?<Alert>{detail.error}</Alert>:game&&<>
 <h3>{game.title}</h3><OpsFacts value={{game_slug:game.game_slug,version:game.version,implementation_key:game.implementation_key,publication_state:game.publication_state,configured_runtime_state:game.configured_runtime_state}}/>
 <form onSubmit={change} key={game.game_slug+game.version}><fieldset disabled={blocked}><legend>发布与运行设置</legend><label>管理动作<select name="operation_type"><option value="GAME_METADATA_UPDATE" disabled={!can('GAME_METADATA_UPDATE')}>修改展示信息</option><option value="GAME_PUBLICATION_SET" disabled={!can('GAME_PUBLICATION_SET')}>修改发布状态</option><option value="GAME_RUNTIME_SET" disabled={!can('GAME_RUNTIME_SET')}>修改运行开关</option></select></label><label>游戏标题<input name="title" defaultValue={game.title} maxLength={100} required/></label><label>展示顺序<input name="sort_order" defaultValue={game.sort_order} inputMode="numeric" maxLength={9} required/></label><label>发布状态<select name="publication_state" defaultValue={game.publication_state}>{['DRAFT','PUBLISHED','COMING_SOON','RETIRED'].map(value=><option key={value} value={value}>{labels[value]}</option>)}</select></label><label>运行状态<select name="configured_runtime_state" defaultValue={game.configured_runtime_state}>{['AVAILABLE','MAINTENANCE','UNAVAILABLE'].map(value=><option key={value} value={value}>{labels[value]}</option>)}</select></label><label>操作原因<textarea name="reason" maxLength={2048} required/></label><button type="submit">读取操作影响</button></fieldset></form>
 <h3>配置版本</h3><p className="hint">规则基线受锁定保护；新的版本经过验证、预览和独立确认后才可生效。</p><label>选择版本<select value={selectedConfig} onChange={event=>setSelectedConfig(event.target.value)} disabled={blocked}><option value="">请选择</option>{detail.data!.config_versions.map(item=><option key={item.config_version_id} value={item.config_version_id}>{labels[item.status]} · {item.config_version_id}</option>)}</select></label>
 {config&&<><OpsFacts value={config}/><form onSubmit={configAction}><fieldset disabled={blocked}><legend>配置生命周期</legend><label>操作<select name="operation_type"><option value="GAME_CONFIG_CLONE_DRAFT" disabled={!can('GAME_CONFIG_CLONE_DRAFT')}>从此版本建立草稿</option><option value="GAME_CONFIG_VALIDATE" disabled={config.status!=='DRAFT'||!can('GAME_CONFIG_VALIDATE')}>验证草稿</option><option value="GAME_CONFIG_PREVIEW" disabled={config.status!=='VALIDATED'||!can('GAME_CONFIG_PREVIEW')}>生成配置预览</option><option value="GAME_CONFIG_ACTIVATE" disabled={config.status!=='PREVIEWED'||!can('GAME_CONFIG_ACTIVATE')}>激活已预览配置</option></select></label><label>操作原因<textarea name="reason" maxLength={2048} required/></label><button type="submit">读取配置操作影响</button></fieldset></form></>}
 {config?.editable_config&&config.status==='DRAFT'&&<form onSubmit={saveDraft} key={config.config_version_id+config.version_number}><fieldset disabled={blocked||!can('GAME_CONFIG_DRAFT_SAVE')}><legend>编辑奖池草稿</legend><label>奖池版本<input name="prize_table_version" defaultValue={config.editable_config.prize_table_version} maxLength={128} required/></label>{config.editable_config.prizes.map((prize,index)=><label key={prize.tier}>{prize.tier} · 固定倍率 {prize.multiplier}<input name={`weight_${index}`} defaultValue={prize.weight} inputMode="numeric" maxLength={19} required/></label>)}<label>操作原因<textarea name="reason" maxLength={2048} required/></label><button type="submit">预览草稿变更</button></fieldset></form>}
 <details><summary>验证资料</summary><OpsFacts value={detail.data!.validation_artifacts}/></details>
 </>}</section>}</>;
}
