import { useState, type FormEvent } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { Alert, Loading, useResource } from '../ui';
import { canAcknowledgeOpsReview, checkOperationView, opsError, opsID, type OpsOperationView } from './ops-api';
import { useOps } from './OpsShell';
import { OpsOperationList } from './OpsOperationList';
import { clearOpsPending, opsPendingKey } from './ops-pending';

export const opsState:Record<string,string>={CONFIRMED:'已确认',REFUNDED:'已退回',RECOVERING:'恢复中',PREPARED:'待确认',AUTHORIZED:'已授权',EXECUTING:'执行中',SUCCEEDED:'已完成',FAILED:'失败',FAILED_NO_EFFECT:'失败且未生效',NEEDS_REVIEW:'需要核对',PENDING:'处理中',RECONCILING:'正在对账',CANCELLED:'已取消',ACTIVE:'生效中',SCHEDULED:'已预约',COMPLETED:'已结束',DISABLED:'已停用',NOT_CREATED:'尚未创建',ACTIVATION_FAILED:'启用失败',ENDING_FAILED:'结束失败',SUPER_ADMIN:'最高管理员',OPERATOR:'运营人员',AUDITOR:'审计员',DEVELOPMENT:'开发环境',STAGING:'预发布环境',PRODUCTION:'生产环境'};
const factLabels:Record<string,string>={snapshot_id:'快照编号',slice_target_id:'榜单范围',entry_count:'条目数',old_count:'原条目数',new_count:'新条目数',added:'新增条目',removed:'移除条目',changed:'变化条目',old_hash:'原内容摘要',new_hash:'新内容摘要',aggregate_hash:'内容摘要',build_kind:'生成类型',built_at:'生成时间',source_checked_at:'来源检查时间',period_start:'周期开始',period_end:'周期结束',pointer_version:'发布版本',current_pointer_version:'当前发布版本',published:'正在发布',config_version_id:'配置编号',config_hash:'配置摘要',version_number:'配置版本',ruleset_version:'规则版本',algorithm_version:'算法版本',publication_state:'发布状态',configured_runtime_state:'运行设置',requires_attention:'存在需关注事项',remote_receipt_accepted:'远端回执已确认',remote_receipt_state:'远端处理状态',remote_receipt_hash:'远端回执摘要',service_state:'服务读取状态',open_tables:'未关闭牌桌',active_sessions:'活动会话',hands_in_progress:'进行中手牌',needs_review_hands:'待核对手牌',pending_funding:'待处理资金操作',generated_at:'观察时间',blockers:'需关注事项',affected_users:'受影响用户',pending_transfers:'待处理转账',active_direct_play_rounds:'活动游戏回合',active_poker_tables:'活动 Poker 牌桌',active_poker_hands:'活动 Poker 手牌',pending_reward_claims:'待处理奖励',scheduled_ranking_publishes:'预约排行榜发布',scheduled_announcements:'预约公告',critical_notice_id:'独立服务提示编号',announcement_id:'关联公告',delta_units:'变动单位',reference:'关联依据',maintenance_id:'维护编号',state:'状态',status:'状态',reason:'原因',environment:'环境',version:'版本',scopes:'影响范围',scheduled_start_at:'计划开始',scheduled_end_at:'计划结束',estimated_end_at:'预计结束',activated_at:'实际开始',ended_at:'实际结束',operation_id:'操作编号',action:'操作',input:'变更内容',start_at:'开始时间',end_at:'结束时间',newapi_user_id:'账户编号',principal_id:'运营身份编号',base_role:'角色',authz_epoch:'权限版本',permissions:'权限',created_at:'创建时间',updated_at:'更新时间',disabled_at:'停用时间',created_by:'创建者',updated_by:'修改者',disabled_by:'停用者',amount_units:'金额单位',balance_units:'余额单位',transaction_id:'交易编号',transfer_id:'转账编号',claim_id:'奖励编号',table_id:'牌桌编号',game_slug:'游戏',config_version:'配置版本',accepting_players:'接纳新玩家',enabled:'已启用',CHALDEA_USER_WRITES:'平台用户新写入',WALLET_EXCHANGE:'钱包兑换',REWARDS:'奖励领取',DIRECT_PLAY_NEW_ROUNDS:'新游戏回合',POKER_NEW_TABLES_NEW_HANDS:'Poker 新桌与新手牌',RANKINGS_PUBLISHING:'排行榜发布',ANNOUNCEMENTS_SCHEDULING:'公告定时发布'};
export const opsTime=(value:string)=>Number.isFinite(Date.parse(value))?new Date(value).toLocaleString('zh-CN',{hour12:false}):value;
function factValue(value:unknown):string {if(value===null||value===undefined)return '—';if(typeof value==='boolean')return value?'是':'否';if(typeof value==='string')return Object.hasOwn(factLabels,value)?factLabels[value]:Object.hasOwn(opsState,value)?opsState[value]:(/^\d{4}-\d\d-\d\dT/.test(value)?opsTime(value):value);if(typeof value==='number')return String(value);return '';}
export function OpsFacts({value,depth=0}:{value:unknown;depth?:number}){
 if(depth>5)return <span>内容层级较多，请联系支持人员核对。</span>;
 if(Array.isArray(value))return value.length?<ul>{value.map((item,index)=><li key={index}><OpsFacts value={item} depth={depth+1}/></li>)}</ul>:<span>无</span>;
 if(value&&typeof value==='object')return Object.keys(value).length?<dl className="ops-facts">{Object.entries(value).map(([key,child])=><div key={key}><dt>{Object.hasOwn(factLabels,key)?factLabels[key]:key}</dt><dd><OpsFacts value={child} depth={depth+1}/></dd></div>)}</dl>:<span>无</span>;
 return <span>{factValue(value)}</span>;
}
export function OpsReceipt({view}:{view:OpsOperationView}){
 const item=view.operation;
 return <><section className="panel" aria-label="操作回执"><div className="section-heading"><h2>{opsState[item.state]||item.state}</h2><span>{opsState[item.environment]||item.environment}</span></div><dl className="ops-impact"><div><dt>操作编号</dt><dd>{item.operation_id}</dd></div><div><dt>操作类型</dt><dd>{item.operation_type}</dd></div><div><dt>目标</dt><dd>{item.target.id}</dd></div><div><dt>发起账户</dt><dd>{item.actor_newapi_user_id}</dd></div></dl><p>原因：{item.reason||'—'}</p>{item.failure_code&&<Alert>处理原因：{item.failure_code}</Alert>}<p>最后更新：{opsTime(item.updated_at)}</p>{view.audit_id&&<Link to={`/ops/audit/${view.audit_id}`}>查看关联审计 →</Link>}<details><summary>处理结果</summary><OpsFacts value={item.result}/></details></section><section className="panel"><h2>操作时间线</h2>{view.timeline.length?<ol className="ops-timeline">{view.timeline.map(event=><li key={event.event_id}><strong>{opsState[event.state]||event.state}</strong>{event.substate&&<span> · {event.substate}</span>}<time dateTime={event.occurred_at}>{opsTime(event.occurred_at)}</time>{event.failure_code&&<p>{event.failure_code}</p>}</li>)}</ol>:<p>暂无后续事件。</p>}</section></>;
}
export function OpsOperationDetail(){
 const {operationID=''}=useParams();const {client,bootstrap}=useOps();
 const [cancelling,setCancelling]=useState(false),[cancelled,setCancelled]=useState(false),[acknowledged,setAcknowledged]=useState(false),[cancelError,setCancelError]=useState('');
 const resource=useResource(async()=>{if(!opsID(operationID))throw new Error('操作编号无效。');try{return checkOperationView(await client.request<OpsOperationView>(`/api/v1/ops/operations/${operationID}?authz_epoch=${bootstrap.principal.authz_epoch}`));}catch(error){throw new Error(opsError(error));}},[client,operationID,bootstrap.principal.authz_epoch]);
 async function cancel(){if(cancelling)return;setCancelling(true);setCancelError('');try{
  if(!navigator.locks)throw new Error('当前浏览器无法协调管理写入，请使用支持安全锁的浏览器。');
  const key=opsPendingKey(bootstrap.principal.principal_id);
  await navigator.locks.request(key,async()=>{const result=await client.request<{operation:OpsOperationView}>(`/api/v1/ops/operations/${operationID}/cancel`,'POST',{authz_epoch:bootstrap.principal.authz_epoch});const view=checkOperationView(result?.operation);if(view.operation.operation_id!==operationID||view.operation.actor_newapi_user_id!==bootstrap.principal.newapi_user_id)throw new Error('取消结果无法核对。');if(view.operation.state==='CANCELLED'){clearOpsPending(key,operationID);setCancelled(true)}else if(!['SUCCEEDED','FAILED_NO_EFFECT'].includes(view.operation.state))throw new Error('原操作尚未结束，请继续查询。');resource.reload()});
 }catch(error){setCancelError(opsError(error))}finally{setCancelling(false)}}
 async function acknowledge(){if(cancelling)return;setCancelling(true);setCancelError('');try{
  if(!navigator.locks)throw new Error('当前浏览器无法协调管理写入，请使用支持安全锁的浏览器。');
  const key=opsPendingKey(bootstrap.principal.principal_id);
  await navigator.locks.request(key,async()=>{const view=checkOperationView(await client.request<OpsOperationView>(`/api/v1/ops/operations/${operationID}?authz_epoch=${bootstrap.principal.authz_epoch}`));if(view.operation.operation_id!==operationID||view.operation.actor_newapi_user_id!==bootstrap.principal.newapi_user_id||!canAcknowledgeOpsReview(view))throw new Error('尚未确认远端回执和审计，请继续查询原操作。');clearOpsPending(key,operationID);setAcknowledged(true)});
 }catch(error){setCancelError(opsError(error))}finally{setCancelling(false)}}
 return <><header className="page-heading"><div><p className="eyebrow">OPERATIONS / RECEIPT</p><h1>操作详情</h1><Link to="/ops/operations">返回操作查询</Link></div><button onClick={resource.reload} disabled={resource.loading}>查询原操作</button></header>{resource.loading?<Loading/>:resource.error?<Alert>{resource.error}</Alert>:resource.data&&<><OpsReceipt view={resource.data}/>{resource.data.operation.state==='PREPARED'&&resource.data.operation.actor_newapi_user_id===bootstrap.principal.newapi_user_id&&<section className="panel"><h2>取消未执行的操作</h2><p>离开编辑页面后，可在这里取消尚未执行的原操作。服务器会重新核对状态；已经执行的操作会保留实际回执。</p><button disabled={cancelling||cancelled} onClick={()=>{void cancel()}}>取消本次操作</button>{cancelled&&<p role="status">原操作已取消，可返回业务页面重新编辑；预览和时间线仍保留。</p>}{cancelError&&<Alert>{cancelError}</Alert>}</section>}{canAcknowledgeOpsReview(resource.data)&&resource.data.operation.actor_newapi_user_id===bootstrap.principal.newapi_user_id&&<section className="panel"><h2>继续人工核对</h2><p>远端回执与审计已确认，业务仍需恢复或人工处理。确认后保留本次待核对记录，并解除当前浏览器的操作等待。</p><button disabled={cancelling||acknowledged} onClick={()=>{void acknowledge()}}>保留待核对记录并关闭回执</button>{acknowledged&&<p role="status">待核对记录已保留，可进入业务页面继续处理。</p>}{cancelError&&<Alert>{cancelError}</Alert>}</section>}</>}</>;
}
export function OpsOperationLookup(){
 const [id,setID]=useState(''),[error,setError]=useState('');const navigate=useNavigate();
 function submit(event:FormEvent){event.preventDefault();if(!opsID(id.trim())){setError('请输入完整的操作编号。');return}navigate(`/ops/operations/${id.trim()}`);}
 return <><header className="page-heading"><div><p className="eyebrow">OPERATIONS / RECORDS</p><h1>操作记录</h1><p>按原操作编号查询当前状态、时间线和审计回执。</p></div></header><section className="panel"><form onSubmit={submit} className="filters"><label>操作编号<input value={id} onChange={event=>setID(event.target.value)} maxLength={36} required autoComplete="off"/></label><button type="submit">查询操作</button></form>{error&&<Alert>{error}</Alert>}<p className="hint">请求结果不确定时，请先查询原操作，避免重复发起业务变更。</p></section><OpsOperationList/></>;
}


