import { useState, type FormEvent } from 'react';
import { Link } from 'react-router-dom';
import { Alert, Loading, useResource } from '../ui';
import { checkOperation, opsError, opsID, opsVersion, type OpsOperation } from './ops-api';
import { opsState, opsTime } from './OpsOperationDetail';
import { useOps } from './OpsShell';

export function OpsOperationList(){
 const {client,bootstrap}=useOps();const [state,setState]=useState(''),[type,setType]=useState(''),[actorInput,setActorInput]=useState(''),[actor,setActor]=useState(''),[cursor,setCursor]=useState(''),[error,setError]=useState('');
 const resource=useResource(async()=>{try{const page=await client.request<{items:OpsOperation[];next_before?:string;next_before_id?:string}>(`/api/v1/ops/operations?authz_epoch=${bootstrap.principal.authz_epoch}&limit=50${state?'&state='+state:''}${type?'&operation_type='+encodeURIComponent(type):''}${actor?'&actor_newapi_user_id='+actor:''}${cursor}`);if(!page||!Array.isArray(page.items)||!!page.next_before!==!!page.next_before_id||page.next_before&&(!Number.isFinite(Date.parse(page.next_before))||!opsID(page.next_before_id)))throw new Error('操作列表响应无法核对。');page.items.forEach(checkOperation);return page}catch(error){throw new Error(opsError(error))}},[client,bootstrap.principal.authz_epoch,state,type,actor,cursor]);
 function filter(event:FormEvent){event.preventDefault();if(actorInput.trim()&&!opsVersion(actorInput.trim())){setError('发起账户编号无效。');return}setError('');setActor(actorInput.trim());setCursor('');resource.reload()}
 return <section className="panel ops-system-list ops-system-operation-list"><div className="section-heading"><h2>近期操作</h2><button onClick={()=>{setCursor('');resource.reload()}} disabled={resource.loading}>最新记录</button></div><form className="filters" onSubmit={filter}><label>状态<select value={state} onChange={event=>{setState(event.target.value);setCursor('')}}><option value="">全部状态</option>{['PREPARED','AUTHORIZED','EXECUTING','SUCCEEDED','FAILED','FAILED_NO_EFFECT','NEEDS_REVIEW','CANCELLED'].map(value=><option value={value} key={value}>{opsState[value]||value}</option>)}</select></label><label>操作类型<select value={type} onChange={event=>{setType(event.target.value);setCursor('')}}><option value="">全部类型</option>{bootstrap.operations.map(item=><option key={item.operation_type} value={item.operation_type}>{item.operation_type}</option>)}</select></label><label>发起账户<input value={actorInput} onChange={event=>setActorInput(event.target.value)} maxLength={19} inputMode="numeric" placeholder="全部账户"/></label><button type="submit">筛选</button></form>{error&&<Alert>{error}</Alert>}{resource.loading?<Loading/>:resource.error?<Alert>{resource.error}</Alert>:resource.data&&<><div className="table-wrap" role="region" aria-label="近期操作" tabIndex={0}><table><thead><tr><th>时间 / 操作</th><th>状态</th><th>发起账户</th><th>目标</th><th>原因</th></tr></thead><tbody>{resource.data.items.map(item=><tr key={item.operation_id}><td>{opsTime(item.created_at)}<small><Link to={`/ops/operations/${item.operation_id}`}>{item.operation_type}</Link></small></td><td>{opsState[item.state]||item.state}</td><td>{item.actor_newapi_user_id}</td><td>{item.target.type}<small>{item.target.id}</small></td><td>{item.reason}</td></tr>)}</tbody></table></div>{!resource.data.items.length&&<p>暂无当前权限范围内的匹配操作。</p>}{resource.data.next_before&&<button className="ops-system-more" onClick={()=>setCursor(`&before=${encodeURIComponent(resource.data!.next_before!)}&before_id=${resource.data!.next_before_id}`)}>更早记录</button>}</>}</section>;
}
