import { useEffect, useState, type FormEvent } from 'react';
import { z } from 'zod';
import { Alert, Loading, useResource } from '../ui';
import { OpsFacts, opsTime } from './OpsOperationDetail';
import { OpsMutationPanel, useOpsMutation } from './OpsMutation';
import { canAcknowledgeOpsReview, opsError, opsID, opsVersion } from './ops-api';
import { useOps } from './OpsShell';
import './ops-business.css';

const decimal=z.string().regex(/^(0|[1-9][0-9]{0,18})$/),uuid=z.string().uuid(),time=z.string().refine(value=>Number.isFinite(Date.parse(value)));
const overviewSchema=z.object({generated_at:time,service_state:z.string(),requires_attention:z.boolean(),blockers:z.array(z.string()),open_tables:decimal,active_sessions:decimal,hands_in_progress:decimal,needs_review_hands:decimal,pending_funding:decimal,oldest_pending_funding_at:time.nullish()});
const tableSchema=z.object({table_id:uuid,owner_user_id:decimal,name:z.string(),access_mode:z.string(),max_seats:z.number().int().min(2).max(9),occupied_seats:decimal,spectator_count:decimal,chat_enabled:z.boolean(),lifecycle_state:z.string(),accepting_players:z.boolean(),allow_new_hands:z.boolean(),table_version:decimal,runtime_epoch:decimal,current_hand_id:uuid.nullish(),needs_review:z.boolean(),recovery_state:z.string().nullish(),created_at:time,updated_at:time});
const playerSchema=z.object({session_id:uuid,user_id:decimal,seat_no:z.number().int().min(1).max(9),display_name:z.string(),state:z.string(),stack_units:decimal,connected:z.boolean(),leave_after_hand:z.boolean()});
const messageSchema=z.object({message_id:uuid,sequence:decimal,kind:z.string(),body:z.string(),created_at:time,author:z.object({user_id:decimal,member_id:z.string(),display_name:z.string()}).nullish(),moderation_state:z.enum(['VISIBLE','HIDDEN'])});
const detailSchema=z.object({generated_at:time,table:tableSchema,players:z.array(playerSchema).max(12),messages:z.array(messageSchema).max(100),recent_events:z.array(z.record(z.string(),z.json())).max(100)});
const sessionSchema=z.object({session_id:uuid,table_id:uuid,user_id:decimal,seat_no:z.number().int().min(1).max(9),display_name:z.string(),state:z.string(),initial_buyin_units:decimal,total_topup_units:decimal,current_stack_units:decimal,final_cashout_units:decimal.nullish(),realized_pl_units:z.string().regex(/^-?(0|[1-9][0-9]{0,18})$/).nullish(),control_epoch:decimal,started_at:time,ended_at:time.nullish(),end_reason:z.string().nullish()});
const handSchema=z.object({hand_id:uuid,table_id:uuid,hand_no:decimal,state:z.string(),hand_version:decimal,event_sequence:decimal,public_board_count:decimal,participant_count:decimal,total_pot_units:decimal,created_at:time,settled_at:time.nullish(),recovery_state:z.string().nullish()});
const pageSchema=<T extends z.ZodType>(item:T)=>z.object({generated_at:time,items:z.array(item).max(100),next_cursor:z.string().nullish()});
const commands=[['POKER_ACCEPTING_PLAYERS_SET','入座开关'],['POKER_NEW_HANDS_SET','新手牌开关'],['POKER_CLOSE_AFTER_HAND','本手结束后关桌'],['POKER_REMOVE_PLAYER_AFTER_HAND','本手结束后移出玩家'],['POKER_REMOVE_SPECTATOR','移出观众'],['POKER_CHAT_MUTE_SET','聊天禁言设置'],['POKER_TABLE_PAUSE','暂停牌桌'],['POKER_TABLE_RESUME','恢复牌桌'],['POKER_RECOVERY_REQUEST','提交恢复处理'],['POKER_EMERGENCY_PAUSE','紧急暂停']] as const;
export function OpsPoker(){
 const {client,bootstrap}=useOps(),mutation=useOpsMutation();const [table,setTable]=useState(''),[tableCursor,setTableCursor]=useState(''),[sessionCursor,setSessionCursor]=useState(''),[selection,setSelection]=useState<{kind:'sessions'|'hands';id:string}>(),[command,setCommand]=useState<string>(commands[0][0]),[error,setError]=useState('');
 const epoch=bootstrap.principal.authz_epoch,blocked=!!mutation.pending||mutation.busy;
 const can=(type:string)=>bootstrap.operations.some(item=>item.operation_type===type&&item.available&&bootstrap.principal.permissions.includes(item.required_permission));
 const overview=useResource(async()=>{try{return overviewSchema.parse(await client.request(`/api/v1/ops/poker?authz_epoch=${epoch}`))}catch(error){throw new Error(opsError(error))}},[client,epoch]);
 const tables=useResource(async()=>{try{return pageSchema(tableSchema).parse(await client.request(`/api/v1/ops/poker/tables?authz_epoch=${epoch}&limit=50${tableCursor?'&cursor='+encodeURIComponent(tableCursor):''}`))}catch(error){throw new Error(opsError(error))}},[client,epoch,tableCursor]);
 const sessions=useResource(async()=>{try{return pageSchema(sessionSchema).parse(await client.request(`/api/v1/ops/poker/sessions?authz_epoch=${epoch}&limit=50${sessionCursor?'&cursor='+encodeURIComponent(sessionCursor):''}`))}catch(error){throw new Error(opsError(error))}},[client,epoch,sessionCursor]);
 const detail=useResource(async()=>{if(!table)return null;try{const value=detailSchema.parse(await client.request(`/api/v1/ops/poker/tables/${table}?authz_epoch=${epoch}`));if(value.table.table_id!==table)throw new Error('牌桌编号不一致。');return value}catch(error){throw new Error(opsError(error))}},[client,epoch,table]);
 useEffect(()=>{if(mutation.receipt?.operation.state==='SUCCEEDED'||canAcknowledgeOpsReview(mutation.receipt)){overview.reload();tables.reload();sessions.reload();detail.reload()}},[mutation.receipt?.operation.operation_id,mutation.receipt?.operation.state]);
 function prepare(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!detail.data)return;const form=new FormData(event.currentTarget),targetUser=String(form.get('target_user_id')||''),targetSession=String(form.get('target_session_id')||'');let input:Record<string,unknown>={};
  if(['POKER_REMOVE_PLAYER_AFTER_HAND','POKER_REMOVE_SPECTATOR','POKER_CHAT_MUTE_SET'].includes(command)&&!opsVersion(targetUser)){setError('请输入目标账户编号。');return}
  if(command==='POKER_REMOVE_PLAYER_AFTER_HAND'&&!opsID(targetSession)){setError('请选择该玩家的会话编号。');return}
  switch(command){case 'POKER_ACCEPTING_PLAYERS_SET':input={accepting:form.get('enabled')==='true'};break;case 'POKER_NEW_HANDS_SET':input={allow_new_hands:form.get('enabled')==='true'};break;case 'POKER_REMOVE_PLAYER_AFTER_HAND':input={target_user_id:targetUser,target_session_id:targetSession};break;case 'POKER_REMOVE_SPECTATOR':input={target_user_id:targetUser};break;case 'POKER_CHAT_MUTE_SET':input={target_user_id:targetUser,muted:form.get('enabled')==='true'};break;case 'POKER_RECOVERY_REQUEST':input={recovery_action:String(form.get('recovery_action'))};break}
  setError('');mutation.prepare({operation_type:command,target:{type:'poker_table',id:table,expected_version:detail.data.table.table_version},input,reason:String(form.get('reason')||'').trim()});
 }
 function moderate(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!detail.data)return;const form=new FormData(event.currentTarget),id=String(form.get('message_id')||'');const message=detail.data.messages.find(item=>item.message_id===id);if(!message){setError('请选择本桌当前读取的消息。');return}setError('');mutation.prepare({operation_type:'POKER_CHAT_VISIBILITY_SET',target:{type:'poker_message',id,expected_version:detail.data.table.table_version},input:{table_id:table,hidden:form.get('hidden')==='true'},reason:String(form.get('reason')||'').trim()});}
 return <><header className="page-heading"><div><p className="eyebrow">OPERATIONS / POKER</p><h1>Poker 管理</h1><p>核对牌桌、资金处理和恢复状态；管理操作由 Poker 服务执行并返回原操作回执。</p></div><button onClick={()=>{overview.reload();tables.reload();sessions.reload()}} disabled={blocked||overview.loading}>刷新状态</button></header><OpsMutationPanel mutation={mutation}/>{error&&<Alert>{error}</Alert>}
 <section className="panel ops-business-service"><h2>服务概况</h2>{overview.loading?<Loading/>:overview.error?<Alert>{overview.error}</Alert>:overview.data&&<><OpsFacts value={overview.data}/>{overview.data.blockers.length>0&&<Alert><ul>{overview.data.blockers.map(item=><li key={item}>{item}</li>)}</ul></Alert>}</>}</section>
 <section className="panel ops-business-list"><div className="section-heading"><h2>牌桌</h2><span className="ops-business-section-note">选择牌桌读取详情与管理动作</span></div>{tables.loading?<Loading/>:tables.error?<Alert>{tables.error}</Alert>:tables.data&&<><div className="table-wrap" role="region" aria-label="Poker 牌桌列表" tabIndex={0}><table><thead><tr><th>牌桌</th><th>状态</th><th>玩家 / 观众</th><th>入座 / 新手牌</th><th>恢复</th></tr></thead><tbody>{tables.data.items.map(item=><tr key={item.table_id}><td><button disabled={blocked} onClick={()=>setTable(item.table_id)}>{item.name}</button><small>{item.table_id}</small></td><td>{item.lifecycle_state}</td><td>{item.occupied_seats} / {item.max_seats} · 观众 {item.spectator_count}</td><td>{item.accepting_players?'开放':'关闭'} / {item.allow_new_hands?'允许':'暂停'}</td><td>{item.needs_review?'需要核对':item.recovery_state||'—'}</td></tr>)}</tbody></table></div>{!tables.data.items.length&&<p>暂无符合条件的牌桌。</p>}<div className="ops-actions"><button disabled={!tableCursor||blocked} onClick={()=>setTableCursor('')}>第一页</button><button disabled={!tables.data.next_cursor||blocked} onClick={()=>setTableCursor(tables.data!.next_cursor!)}>下一页</button></div></>}</section>
 {table&&<section className="panel ops-business-detail"><div className="section-heading"><h2>牌桌详情</h2><button disabled={blocked||detail.loading} onClick={detail.reload}>刷新本桌</button></div>{detail.loading?<Loading/>:detail.error?<Alert>{detail.error}</Alert>:detail.data&&<><div className="ops-business-poker-top"><div className="ops-business-poker-identity"><OpsFacts value={detail.data.table}/>{detail.data.table.current_hand_id&&<button onClick={()=>setSelection({kind:'hands',id:detail.data!.table.current_hand_id!})}>读取当前手牌状态</button>}<h3>玩家</h3>{detail.data.players.map(player=><article className="ops-entry" key={player.session_id}><button onClick={()=>setSelection({kind:'sessions',id:player.session_id})}>{player.display_name} · 座位 {player.seat_no}</button><p>账户 {player.user_id} · {player.connected?'已连接':'断线'} · {player.leave_after_hand?'已申请安全离桌':player.state}</p><small>会话 {player.session_id}</small></article>)}</div>
 <form className="ops-business-poker-controls" onSubmit={prepare}><fieldset disabled={blocked}><legend>牌桌管理</legend><label>操作<select value={command} onChange={event=>setCommand(event.target.value)}>{commands.map(([type,label])=><option key={type} value={type} disabled={!can(type)}>{label}</option>)}</select></label>{['POKER_ACCEPTING_PLAYERS_SET','POKER_NEW_HANDS_SET','POKER_CHAT_MUTE_SET'].includes(command)&&<label>{command==='POKER_CHAT_MUTE_SET'?'禁言状态':'开关'}<select name="enabled"><option value="false">{command==='POKER_CHAT_MUTE_SET'?'解除禁言':'关闭'}</option><option value="true">{command==='POKER_CHAT_MUTE_SET'?'禁言':'开启'}</option></select></label>}{['POKER_REMOVE_PLAYER_AFTER_HAND','POKER_REMOVE_SPECTATOR','POKER_CHAT_MUTE_SET'].includes(command)&&<label>目标账户编号<input name="target_user_id" maxLength={19} inputMode="numeric" required/></label>}{command==='POKER_REMOVE_PLAYER_AFTER_HAND'&&<label>目标玩家会话<select name="target_session_id" required><option value="">请选择</option>{detail.data.players.map(player=><option key={player.session_id} value={player.session_id}>{player.display_name} · {player.user_id} · {player.session_id}</option>)}</select></label>}{command==='POKER_RECOVERY_REQUEST'&&<label>恢复动作<select name="recovery_action"><option value="RECOVER">请求恢复</option><option value="RESUME">恢复运行</option><option value="SAFE_CLOSE">安全关闭</option><option value="ESCALATE">升级人工核对</option></select></label>}<label>操作原因<textarea name="reason" maxLength={2048} required/></label><button type="submit" disabled={!can(command)}>核对操作影响</button></fieldset></form></div>
 <div className="ops-business-poker-chat-grid"><div><h3>聊天管理</h3><div className="ops-chat-review">{detail.data.messages.map(message=><article key={message.message_id}><p><strong>{message.author?.display_name||'系统'}</strong> · {opsTime(message.created_at)} · {message.moderation_state==='HIDDEN'?'已隐藏':'可见'}</p><p>{message.body}</p><small>{message.message_id}</small></article>)}</div></div><form className="ops-business-chat-controls" onSubmit={moderate}><fieldset disabled={blocked||!can('POKER_CHAT_VISIBILITY_SET')}><legend>消息可见性</legend><label>目标消息<select name="message_id" required><option value="">请选择</option>{detail.data.messages.filter(message=>message.kind!=='SYSTEM').map(message=><option key={message.message_id} value={message.message_id}>{message.author?.display_name||'用户'} · {message.message_id}</option>)}</select></label><label>可见性<select name="hidden"><option value="true">隐藏消息</option><option value="false">恢复可见</option></select></label><label>操作原因<textarea name="reason" maxLength={2048} required/></label><button type="submit">核对消息变更</button></fieldset></form></div><details><summary>近期管理事件</summary><OpsFacts value={detail.data.recent_events}/></details></>}</section>}
 <section className="panel ops-business-sessions"><h2>玩家会话</h2>{sessions.loading?<Loading/>:sessions.error?<Alert>{sessions.error}</Alert>:sessions.data&&<><div className="table-wrap"><table><thead><tr><th>玩家</th><th>会话</th><th>状态</th><th>开始时间</th></tr></thead><tbody>{sessions.data.items.map(item=><tr key={item.session_id}><td>{item.display_name}<small>{item.user_id}</small></td><td><button onClick={()=>setSelection({kind:'sessions',id:item.session_id})}>{item.session_id}</button></td><td>{item.state}</td><td>{opsTime(item.started_at)}</td></tr>)}</tbody></table></div>{!sessions.data.items.length&&<p>暂无会话。</p>}<div className="ops-actions"><button disabled={!sessionCursor||blocked} onClick={()=>setSessionCursor('')}>第一页</button><button disabled={!sessions.data.next_cursor||blocked} onClick={()=>setSessionCursor(sessions.data!.next_cursor!)}>下一页</button></div></>}</section>
 {selection&&<OpsPokerRecord key={selection.kind+selection.id} selection={selection}/>}</>;
}
function OpsPokerRecord({selection}:{selection:{kind:'sessions'|'hands';id:string}}){const {client,bootstrap}=useOps();const resource=useResource(async()=>{try{const raw=await client.request(`/api/v1/ops/poker/${selection.kind}/${selection.id}?authz_epoch=${bootstrap.principal.authz_epoch}`);const value=selection.kind==='sessions'?sessionSchema.parse(raw):handSchema.parse(raw);const id='session_id' in value?value.session_id:value.hand_id;if(id!==selection.id)throw new Error('记录编号不一致。');return value}catch(error){throw new Error(opsError(error))}},[client,bootstrap.principal.authz_epoch,selection.kind,selection.id]);return <section className="panel ops-business-record-detail"><h2>{selection.kind==='sessions'?'会话详情':'手牌运行状态'}</h2>{resource.loading?<Loading/>:resource.error?<Alert>{resource.error}</Alert>:resource.data&&<OpsFacts value={resource.data}/>}</section>}
