import { useState, type FormEvent } from 'react';
import { useLocation } from 'react-router-dom';
import { z } from 'zod';
import { Alert, Loading, useResource } from '../ui';
import { chips } from '../games-api';
import { handSchema, pageSchema, recordTypes, results, roundSchema, sessionSchema, statuses, transactionSchema } from '../history/api';
import { opsError, opsID, opsVersion } from './ops-api';
import { OpsFacts, opsTime } from './OpsOperationDetail';
import { useOps } from './OpsShell';
import '../history/history.css';

type Selection={kind:'rounds'|'sessions'|'hands'|'transactions';id:string};
const kinds:Record<string,Selection['kind']>={DIRECT_PLAY_ROUND:'rounds',POKER_SESSION:'sessions',POKER_HAND:'hands'};
const names:Record<string,string>={DIRECT_PLAY_ROUND:'单局游戏',POKER_SESSION:'Poker 会话',POKER_HAND:'Poker 手牌',WIN:'净赢',LOSS:'净输',BREAK_EVEN:'回本',CANCELLED:'已取消',REFUNDED:'已退回',PROCESSING:'处理中',SETTLED:'已结算',RECOVERING:'恢复中'};
const amount=(value:string|null|undefined)=>value==null?'—':chips(value,true);
export function OpsRecords(){
 const {client,bootstrap}=useOps(),location=useLocation();const supplied=new URLSearchParams(location.search).get('subject_newapi_user_id')||'';
 const [subjectInput,setSubjectInput]=useState(opsVersion(supplied)?supplied:''),[subject,setSubject]=useState(opsVersion(supplied)?supplied:''),[query,setQuery]=useState(''),[cursor,setCursor]=useState(''),[selected,setSelected]=useState<Selection>(),[error,setError]=useState('');
 const epoch=bootstrap.principal.authz_epoch;
 const resource=useResource(async()=>{if(!subject)return null;try{const response=await client.request<{subject_newapi_user_id:string}>(`/api/v1/ops/records?authz_epoch=${epoch}&subject_newapi_user_id=${subject}&limit=50${query}${cursor?'&cursor='+encodeURIComponent(cursor):''}`);if(response?.subject_newapi_user_id!==subject)throw new Error('记录所属账户无法核对。');return pageSchema.parse(response)}catch(error){throw new Error(opsError(error))}},[client,epoch,subject,query,cursor]);
 function filter(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!opsVersion(subjectInput)){setError('请先填写要查询的账户编号。');return}const values=new FormData(event.currentTarget),params=new URLSearchParams();for(const [key,value] of values){if(typeof value!=='string'||!value)continue;if(key==='time_from'||key==='time_to'){const time=Date.parse(value);if(!Number.isFinite(time)){setError('时间范围无效。');return}params.set(key,new Date(time).toISOString())}else params.set(key,value.trim())}if(params.has('id')&&!opsID(params.get('id'))||params.has('time_from')&&params.has('time_to')&&Date.parse(params.get('time_from')!)>=Date.parse(params.get('time_to')!)){setError('请检查记录编号和时间范围。');return}setError('');setSubject(subjectInput);setSelected(undefined);setCursor('');setQuery(params.size?'&'+params:'');resource.reload()}
 return <><header className="page-heading"><div><p className="eyebrow">OPERATIONS / RECORDS</p><h1>业务记录查询</h1><p>按指定账户读取记录；每次读取均经过权限检查并记录访问审计。</p></div></header><section className="panel"><form className="filters" onSubmit={filter}><label>目标账户编号<input value={subjectInput} onChange={event=>setSubjectInput(event.target.value)} maxLength={19} inputMode="numeric" required/></label><label>记录类型<select name="record_type"><option value="">全部单局与会话</option>{recordTypes.map(value=><option key={value} value={value}>{names[value]}</option>)}</select></label><label>模式<select name="mode"><option value="">全部模式</option><option value="DIRECT_PLAY">直接游玩</option><option value="POKER">Poker</option></select></label><label>游戏<select name="game_slug"><option value="">全部游戏</option>{resource.data?.game_options.map(item=><option value={item.game_slug} key={item.game_slug}>{item.game_title}{item.retired?'（已退役）':''}</option>)}</select></label><label>开始时间<input type="datetime-local" name="time_from"/></label><label>结束时间（不含）<input type="datetime-local" name="time_to"/></label><label>结果<select name="result"><option value="">全部结果</option>{results.map(value=><option key={value} value={value}>{names[value]||value}</option>)}</select></label><label>状态<select name="status"><option value="">全部状态</option>{statuses.map(value=><option key={value} value={value}>{names[value]||value}</option>)}</select></label><label>精确记录编号<input name="id" maxLength={36}/></label><button type="submit">查询业务记录</button></form>{error&&<Alert>{error}</Alert>}{subject&&(resource.loading?<Loading/>:resource.error?<Alert>{resource.error}</Alert>:resource.data&&<><p className="hint">当前查询账户：{subject}。时间筛选使用当前设备时区。</p><div className="history-records">{resource.data.items.map(item=><article className="history-record" key={item.record_type+item.source_id}><div><small>{names[item.record_type]} · {opsTime(item.occurred_at)}</small><h3>{item.snapshot.game_title}</h3><p>{item.snapshot.table_name||''} · {names[item.status]||item.status}</p><small>当时昵称：{item.snapshot.actor_display_name||'未记录'}</small></div><dl className="ops-impact"><div><dt>投入</dt><dd>{amount(item.record_type==='POKER_SESSION'?item.initial_buyin_units:item.stake_units)}</dd></div><div><dt>返回</dt><dd>{amount(item.record_type==='POKER_SESSION'?item.final_cashout_units:item.payout_units)}</dd></div><div><dt>净变化</dt><dd>{amount(item.net_change_units)}</dd></div></dl><button onClick={()=>setSelected({kind:kinds[item.record_type],id:item.source_id})}>读取详情</button><small>{item.source_id}</small></article>)}</div>{!resource.data.items.length&&<p>该账户暂无符合条件的记录。</p>}<div className="ops-actions"><button disabled={!cursor} onClick={()=>setCursor('')}>返回第一页</button><button disabled={!resource.data.has_more||!resource.data.next_cursor} onClick={()=>setCursor(resource.data!.next_cursor!)}>下一页</button></div></>)}</section>{subject&&selected&&<OpsRecordDetail key={subject+selected.kind+selected.id} subject={subject} selection={selected} select={setSelected}/>}</>;
}
function OpsRecordDetail({subject,selection,select}:{subject:string;selection:Selection;select:(item:Selection)=>void}){
 const {client,bootstrap}=useOps();const [cursor,setCursor]=useState(''),[funding,setFunding]=useState(''),[hands,setHands]=useState(''),[proof,setProof]=useState(false);
 const epoch=bootstrap.principal.authz_epoch,base=`/api/v1/ops/records/${selection.kind}/${selection.id}`,identity=`authz_epoch=${epoch}&subject_newapi_user_id=${subject}`;
 const resource=useResource(async()=>{try{const suffix=selection.kind==='sessions'?`&funding_limit=50&hand_limit=50${funding?'&funding_cursor='+encodeURIComponent(funding):''}${hands?'&hand_cursor='+encodeURIComponent(hands):''}`:selection.kind==='hands'?`&limit=100${cursor?'&cursor='+encodeURIComponent(cursor):''}`:'';const value=await client.request<{subject_newapi_user_id:string;record_type:string;record:unknown}>(`${base}?${identity}${suffix}`);if(value?.subject_newapi_user_id!==subject)throw new Error('记录账户不一致。');const schema=selection.kind==='rounds'?roundSchema:selection.kind==='sessions'?sessionSchema:selection.kind==='hands'?handSchema:transactionSchema;const record=schema.parse(value.record);const actual='session_id' in record&&selection.kind==='sessions'?record.session_id:'hand_id' in record?record.hand_id:'id' in record?record.id:'';if(actual!==selection.id)throw new Error('记录编号不一致。');return record}catch(error){throw new Error(opsError(error))}},[client,base,identity,selection.kind,selection.id,cursor,funding,hands]);
 const verify=useResource(async()=>{if(!proof)return null;try{const value=await client.request<{subject_newapi_user_id:string;record:unknown}>(`${base}/verify?${identity}`);if(value?.subject_newapi_user_id!==subject)throw new Error('验证记录账户不一致。');return z.record(z.string(),z.json()).parse(value.record)}catch(error){throw new Error(opsError(error))}},[client,base,identity,proof]);
 const data=resource.data;
 return <section className="panel"><div className="section-heading"><h2>记录详情 · {selection.id}</h2><button onClick={resource.reload} disabled={resource.loading}>刷新原记录</button></div>{resource.loading?<Loading/>:resource.error?<Alert>{resource.error}</Alert>:data&&<><OpsFacts value={data}/><div className="ops-actions">{'transactions' in data&&data.transactions.map(item=><button key={item.id} onClick={()=>select({kind:'transactions',id:item.id})}>交易 {item.id}</button>)}{'hands' in data&&data.hands.map(item=><button key={item.hand_id} onClick={()=>select({kind:'hands',id:item.hand_id})}>第 {item.hand_no} 手牌</button>)}{'links' in data&&data.links.map(item=><button key={item.source_id} onClick={()=>select({kind:kinds[item.record_type],id:item.source_id})}>关联{names[item.record_type]}</button>)}{'next_funding_cursor' in data&&data.next_funding_cursor&&<button onClick={()=>setFunding(data.next_funding_cursor!)}>下一页资金操作</button>}{'next_hand_cursor' in data&&data.next_hand_cursor&&<button onClick={()=>setHands(data.next_hand_cursor!)}>下一页手牌</button>}{'next_cursor' in data&&data.next_cursor&&<button onClick={()=>setCursor(data.next_cursor!)}>下一页行动</button>}</div>{['rounds','hands'].includes(selection.kind)&&<><button onClick={()=>setProof(value=>!value)}>{proof?'收起公平性材料':'读取获授权的公平性材料'}</button>{proof&&(verify.loading?<Loading/>:verify.error?<Alert>{verify.error}</Alert>:verify.data&&<OpsFacts value={verify.data}/>)}</>}</>}</section>;
}
