import { Link } from 'react-router-dom';
import './ops-system.css';
import { Alert, Empty, Loading, useResource } from '../ui';
import { opsError } from './ops-api';
import { useOps } from './OpsShell';

type Job={kind:string;pending_count:string;attention_count:string;due_count:string;oldest_due_at:string|null};
type Health={ready:boolean;checked_at:string;components:{name:string;state:'READY'|'UNAVAILABLE'}[];stale?:boolean;stale_after?:string};
const jobNames:Record<string,string>={ANNOUNCEMENTS:'公告定时发布与到期',GAME_ROUNDS:'游戏回合恢复',REGISTRATION_GRANTS:'注册奖励',KEY_PURPOSE_SYNC:'密钥用途同步',QUOTA_TRANSFERS:'额度转账',MAINTENANCE:'维护窗口',OPS_REMOTE:'Poker 运营操作',RANKING_REBUILDS:'排行榜影子重建'};
const componentNames:Record<string,string>={web:'页面资源',native:'Native 服务',session_database:'会话数据库',session_cache:'会话缓存',platform_database:'平台数据库',history_reader:'历史记录查询',history_worker_database:'历史归档数据库',history_poker_reader:'Poker 历史来源',request_attribution:'请求归因同步',maintenance_worker:'维护执行器',ops_remote_worker:'远程运营执行器',poker_process:'Poker 进程',poker_database:'Poker 数据库',poker_auth_database:'Poker 身份只读库',poker_cache:'Poker 票据缓存'};
const count=(value:unknown):value is string=>typeof value==='string'&&/^(0|[1-9][0-9]{0,18})$/.test(value);
function checkJobs(value:{items:Job[]}){if(!value||!Array.isArray(value.items)||value.items.some(item=>!item||!Object.hasOwn(jobNames,item.kind)||!count(item.pending_count)||!count(item.attention_count)||!count(item.due_count)||item.oldest_due_at!==null&&!Number.isFinite(Date.parse(item.oldest_due_at))))throw new Error('任务状态响应格式异常。');return value.items;}
const when=(value:string|null)=>value?new Date(value).toLocaleString('zh-CN',{hour12:false}):'—';
export function OpsAttention(){
 const {client}=useOps();const resource=useResource(()=>client.request<{items:Job[]}>('/api/v1/ops/attention').then(checkJobs).catch(error=>{throw new Error(opsError(error));}),[client]);
 const destinations:Record<string,string>={ANNOUNCEMENTS:'/ops/announcements',GAME_ROUNDS:'/ops/games',REGISTRATION_GRANTS:'/ops/rewards',KEY_PURPOSE_SYNC:'/ops/economy',QUOTA_TRANSFERS:'/ops/economy',MAINTENANCE:'/ops/maintenance',OPS_REMOTE:'/ops/operations',RANKING_REBUILDS:'/ops/rankings'};
 return <><header className="page-heading ops-system-heading"><div><p className="eyebrow">OPERATIONS / ATTENTION</p><h1>待处理事项</h1><p>查看当前授权队列中标记为需要核对的工作。</p></div><button onClick={resource.reload} disabled={resource.loading}>刷新事项</button></header>{resource.loading?<Loading/>:resource.error?<Alert>{resource.error}</Alert>:resource.data?.length?<div className="ops-entry-grid ops-system-cards">{resource.data.map(item=><section className="panel ops-system-card" key={item.kind}><h2>{jobNames[item.kind]}</h2><p><strong>{item.attention_count}</strong> 项需要核对</p><Link to={destinations[item.kind]}>进入业务页面处理 →</Link></section>)}</div>:<Empty title="授权队列暂无待核对事项">可在后台任务与服务健康页继续查看运行状态。</Empty>}</>;
}
export function OpsJobs(){
 const {client}=useOps();const resource=useResource(()=>client.request<{items:Job[]}>('/api/v1/ops/jobs').then(checkJobs).catch(error=>{throw new Error(opsError(error));}),[client]);
 return <><header className="page-heading ops-system-heading"><div><p className="eyebrow">OPERATIONS / JOBS</p><h1>后台任务</h1><p>查看当前队列中的待处理工作与需要人工核对的事项。</p></div><button onClick={resource.reload} disabled={resource.loading}>刷新状态</button></header>{resource.loading?<Loading/>:resource.error?<Alert>{resource.error}</Alert>:resource.data&&<section className="panel ops-system-list"><div className="table-wrap" role="region" aria-label="后台任务状态" tabIndex={0}><table><thead><tr><th>任务</th><th>待处理</th><th>已到执行时间</th><th>待核对</th><th>最早计划时间</th></tr></thead><tbody>{resource.data.map(item=><tr key={item.kind}><th scope="row">{jobNames[item.kind]}</th><td>{item.pending_count}</td><td>{item.due_count}</td><td>{item.attention_count==='0'?'0':<strong className="status-error">{item.attention_count}</strong>}</td><td>{when(item.oldest_due_at)}</td></tr>)}</tbody></table></div><p className="hint">队列数量来自本次查询；空队列不能证明后台执行器正在运行。维护期间，已经受理的结算与恢复工作会继续推进。</p></section>}</>;
}
export function OpsServiceHealth(){
 const {client,bootstrap}=useOps();const resource=useResource(async()=>{try{const response=await client.request<{snapshot:Health;observed_at:string;stale_after:string;stale:boolean}>('/api/v1/ops/service-health');if(!response||typeof response.stale!=='boolean'||!Number.isFinite(Date.parse(response.observed_at))||!Number.isFinite(Date.parse(response.stale_after)))throw new Error('服务快照响应格式异常。');const value={...response.snapshot,stale:response.stale,stale_after:response.stale_after};if(!value||typeof value.ready!=='boolean'||!Number.isFinite(Date.parse(value.checked_at))||!Array.isArray(value.components)||value.components.some(item=>!item||typeof item.name!=='string'||!['READY','UNAVAILABLE'].includes(item.state)))throw new Error('服务状态响应格式异常。');return value;}catch(error){throw new Error(opsError(error));}},[client]);
 return <><header className="page-heading ops-system-heading"><div><p className="eyebrow">OPERATIONS / SERVICE HEALTH</p><h1>服务健康</h1><p>查看后台检查器生成的依赖状态快照。</p></div><button onClick={resource.reload} disabled={resource.loading}>刷新快照</button></header>{resource.loading?<Loading/>:resource.error?<Alert>{resource.error}</Alert>:resource.data&&<section className="panel ops-system-health"><h2 className={"ops-system-health-summary "+(resource.data.stale?"is-unknown":resource.data.ready?"is-ready":"is-unavailable")}>{resource.data.stale?'服务状态快照已过期':resource.data.ready?'已配置依赖检查通过':'存在不可用或尚未配置的依赖'}</h2><p className="ops-system-observed">检查时间：<time dateTime={resource.data.checked_at}>{when(resource.data.checked_at)}</time></p><div className="table-wrap" role="region" aria-label="依赖检查结果" tabIndex={0}><table><thead><tr><th>依赖</th><th>检查结果</th></tr></thead><tbody>{resource.data.components.map(item=><tr key={item.name}><th scope="row">{Object.hasOwn(componentNames,item.name)?componentNames[item.name]:item.name}</th><td><span className={"ops-system-health-result "+(resource.data!.stale?"is-unknown":item.state==="READY"?"is-ready":"is-unavailable")}>{resource.data!.stale?'未知（快照过期）':item.state==='READY'?'可用':'不可用'}</span></td></tr>)}</tbody></table></div><p className="hint">后台每 15 秒检查一次，45 秒未更新的快照显示为未知。此结果只反映对应时点的依赖检查，业务链路与备份恢复仍需各自验收。</p>{(bootstrap.principal.permissions.includes("jobs.read")||bootstrap.principal.permissions.includes("operations.read"))&&<nav className="ops-system-links" aria-label="相关运营页面">{bootstrap.principal.permissions.includes("jobs.read")&&<Link to="/ops/jobs">查看后台任务 →</Link>}{bootstrap.principal.permissions.includes("operations.read")&&<Link to="/ops/operations">查看操作记录 →</Link>}</nav>}</section>}</>;
}

