import { useEffect, useState, type FormEvent } from 'react';
import { Link } from 'react-router-dom';
import { z } from 'zod';
import { Alert, Loading, useResource } from '../ui';
import { OpsFacts, opsTime } from './OpsOperationDetail';
import { OpsMutationPanel, useOpsMutation } from './OpsMutation';
import { opsError } from './ops-api';
import { useOps } from './OpsShell';
import './ops-business.css';

const decimal=z.string().regex(/^(0|[1-9][0-9]{0,18})$/),uuid=z.string().uuid(),time=z.string().refine(value=>Number.isFinite(Date.parse(value))),hash=z.string().regex(/^[0-9a-f]{64}$/);
const domain=z.enum(['GAMES','RP','ASSETS']),period=z.enum(['DAY','WEEK','ALL_TIME','CURRENT']);
const metrics=z.enum(['TOTAL_ASSETS','GAME_PROFIT','BIGGEST_WIN','TOTAL_WAGERED','POKER_PROFIT','RP_CALLS','RP_ERRORS','RP_CREDITS']);
const aggregationSchema=z.object({slice_target_id:z.string().max(256),domain,metric:metrics,period,date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).nullish(),published_pointer_version:decimal,published_snapshot_id:uuid.nullish(),last_source_checked_at:time.nullish(),last_built_at:time.nullish(),lag_seconds:decimal.nullish(),state:z.string(),model_scope:z.enum(['ALL','MODEL']).optional(),model_id:z.string().optional()});
const snapshotSchema=z.object({snapshot_id:uuid,slice_target_id:z.string().max(256),domain,period,period_start:time,period_end:time.nullish(),build_kind:z.string(),source_checked_at:time,built_at:time,entry_count:decimal,aggregate_hash:hash,published:z.boolean(),operation_id:uuid.nullish(),pointer_version:decimal,current_pointer_version:decimal});
const rebuildSchema=z.object({operation_id:uuid,slice_target_id:z.string().max(256),domain,metric:metrics,period,date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),model_scope:z.enum(['ALL','MODEL']),model_id:z.string().optional(),expected_pointer_version:decimal,status:z.enum(['PENDING','RUNNING','SHADOW','PUBLISHED','FAILED']),shadow_snapshot_id:uuid.optional(),attempts:decimal,failure_code:z.string().optional(),created_at:time,updated_at:time});
const overviewSchema=z.object({generated_at:time,aggregation_status:z.array(aggregationSchema).max(200),published:z.array(snapshotSchema).max(200),shadow_rebuilds:z.array(snapshotSchema).max(200),rebuild_jobs:z.array(rebuildSchema).max(100)});
const detailSchema=z.object({snapshot:snapshotSchema,current:snapshotSchema.nullish(),diff:z.object({old_count:decimal,new_count:decimal,added:decimal,removed:decimal,changed:decimal,old_hash:hash.nullish(),new_hash:hash})});
const names:Record<string,string>={GAMES:'游戏',RP:'RP 调用',ASSETS:'资产',DAY:'日榜',WEEK:'周榜',ALL_TIME:'总榜',CURRENT:'当前快照',TOTAL_ASSETS:'总资产',GAME_PROFIT:'游戏净收益',BIGGEST_WIN:'最高单次净赢',TOTAL_WAGERED:'累计投入',POKER_PROFIT:'Poker 净收益',RP_CALLS:'RP 请求数',RP_ERRORS:'RP 错误数',RP_CREDITS:'RP 消耗额度'};
const jobStates:Record<string,string>={PENDING:'等待处理',RUNNING:'正在重建',SHADOW:'影子快照已生成',PUBLISHED:'已发布',FAILED:'重建失败'};
export function OpsRankings(){
 const {client,bootstrap}=useOps(),mutation=useOpsMutation();const [slice,setSlice]=useState(''),[snapshot,setSnapshot]=useState('');const epoch=bootstrap.principal.authz_epoch,blocked=!!mutation.pending||mutation.busy;
 const can=(type:string)=>bootstrap.operations.some(item=>item.operation_type===type&&item.available&&bootstrap.principal.permissions.includes(item.required_permission));
 const resource=useResource(async()=>{try{return overviewSchema.parse(await client.request(`/api/v1/ops/rankings?authz_epoch=${epoch}`))}catch(error){throw new Error(opsError(error))}},[client,epoch]);
 const detail=useResource(async()=>{if(!snapshot)return null;try{const value=detailSchema.parse(await client.request(`/api/v1/ops/rankings/snapshots/${snapshot}?authz_epoch=${epoch}`));if(value.snapshot.snapshot_id!==snapshot)throw new Error('快照编号不一致。');return value}catch(error){throw new Error(opsError(error))}},[client,epoch,snapshot]);
 const selected=resource.data?.aggregation_status.find(item=>item.slice_target_id===slice);
 useEffect(()=>{if(mutation.receipt?.operation.state==='SUCCEEDED'){resource.reload();detail.reload()}},[mutation.receipt?.operation.operation_id,mutation.receipt?.operation.state]);
 function rebuild(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!selected)return;const form=new FormData(event.currentTarget);mutation.prepare({operation_type:'RANKING_REBUILD_CREATE',target:{type:'ranking_slice',id:selected.slice_target_id,expected_version:selected.published_pointer_version},input:{domain:selected.domain,metric:selected.metric,period:selected.period,...(selected.date?{date:selected.date}:{}),model_scope:selected.model_scope||'ALL',...(selected.model_id?{model_id:selected.model_id}:{})},reason:String(form.get('reason')||'').trim()})}
 function publish(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!detail.data)return;const candidate=detail.data.snapshot,form=new FormData(event.currentTarget);const metric=candidate.slice_target_id.split(':')[1];if(!metrics.safeParse(metric).success)return;mutation.prepare({operation_type:'RANKING_REPAIR_PUBLISH',target:{type:'ranking_snapshot',id:candidate.snapshot_id,expected_version:candidate.current_pointer_version},input:{metric},reason:String(form.get('reason')||'').trim()})}
 function snapshots(items:z.infer<typeof snapshotSchema>[],label:string){return <div className="table-wrap" role="region" aria-label={label} tabIndex={0}><table><thead><tr><th>范围</th><th>生成时间</th><th>条目</th><th>状态</th><th>详情</th></tr></thead><tbody>{items.map(item=><tr key={item.snapshot_id}><td>{names[item.domain]} · {names[item.period]}<small>{item.slice_target_id}</small></td><td>{opsTime(item.built_at)}</td><td>{item.entry_count}</td><td>{item.published?'正在发布':item.build_kind}</td><td><button disabled={blocked} onClick={()=>setSnapshot(item.snapshot_id)}>核对快照</button></td></tr>)}</tbody></table></div>}
 return <><header className="page-heading"><div><p className="eyebrow">OPERATIONS / RANKINGS</p><h1>排行榜管理</h1><p>先生成影子快照、比较差异，再独立确认发布；重建不会直接替换当前榜单。</p></div><button onClick={resource.reload} disabled={blocked||resource.loading}>刷新状态</button></header><OpsMutationPanel mutation={mutation}/>
 {resource.loading?<Loading/>:resource.error?<Alert>{resource.error}</Alert>:resource.data&&<><section className="panel ops-business-aggregation"><h2>聚合状态</h2><p className="hint">观察时间：{opsTime(resource.data.generated_at)}</p><div className="table-wrap" role="region" aria-label="排行聚合状态" tabIndex={0}><table><thead><tr><th>榜单</th><th>状态</th><th>来源检查</th><th>延迟</th><th>操作</th></tr></thead><tbody>{resource.data.aggregation_status.map(item=><tr key={item.slice_target_id}><td>{names[item.domain]} · {names[item.metric]} · {names[item.period]}<small>{item.date||'当前范围'}</small></td><td>{item.state}</td><td>{item.last_source_checked_at?opsTime(item.last_source_checked_at):'尚未检查'}</td><td>{item.lag_seconds==null?'未知':item.lag_seconds+' 秒'}</td><td><button disabled={blocked||!can('RANKING_REBUILD_CREATE')} onClick={()=>setSlice(item.slice_target_id)}>准备重建</button></td></tr>)}</tbody></table></div>{!resource.data.aggregation_status.length&&<p>当前没有可读取的聚合状态。</p>}
 {selected&&<form className="ops-business-rebuild" onSubmit={rebuild} key={selected.slice_target_id}><fieldset disabled={blocked||!can('RANKING_REBUILD_CREATE')}><legend>建立影子重建任务</legend><p>{names[selected.domain]} · {names[selected.metric]} · {names[selected.period]} · {selected.date||'当前范围'}</p><p className="hint">目标版本 {selected.published_pointer_version}。后台按持久来源生成候选，不直接编辑用户分数。</p><label>操作原因<textarea name="reason" maxLength={2048} required/></label><button type="submit">读取重建影响</button></fieldset></form>}</section>
 <section className="panel ops-business-jobs"><h2>重建任务</h2><p className="hint">操作受理仅表示已经入队。生成影子快照后仍需独立核对和发布；失败时先查询原操作。</p>{resource.data.rebuild_jobs.length?<div className="table-wrap" role="region" aria-label="排行榜重建任务" tabIndex={0}><table><thead><tr><th>榜单</th><th>任务状态</th><th>最后更新</th><th>处理原因</th><th>记录</th></tr></thead><tbody>{resource.data.rebuild_jobs.map(job=><tr key={job.operation_id}><td>{names[job.metric]} · {names[job.period]}<small>{job.date||'当前范围'}</small></td><td>{jobStates[job.status]}<small>尝试次数 {job.attempts}</small></td><td>{opsTime(job.updated_at)}</td><td>{job.failure_code||'—'}</td><td><Link to={`/ops/operations/${job.operation_id}`}>查询原操作</Link>{job.shadow_snapshot_id&&<button disabled={blocked} onClick={()=>setSnapshot(job.shadow_snapshot_id!)}>核对生成的快照</button>}</td></tr>)}</tbody></table></div>:<p>暂无重建任务。</p>}</section>
 <div className="ops-business-snapshot-grid"><section className="panel ops-business-published"><h2>正在发布的快照</h2><p className="hint">同一批常规快照可包含多个指标，此处合并展示；各指标的发布状态见上方聚合状态。</p>{resource.data.published.length?snapshots(resource.data.published,'已发布快照'):<p>暂无已发布快照。</p>}</section><section className="panel ops-business-shadow"><h2>影子重建候选</h2>{resource.data.shadow_rebuilds.length?snapshots(resource.data.shadow_rebuilds,'影子快照'):<p>暂无影子快照。可在重建任务中查看处理状态。</p>}</section></div></>}
 {snapshot&&<section className="panel ops-business-snapshot-detail"><div className="section-heading"><h2>快照与差异</h2><button onClick={detail.reload} disabled={blocked||detail.loading}>刷新候选</button></div>{detail.loading?<Loading/>:detail.error?<Alert>{detail.error}</Alert>:detail.data&&<><OpsFacts value={detail.data.snapshot}/><h3>与当前快照比较</h3><OpsFacts value={detail.data.diff}/>{!detail.data.snapshot.published&&detail.data.snapshot.pointer_version==='0'&&detail.data.snapshot.build_kind==='REPAIR'&&<form className="ops-business-publish" onSubmit={publish}><fieldset disabled={blocked||!can('RANKING_REPAIR_PUBLISH')}><legend>发布已核对的候选</legend><p>发布会核对当前指针版本，并要求高权限身份验证和输入确认语句。</p><label>发布原因<textarea name="reason" maxLength={2048} required/></label><button type="submit">读取发布影响</button></fieldset></form>}</>}</section>}</>;
}
