import { useState, type FormEvent } from 'react';
import { Link } from 'react-router-dom';
import { Alert, Loading, useResource } from '../ui';
import { opsError, opsVersion } from './ops-api';
import { opsTime } from './OpsOperationDetail';
import { opsInt64, opsPositiveInt64, opsUserID } from './OpsEconomy';
import { useOps } from './OpsShell';
import { OpsMutationPanel, useOpsMutation } from './OpsMutation';

export type OpsUser={newapi_user_id:string;short_account_id:string;profile_status:'INCOMPLETE'|'COMPLETE';display_name:string;profile_version:string;rename_required:boolean;created_at:string};
export function OpsUsers(){
 const {client,bootstrap}=useOps();const [draft,setDraft]=useState(''),[query,setQuery]=useState(''),[selected,setSelected]=useState<OpsUser>();
 const resource=useResource(async()=>{try{const page=await client.request<{items:OpsUser[]}>(`/api/v1/ops/users?authz_epoch=${bootstrap.principal.authz_epoch}&limit=100${query?'&q='+encodeURIComponent(query):''}`);if(!page||!Array.isArray(page.items)||page.items.length>100||new Set(page.items.map(item=>item?.newapi_user_id)).size!==page.items.length||page.items.some(item=>!item||!opsUserID(item.newapi_user_id)||!opsInt64(item.profile_version)||(item.profile_status==='COMPLETE')!==opsPositiveInt64(item.profile_version)||!['INCOMPLETE','COMPLETE'].includes(item.profile_status)||typeof item.display_name!=='string'||typeof item.short_account_id!=='string'||typeof item.rename_required!=='boolean'||!Number.isFinite(Date.parse(item.created_at))))throw new Error('用户列表响应无法核对。');return page.items}catch(error){throw new Error(opsError(error))}},[client,bootstrap.principal.authz_epoch,query]);
 function search(event:FormEvent){event.preventDefault();setQuery(draft.trim());resource.reload()}
 return <><header className="page-heading"><div><p className="eyebrow">OPERATIONS / USERS</p><h1>用户查询</h1><p>查找平台身份，进入获授权的业务记录与支持流程。</p></div><button onClick={resource.reload} disabled={resource.loading}>刷新用户</button></header><section className="panel"><form className="filters" onSubmit={search}><label>账户编号、短编号或昵称<input value={draft} onChange={event=>setDraft(event.target.value)} maxLength={100}/></label><button type="submit">查找用户</button></form>{resource.loading?<Loading/>:resource.error?<Alert>{resource.error}</Alert>:resource.data&&<><div className="table-wrap"><table><thead><tr><th>账户</th><th>Master 资料</th><th>登记时间</th><th>业务入口</th></tr></thead><tbody>{resource.data.map(item=><tr key={item.newapi_user_id}><td>{item.short_account_id}<small>{item.newapi_user_id}</small></td><td>{item.display_name||'尚未设置昵称'}<small>{item.profile_status==='COMPLETE'?'资料完整':'待完成资料'}{item.rename_required?' · 需修改昵称':''}</small></td><td>{opsTime(item.created_at)}</td><td>{bootstrap.principal.permissions.includes('users.master.moderate')&&item.profile_status==='COMPLETE'&&<button disabled={!!selected} onClick={()=>setSelected(item)}>处理昵称</button>}{bootstrap.principal.permissions.includes('records.read')&&<Link to={`/ops/records?subject_newapi_user_id=${item.newapi_user_id}`}>查看业务记录</Link>}{bootstrap.principal.permissions.includes('support-cases.read')&&<Link to={`/ops/support-cases?subject_newapi_user_id=${item.newapi_user_id}`}>支持工单</Link>}</td></tr>)}</tbody></table></div>{!resource.data.length&&<p>没有匹配的用户。</p>}<p className="hint">最多显示 100 项；可使用账户编号精确查询。</p></>}</section>{selected&&<OpsUserModeration key={selected.newapi_user_id} user={selected} onClose={()=>setSelected(undefined)}/>}</>;
}
function OpsUserModeration({user,onClose}:{user:OpsUser;onClose:()=>void}){
 const mutation=useOpsMutation();const [name,setName]=useState(user.display_name),[reason,setReason]=useState('');
 function prepare(type:string,input:Record<string,unknown>){if(!reason.trim())return;mutation.prepare({operation_type:type,target:{type:'MASTER_PROFILE',id:user.newapi_user_id,expected_version:user.profile_version},input,reason:reason.trim()})}
 return <section className="panel"><div className="section-heading"><h2>Master 昵称处理 · {user.newapi_user_id}</h2><button disabled={!!mutation.pending} onClick={onClose}>关闭处理</button></div><fieldset disabled={!!mutation.pending}><label>操作原因<textarea value={reason} onChange={event=>setReason(event.target.value)} maxLength={1000}/></label><button disabled={!reason.trim()} onClick={()=>prepare('MASTER_RENAME_REQUIRED',{required:!user.rename_required})}>{user.rename_required?'预览清除改名要求':'预览要求用户改名'}</button><label>更正后的昵称<input value={name} onChange={event=>setName(event.target.value)} maxLength={64}/></label><button disabled={!reason.trim()||!name.trim()} onClick={()=>prepare('MASTER_FORCE_RENAME',{display_name:name.trim()})}>预览管理员更名</button></fieldset><p className="hint">完成后请刷新用户列表，重新选择用户以核对最新资料。</p><OpsMutationPanel mutation={mutation}/></section>;
}


