import {act,fireEvent,render,screen,waitFor,within} from '@testing-library/react';
import {Link,MemoryRouter,Route,Routes,useLocation} from 'react-router-dom';
import {expect,it,vi} from 'vitest';
import {ApiClient} from '../api';
import {RouletteLobby} from './RouletteLobby';
import {RouletteRoom} from './RouletteRoom';
import {PressureTable} from './PressureTable';
import type {RoomView} from './roulette-api';

it('keeps both roulette variants folded while recovering original create and room commands by readonly receipt evidence',async()=>{
 sessionStorage.clear();
 const round='01990000-0000-7000-8000-000000000001',other='01990000-0000-7000-8000-000000000002',config='01990000-0000-7000-8000-000000000003',policy='01990000-0000-7000-8000-000000000004',created='01990000-0000-7000-8000-000000000005';
 const binding=(game:'devil-roulette'|'pressure-roulette'):RoomView['binding']=>({config_version_id:config,config_hash:'a'.repeat(64),wager_policy_version_id:policy,wager_policy_hash:'b'.repeat(64),ruleset_version:game==='devil-roulette'?'momiao-devil-rules-v1':'momiao-pressure-rules-v1',algorithm_version:game==='devil-roulette'?'momiao-devil-rng-v1':'momiao-pressure-rng-v1',fairness_stream_version:'chaldea-pf-hmac-sha256-v1'});
 const lobby=(game:'devil-roulette'|'pressure-roulette')=>({game,state:'PLAY',binding:binding(game),minimum_units:'1000000',step_units:'1000000',available_units:'100000000',own_round_id:null,rooms:[],next_cursor:null,csrf_token:'c'.repeat(64)});
 const room=(game:'devil-roulette'|'pressure-roulette',id:string,version='1')=>({id,game,title:game==='devil-roulette'?'合成恶魔桌':'合成加压桌',version,sequence:version==='1'?'0':'1',state:'WAITING',target_players:game==='devil-roulette'?2:3,stake_units:'5000000',pool_units:version==='1'?'0':'5000000',binding:binding(game),server_seed_hash:'d'.repeat(64),turn_seat:null,server_now:'2026-09-22T12:00:00+08:00',deadline:'2099-09-22T12:05:00+08:00',game_deadline:null,players:[{seat:0,name:'御主',ready:version!=='1',alive:true,forfeited:false,hp:4,item_count:4}],self:{seat:0,available_units:'100000000',items:['handcuffs','magnifier','phone','medicine'],intel:[{index:0,live:true}]},actions:version==='1'?[{kind:'READY'},{kind:'LEAVE'},{kind:'CANCEL'}]:[{kind:'UNREADY'},{kind:'CANCEL'}],log:[],devil:null,pressure:null});
 const ok=(data:unknown)=>new Response(JSON.stringify({success:true,data}),{headers:{'Content-Type':'application/json'}}),failed=(status:number,code:string,message:string)=>new Response(JSON.stringify({success:false,error:{code,message}}),{status,headers:{'Content-Type':'application/json'}}),missing=()=>failed(404,'ROULETTE_NOT_FOUND','尚无回执');
 const login={access_token:'synthetic',access_expires_at:4102444800,user:{id:910002,username:'synthetic',display_name:'御主',role:1},session:{sid:'synthetic'}};
 let hidden=false,online=true,authoritative=false,roomUnavailable=false,wrongRoomID=false,failedRoomReads=0,wrongRoomReads=0,createdRoomReads=0,createReceiptReads=0,receiptReads=0,resolveFirst!:(value:Response)=>void,resolveSecond!:(value:Response)=>void;
 const firstReceipt=new Promise<Response>(resolve=>resolveFirst=resolve),secondReceipt=new Promise<Response>(resolve=>resolveSecond=resolve),createPosts:{key:string;body:any}[]=[],commandPosts:{path:string;key:string;body:any}[]=[],createReceiptMethods:string[]=[],receiptMethods:string[]=[];
 vi.spyOn(document,'hidden','get').mockImplementation(()=>hidden);vi.spyOn(navigator,'onLine','get').mockImplementation(()=>online);
 const fetcher=vi.fn(async(path:string,init?:RequestInit)=>{
  if(path==='/api/user/login')return ok(login);
  if(path.startsWith('/api/v1/roulette?game='))return ok(lobby(path.includes('pressure-roulette')?'pressure-roulette':'devil-roulette'));
  if(path==='/api/v1/roulette/rooms'&&init?.method==='POST'){const headers=new Headers(init.headers);createPosts.push({key:headers.get('Idempotency-Key')||'',body:JSON.parse(String(init.body))});throw new TypeError('synthetic lost create ACK');}
  if(path===`/api/v1/roulette/rooms/${round}/commands`){const headers=new Headers(init?.headers);commandPosts.push({path,key:headers.get('Idempotency-Key')||'',body:JSON.parse(String(init?.body))});return missing();}
  if(path===`/api/v1/roulette/receipts/${createPosts[0]?.key}`){createReceiptReads++;createReceiptMethods.push(String(init?.method));return createReceiptReads===1?missing():ok({round_id:created,version:'1',sequence:'0',state:'WAITING'});}
  if(path===`/api/v1/roulette/receipts/${commandPosts[0]?.key}`){receiptReads++;receiptMethods.push(String(init?.method));return receiptReads===1?firstReceipt:receiptReads===2?secondReceipt:ok({round_id:round,version:'2',sequence:'1',state:'WAITING'});}
  if(path===`/api/v1/roulette/rooms/${created}`){createdRoomReads++;return ok(room('devil-roulette',created));}
  if(path===`/api/v1/roulette/rooms/${round}`){if(roomUnavailable){failedRoomReads++;return failed(503,'ROULETTE_UNAVAILABLE','桌面暂不可读');}if(wrongRoomID){wrongRoomReads++;return ok({...room('devil-roulette',round),'id':other,title:'错误房间'});}return ok(room('devil-roulette',round,authoritative?'2':'1'));}
  if(path===`/api/v1/roulette/rooms/${other}`)return ok(room('pressure-roulette',other));
  throw new Error(`unexpected ${init?.method||'GET'} ${path}`);
 });
 const client=new ApiClient(fetcher);await client.login('synthetic','synthetic');

 for(const slug of ['devil-roulette','pressure-roulette'] as const){
  const lobbyView=render(<MemoryRouter><RouletteLobby client={client} userID="910002" slug={slug}/></MemoryRouter>);
  expect(await screen.findByRole('button',{name:/创建房间/})).toBeVisible();expect(screen.getByLabelText('每人投入 / 筹码')).toBeVisible();expect(screen.queryByRole('dialog')).not.toBeInTheDocument();
  if(slug==='pressure-roulette'){expect(lobbyView.container.querySelector('.roulette-pressure-lobby.roulette-salon-lobby')).not.toBeNull();expect(screen.getByRole('combobox',{name:'开局人数'})).toHaveValue('4');expect(screen.getAllByRole('option')).toHaveLength(4);}
  fireEvent.click(screen.getByRole('button',{name:'游戏规则'}));expect(await screen.findByRole('dialog',{name:'游戏规则'})).toBeVisible();fireEvent.click(within(screen.getByRole('dialog')).getByRole('button',{name:'关闭对话框'}));
  fireEvent.click(screen.getByRole('button',{name:'公平验证'}));expect(await screen.findByRole('dialog',{name:'公平验证'})).toBeVisible();fireEvent.click(within(screen.getByRole('dialog')).getByRole('button',{name:'关闭对话框'}));
  lobbyView.unmount();
 }

 const lobbyRecovery=render(<MemoryRouter initialEntries={['/roulette/devil-roulette']}><Routes><Route path="/roulette/devil-roulette" element={<RouletteLobby client={client} userID="910002" slug="devil-roulette"/>}/><Route path="/roulette/pressure-roulette" element={<RouletteLobby client={client} userID="910002" slug="pressure-roulette"/>}/><Route path="/roulette/rooms/:id" element={<p>创建恢复完成</p>}/></Routes></MemoryRouter>);
 expect(await screen.findByRole('button',{name:/创建房间/})).toBeEnabled();hidden=true;fireEvent.click(screen.getByRole('button',{name:/创建房间/}));await waitFor(()=>expect(createPosts).toHaveLength(1));const createKey=createPosts[0].key,createSlot=`momiao.roulette.pending.v1.910002.${client.getSessionGeneration()}.create`;expect(JSON.parse(sessionStorage.getItem(createSlot)!).key).toBe(createKey);expect(screen.getByRole('button',{name:'正在同步创建结果…'})).toBeDisabled();
 hidden=false;document.dispatchEvent(new Event('visibilitychange'));await waitFor(()=>expect(createReceiptReads).toBe(1));expect(JSON.parse(sessionStorage.getItem(createSlot)!).key).toBe(createKey);expect(createPosts).toHaveLength(1);
 hidden=true;fireEvent.click(screen.getByRole('link',{name:'圆桌危局'}));expect(await screen.findByRole('heading',{name:/加压轮盘/})).toBeVisible();fireEvent.click(await screen.findByRole('button',{name:'创建状态'}));const createStatus=await screen.findByRole('dialog',{name:'创建状态'});fireEvent.click(within(createStatus).getByText('回执异常详情'));expect(within(createStatus).queryByRole('button',{name:'同标识重试原创建'})).not.toBeInTheDocument();fireEvent.click(within(createStatus).getByRole('link',{name:'返回原游戏查看创建状态'}));expect(await screen.findByRole('heading',{name:/恶魔轮盘/})).toBeVisible();expect(createPosts).toHaveLength(1);
 hidden=false;document.dispatchEvent(new Event('visibilitychange'));expect(await screen.findByText('创建恢复完成')).toBeVisible();expect(sessionStorage.getItem(createSlot)).toBeNull();expect(createdRoomReads).toBe(1);expect(createReceiptMethods).toEqual(['GET','GET']);expect(createPosts[0].body).toEqual({game:'devil-roulette',stake:'10',players:2});lobbyRecovery.unmount();

 function SwitchRoom(){const {pathname}=useLocation();return <Link to={pathname.endsWith(round)?`/roulette/rooms/${other}`:`/roulette/rooms/${round}`}>切换测试房间</Link>}
 const roomView=render(<MemoryRouter initialEntries={[`/roulette/rooms/${round}`]}><Routes><Route path="/roulette/rooms/:id" element={<><SwitchRoom/><RouletteRoom client={client} userID="910002"/></>}/></Routes></MemoryRouter>);
 expect(await screen.findByRole('heading',{name:'合成恶魔桌'})).toBeVisible();expect(roomView.container.querySelector('.roulette-devil-room')).not.toBeNull();expect(screen.queryByRole('dialog')).not.toBeInTheDocument();
 fireEvent.click(screen.getByRole('button',{name:'托管准备'}));let ready=await screen.findByRole('dialog',{name:'准备并托管'});expect(within(ready).getByText('10')).toBeVisible();expect(within(ready).getByText('d'.repeat(64))).toBeVisible();const seedInput=within(ready).getByLabelText('你的随机贡献'),slot=`momiao.roulette.pending.v1.910002.${client.getSessionGeneration()}.${round}`;fireEvent.change(seedInput,{target:{value:''}});fireEvent.click(within(ready).getByRole('button',{name:'确认并托管 10 筹码'}));ready=await screen.findByRole('dialog',{name:'准备并托管'});expect(within(ready).getByRole('alert')).toHaveTextContent('随机贡献需为 1—128 字节，且不含控制字符。');expect(screen.getAllByRole('alert')).toHaveLength(1);expect(commandPosts).toHaveLength(0);expect(sessionStorage.getItem(slot)).toBeNull();fireEvent.change(within(ready).getByLabelText('你的随机贡献'),{target:{value:'synthetic-client-seed'}});
 hidden=true;fireEvent.click(within(ready).getByRole('button',{name:'确认并托管 10 筹码'}));await waitFor(()=>expect(commandPosts).toHaveLength(1));const original=commandPosts[0].key;expect(JSON.parse(sessionStorage.getItem(slot)!).key).toBe(original);expect(screen.getByRole('status')).toHaveTextContent('只读核对');
 window.dispatchEvent(new Event('online'));await act(async()=>{await Promise.resolve();});expect(receiptReads).toBe(0);
 hidden=false;document.dispatchEvent(new Event('visibilitychange'));await waitFor(()=>expect(receiptReads).toBe(1));document.dispatchEvent(new Event('visibilitychange'));window.dispatchEvent(new Event('online'));expect(receiptReads).toBe(1);
 resolveFirst(missing());expect(await screen.findByText(/退避间隔继续只读核对/)).toBeVisible();expect(JSON.parse(sessionStorage.getItem(slot)!).key).toBe(original);expect(screen.getByText('回执异常详情').closest('details')).not.toHaveAttribute('open');expect(commandPosts).toHaveLength(1);
 roomUnavailable=true;window.dispatchEvent(new Event('online'));await waitFor(()=>expect(receiptReads).toBe(2));window.dispatchEvent(new Event('online'));expect(receiptReads).toBe(2);
 fireEvent.click(screen.getByRole('link',{name:'切换测试房间'}));expect(await screen.findByRole('heading',{name:'合成加压桌'})).toBeVisible();expect(roomView.container.querySelector('.roulette-devil-room')).toBeNull();
 resolveSecond(ok({round_id:round,version:'2',sequence:'1',state:'WAITING'}));await act(async()=>{await secondReceipt;});expect(JSON.parse(sessionStorage.getItem(slot)!).key).toBe(original);expect(commandPosts).toHaveLength(1);
 fireEvent.click(screen.getByRole('link',{name:'切换测试房间'}));await waitFor(()=>expect(receiptReads).toBe(3));expect(failedRoomReads).toBeGreaterThan(0);expect(JSON.parse(sessionStorage.getItem(slot)!).key).toBe(original);expect(commandPosts).toHaveLength(1);
 roomUnavailable=false;wrongRoomID=true;window.dispatchEvent(new Event('online'));await waitFor(()=>expect(wrongRoomReads).toBe(1));expect(screen.queryByRole('heading',{name:'错误房间'})).not.toBeInTheDocument();expect(sessionStorage.getItem(slot)).not.toBeNull();wrongRoomID=false;window.dispatchEvent(new Event('online'));expect(await screen.findByRole('heading',{name:'合成恶魔桌'})).toBeVisible();expect(screen.getByRole('status')).toHaveTextContent('回执已确认');expect(sessionStorage.getItem(slot)).not.toBeNull();
 expect(screen.queryByText('当前一发')).not.toBeNull();fireEvent.click(screen.getByRole('button',{name:'查看私密情报与行动记录'}));expect(await screen.findByRole('dialog',{name:'私密情报与行动记录'})).toHaveTextContent('当前一发实弹');fireEvent.click(within(screen.getByRole('dialog')).getByRole('button',{name:'关闭对话框'}));
 for(const name of ['游戏规则','公平验证']){fireEvent.click(screen.getByRole('button',{name}));expect(await screen.findByRole('dialog',{name})).toBeVisible();fireEvent.click(within(screen.getByRole('dialog')).getByRole('button',{name:'关闭对话框'}));}
 authoritative=true;window.dispatchEvent(new Event('online'));await waitFor(()=>expect(sessionStorage.getItem(slot)).toBeNull());expect(createPosts).toHaveLength(1);expect(commandPosts).toHaveLength(1);expect(receiptMethods).toEqual(['GET','GET','GET']);expect(commandPosts[0].body.ready).toMatchObject({client_seed:'synthetic-client-seed',server_seed_hash:'d'.repeat(64)});roomView.unmount();
 const pressure:RoomView={...room('pressure-roulette',other),state:'PLAYING',target_players:6,turn_seat:0,game_deadline:'2099-09-22T12:30:00+08:00',players:Array.from({length:6},(_,seat)=>({seat,name:`玩家${seat+1}`,ready:true,alive:true,forfeited:false,hp:0,item_count:0})),self:{seat:0,available_units:'100000000',items:[],intel:[]},devil:null,pressure:{actual_load:2,forced_shots:1,order:[0,1,2,3,4,5],pointer:2,unload_skips_shot:false,timeout_tier:0,phase:'CHOICE',chambers:['EMPTY','DUD_SPENT','UNKNOWN','UNKNOWN','UNKNOWN','UNKNOWN'],pool_remaining:6,duds:2,charge:1,loaded:3,forced:0,aggressor:null,riposte_target:null,votes:{}},actions:[{kind:'PRESSURE_PASS'},{kind:'PRESSURE_AGAIN'},{kind:'PRESSURE_CHARGE'}]};
 const onAction=vi.fn(),table=render(<PressureTable view={pressure} onAction={onAction} busy={false} timer="00:32"/>);
 expect(table.container.querySelector('.roulette-pressure')).toHaveAttribute('data-phase','CHOICE');expect(table.container.querySelectorAll('.roulette-player')).toHaveLength(6);expect(table.container.querySelector('.roulette-pressure-center>img')).toHaveAttribute('src',expect.stringMatching(/games\/roulette\/pressure-revolver\.[a-f0-9]{12}\.webp/));
 expect(within(screen.getByRole('list',{name:'公开弹巢状态'})).getAllByRole('listitem')).toHaveLength(6);expect(screen.queryByText(/金圈为下一格/)).not.toBeInTheDocument();
 fireEvent.click(screen.getByRole('button',{name:/加压传枪/}));expect(onAction).toHaveBeenCalledWith(pressure.actions[2]);
 table.rerender(<PressureTable view={pressure} onAction={onAction} busy timer="00:31"/>);expect(screen.getByRole('button',{name:/加压传枪/})).toBeDisabled();
 const vote:RoomView={...pressure,pressure:{...pressure.pressure!,phase:'VOTE',votes:{'0':true}},actions:[{kind:'PRESSURE_VOTE',agree:true},{kind:'PRESSURE_VOTE',agree:false}]};
 table.rerender(<PressureTable view={vote} onAction={onAction} busy={false} timer="00:20"/>);fireEvent.click(screen.getByRole('button',{name:/继续新波/}));expect(onAction).toHaveBeenLastCalledWith({kind:'PRESSURE_VOTE',agree:false});expect(screen.getByText(/已投票 1 \/ 6/)).toBeVisible();
 table.rerender(<PressureTable view={{...pressure,self:null,actions:[]}} onAction={onAction} busy={false} timer="00:20"/>);expect(screen.queryByRole('button')).not.toBeInTheDocument();table.unmount();
 online=false;
});
