"""Bind existing G2 measurements to compiled configs; never generate outcomes.

Raw UNBOUND artifacts stay in the supplied evidence directory. Output is a
portable, non-secret measurement reference and a separate review receipt.
"""
import argparse
import hashlib
import json
from pathlib import Path

p=argparse.ArgumentParser()
p.add_argument('--configs',required=True)
p.add_argument('--artifacts',required=True)
p.add_argument('--receipt',required=True)
args=p.parse_args()
root=Path(__file__).resolve().parent.parent
configs=json.loads(Path(args.configs).read_text(encoding='utf-8-sig'))
evidence=Path(args.artifacts)

def sha(raw): return hashlib.sha256(raw).hexdigest()
def compact_go(value,sort=False):
    text=json.dumps(value,ensure_ascii=False,separators=(',',':'),sort_keys=sort)
    for a,b in [('&','\\u0026'),('<','\\u003c'),('>','\\u003e'),('\u2028','\\u2028'),('\u2029','\\u2029')]: text=text.replace(a,b)
    return text

receipt={'status':'READY_FOR_CONTROLLER_REVIEW','source_artifacts_unchanged':True,'measurements_rerun':False,'games':{}}
summaries={}
expected_artifacts={'slot':'d2b32d4bb9d6f704708959a563261288c49da557d7e55a8f90dde7176a0e57d7','blackjack':'0dfe5045ac000979be8f5c0c3ffe28b78784a9bdeab3aa0b60cc141c707f81ca'}
for game,name in [('slot','slot-exact.json'),('blackjack','blackjack-reference.json')]:
    a=json.loads((evidence/name).read_text(encoding='utf-8-sig'))
    raw_result=compact_go(a['result'])
    assert sha(raw_result.encode())==a['result_sha256']
    saved=a['artifact_sha256'];a['artifact_sha256']=''
    assert saved==expected_artifacts[game] and sha(compact_go(a).encode())==saved
    assert a['production_status']=='NOT_PRODUCTION_VERIFIED' and a['config_binding']['status']=='UNBOUND'
    c=configs[game];b=a['config_binding']
    assert (c['implementation'],c['ruleset'],c['algorithm'],c['schema'])==(b['implementation_key'],b['ruleset_version'],b['algorithm_version'],b['config_schema_version'])
    payload=compact_go(c['canonical_payload'],True).encode()
    assert sha(payload)==c['canonical_payload_sha256']
    identities=[game,c['schema'],c['algorithm']]
    envelope=b'CHALDEA-GAME-CONFIG-V1\0'+b''.join(len(s.encode()).to_bytes(2,'big')+s.encode() for s in identities)+payload
    assert sha(envelope)==c['config_hash']
    owned={}
    for file,want in a['resource_sha256'].items():
        if file in ('go.mod','go.sum') or file.startswith(('internal/games/slot/','internal/games/blackjack/')):
            assert sha((root/file).read_bytes())==want,file+' differs from measured engine'
            owned[file]=want
    if game=='slot':
        assert configs['slot_frozen_resource_sha256']==a['resource_sha256']['slot.FrozenConfig JSON']
        assert a['result']['cases']==33554432 and a['result']['complete'] and a['result']['frozen_targets_matched']
    else:
        assert a['result']['rounds']==10000000 and a['result']['complete']
        assert a['result']['reference_strategy_sha256']==a['resource_sha256']['reference strategy JSON']
    summary={
        'artifact_type':'SLOT_EXHAUSTIVE' if game=='slot' else 'BLACKJACK_RTP',
        'source_artifact_sha256':saved,'source_result_sha256':a['result_sha256'],
        'validation_build':a['run']['build_settings']['vcs.revision'],
        'validator_version':a['validator_version'],'source_binary_sha256':a['run']['binary_sha256'],
        'config_version':c['config_version'],'config_hash':c['config_hash'],
        'canonical_payload_sha256':c['canonical_payload_sha256'],
        'implementation_key':c['implementation'],'ruleset_version':c['ruleset'],'algorithm_version':c['algorithm'],
        'engine_resource_sha256':owned,'result_json':raw_result,
    }
    summaries[game]=compact_go(summary,True)
    receipt['games'][game]={**c,'source_artifact_sha256':saved,'bound_summary_sha256':sha(summaries[game].encode()),'engine_resource_sha256':owned}
generated='// Code generated by scripts/games_bind_extra.py from measured G2 artifacts; DO NOT EDIT.\npackage games\n\nvar extraValidationSummaries = map[string]string{\n'
for game,summary in summaries.items(): generated+=json.dumps(game)+': '+json.dumps(summary,ensure_ascii=False)+',\n'
generated+='}\n'
(root/'internal/games/extra_validation_data.go').write_text(generated,encoding='utf-8')
Path(args.receipt).write_text(json.dumps(receipt,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
for game,c in receipt['games'].items(): print(game,c['config_version'],'config_hash='+c['config_hash'],'summary_sha256='+c['bound_summary_sha256'])
print('Existing measured artifacts pinned to exact compiled resources/configs; no new gameplay samples. Controller review remains separate.')
