import { act, cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import { afterEach, beforeEach, expect, it, vi } from 'vitest';
import { ApiClient, ApiError } from './api';
import { GamePage, RoundReceipt } from './Games';
import * as gameAPI from './games-api';
import type { GameBootstrap, GameRound } from './games-api';

const id='01993200-0000-7000-8000-000000000001';
const commitment='01993200-0000-7000-8000-000000000002';
const hash='a'.repeat(64);
const result:GameRound={id,game:'dice',state:'SETTLED',recovery_state:'NORMAL',input:{type:'DICE',wager:'10',choice:'SMALL'},total_stake_units:'5000000',total_payout_units:'10000000',net_change_units:'5000000',common_result:'WIN',balance_before_units:'500000000',balance_after_units:'505000000',wager_transaction_id:id,settlement_transaction_id:commitment,config_version_id:id,config_hash:hash,wager_policy_version_id:id,wager_policy_hash:hash,algorithm_version:'dice-map-v1',ruleset_version:'dice-rules-v1',fairness_stream_version:'chaldea-pf-hmac-sha256-v1',nonce:'0',commitment_id:commitment,created_at:'2026-09-06T10:00:00Z',settled_at:'2026-09-06T10:00:00Z',dice:{dice:[2,3,4],total:9,triple:false,side:'SMALL',choice:'SMALL',reward:{cost_multiplier:'1',payout_multiplier:'2',outcome:'WIN'}}};
const bootstrap:GameBootstrap={game:{slug:'dice',title:'命运骰盅',effective_runtime:'PLAY',implementation_key:'direct.dice.v1',config:{version_id:id,hash,schema:'dice-config-v1',ruleset_version:'dice-rules-v1',algorithm_version:'dice-map-v1',statistics:{rtp:'35/36',loss:'37/72',win:'35/72',top:'0',break_even:'0'}}},wager_policy:{version_id:id,version:'1',minimum_wager_units:'5000000',maximum_mode:'NONE',input_step_units:'500000',quick_amount_units:['5000000','50000000','250000000','500000000'],hash},available_units:'500000000',latest_round:null,active_round:null,scratch_presentation_blocker:null,effective_entry_action:'PLAY',next_commitment:{id:commitment,reserved_round_id:id,server_seed_hash:hash,nonce:'0',client_seed:'cs1-fixture',client_seed_version:'1',config_version_id:id,config_hash:hash,ruleset_version:'dice-rules-v1',algorithm_version:'dice-map-v1',fairness_stream_version:'chaldea-pf-hmac-sha256-v1',wager_policy_version_id:id,wager_policy_hash:hash,resource_versions:{}},client_seed_preference:{client_seed:'cs1-fixture',version:'1'},csrf_token:hash};
let client:ApiClient;
beforeEach(()=>{
    sessionStorage.clear();client=new ApiClient();
    vi.spyOn(client,'getSnapshot').mockReturnValue({user:{id:1,username:'fixture',display_name:'Fixture',role:1},ready:true,loggingOut:false,notice:''});
    vi.spyOn(gameAPI,'readGameBootstrap').mockResolvedValue(structuredClone(bootstrap));
});
afterEach(()=>vi.restoreAllMocks());
function show(){return render(<MemoryRouter><GamePage client={client} userID="1" slug="dice"/></MemoryRouter>)}
it('Slot adapter submits total chips only and keeps a lost response locked for reconciliation',async()=>{
    vi.mocked(gameAPI.readGameBootstrap).mockResolvedValue({...bootstrap,game:{...bootstrap.game,slug:'slot',config:undefined}});
    const create=vi.spyOn(gameAPI,'createGame').mockRejectedValue(new ApiError('lost response',0,'',true));
    vi.spyOn(gameAPI,'findPendingGame').mockReturnValue(new Promise(()=>{}));
    const view=render(<MemoryRouter><GamePage client={client} userID="1" slug="slot"/></MemoryRouter>);
    await waitFor(()=>expect(screen.getByRole('button',{name:'Spin · 10 筹码'})).toBeEnabled());
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument();
    expect(screen.queryByRole('heading',{name:'开局前的承诺'})).not.toBeInTheDocument();
    const fairness=screen.getByRole('button',{name:'公平验证'});fairness.focus();fireEvent.click(fairness);
    const before=screen.getByRole('dialog',{name:'公平验证'});
    expect(within(before).getByText(hash)).toBeVisible();
    expect(within(before).getByLabelText('Client Seed')).toHaveValue('cs1-fixture');
    fireEvent(before,new Event('cancel',{bubbles:true,cancelable:true}));expect(screen.queryByRole('dialog')).not.toBeInTheDocument();expect(fairness).toHaveFocus();
    let saved!:(value:unknown)=>void;
    const request=vi.spyOn(client,'request').mockReturnValueOnce(new Promise(resolve=>{saved=resolve}));
    fireEvent.click(fairness);fireEvent.click(screen.getByText('自定义 Client Seed'));
    fireEvent.click(screen.getByRole('button',{name:'更新下一局种子'}));
    expect(screen.getByRole('button',{name:'关闭对话框'})).toBeDisabled();
    fireEvent(screen.getByRole('dialog'),new Event('cancel',{bubbles:true,cancelable:true}));
    expect(screen.getByRole('dialog')).toBeInTheDocument();
    saved(bootstrap.next_commitment);
    await waitFor(()=>expect(gameAPI.readGameBootstrap).toHaveBeenCalledTimes(2));
    await waitFor(()=>expect(screen.getByRole('button',{name:'关闭对话框'})).toBeEnabled());
    fireEvent.click(screen.getByRole('button',{name:'关闭对话框'}));
    fireEvent.change(screen.getByLabelText('总下注 · 筹码'),{target:{value:'11'}});
    fireEvent.click(screen.getByRole('button',{name:'Spin · 11 筹码'}));
    await waitFor(()=>expect(create).toHaveBeenCalledTimes(1));
    expect(screen.queryByRole('button',{name:/核对本局/})).not.toBeInTheDocument();
    expect(create).toHaveBeenCalledTimes(1);
    expect(create.mock.calls[0][2].input).toEqual({type:'SLOT',total_wager:'11'});
    expect(screen.getByRole('button',{name:'Spin · 11 筹码'})).toBeDisabled();
    fireEvent.click(fairness);
    expect(within(screen.getByRole('dialog')).getByLabelText('Client Seed')).toBeDisabled();
    fireEvent.click(screen.getByRole('button',{name:'关闭对话框'}));
    view.unmount();sessionStorage.clear();
    const historicalSlot={...result,game:'slot',input:{type:'SLOT',total_wager:'10'},dice:undefined,ruleset_version:'slot-rules-v1',slot:{stops:[0,0,0,0,0],full_grid:Array.from({length:5},()=>['L1','L2','L3']),lines:Array.from({length:10},(_,index)=>({line_number:index+1,interpreted_symbol:'',match_length:0,multiplier:0,line_stake_units:'500000',line_payout_units:'0'})),total_wager_units:'5000000',line_stake_units:'500000',total_payout_units:'10000000',net_change_units:'5000000',result_class:'WIN',result_detail:'WIN'}} as GameRound;
    vi.mocked(gameAPI.readGameBootstrap).mockResolvedValue({...bootstrap,game:{...bootstrap.game,slug:'slot',config:{...bootstrap.game.config!,ruleset_version:'slot-rules-v3'}},latest_round:historicalSlot});
    render(<MemoryRouter><GamePage client={client} userID="1" slug="slot"/></MemoryRouter>);await screen.findByText('本局结果已确认。下一局仍需主动 Spin。');
    expect(screen.queryByRole('table')).not.toBeInTheDocument();
    expect(screen.getByLabelText('本局结算')).toHaveTextContent('+10');
    fireEvent.click(screen.getByRole('button',{name:'奖表与固定规则'}));
    expect(screen.getByRole('table',{name:'slot-paytable-v1 奖励倍率表'})).toBeInTheDocument();expect(screen.queryByRole('table',{name:'slot-paytable-v3 奖励倍率表'})).not.toBeInTheDocument();
    fireEvent.click(screen.getByRole('button',{name:'关闭对话框'}));
    request.mockResolvedValue({round_id:id,verified:true,reveal_state:'REVEALED',server_seed_hash:hash,server_seed:'revealed-test-seed',commitment:bootstrap.next_commitment,canonical_config:'{}',result:historicalSlot});
    fireEvent.click(screen.getByRole('button',{name:'公平验证'}));fireEvent.click(screen.getByRole('button',{name:'验证本局'}));
    expect(await screen.findByText('验证通过：结果与原始输入一致')).toBeVisible();
    expect(request).toHaveBeenCalledWith(`/api/v1/game-rounds/${id}/fairness`);
    expect(create).toHaveBeenCalledTimes(1);
});
it('Blackjack resumes an active hand during maintenance and locks an uncertain action across refresh',async()=>{
    const active={...result,game:'blackjack',state:'PLAYER_TURN',input:{type:'BLACKJACK',initial_wager:'10'},total_payout_units:'0',net_change_units:'-5000000',common_result:'',balance_after_units:'495000000',settlement_transaction_id:'',settled_at:null,dice:undefined,
        blackjack:{phase:'PLAYER_TURN',round_version:'1',active_hand_id:id,hands:[{hand_id:id,hand_index:0,cards:[7,20],stake_units:'5000000',hand_state:'ACTIVE',value:{hard_total:16,best_total:16,is_soft:false},is_natural:false,payout_units:'0',net_change_units:'0'}],dealer_cards:[4],dealer_revealed:false,legal_actions:['HIT','STAND','DOUBLE','SPLIT'],last_player_action_at:'2026-09-06T10:00:00Z',auto_resolve_at:'2026-09-07T10:00:00Z',total_stake_units:'5000000',total_payout_units:'0',net_change_units:'0'}} as GameRound;
    const split={...active,total_stake_units:'10000000',net_change_units:'-10000000',balance_after_units:'490000000',blackjack:{...active.blackjack!,round_version:'2',total_stake_units:'10000000',hands:[active.blackjack!.hands[0],{...active.blackjack!.hands[0],hand_id:commitment,hand_index:4}]}};
    expect(gameAPI.parseRound(split).blackjack?.hands.map(h=>h.hand_index)).toEqual([0,4]);
    vi.mocked(gameAPI.readGameBootstrap).mockResolvedValue({...bootstrap,game:{...bootstrap.game,slug:'blackjack',effective_runtime:'MAINTENANCE',config:undefined},active_round:active,latest_round:active,next_commitment:null,effective_entry_action:'RESUME'});
    const request=vi.spyOn(client,'request').mockRejectedValue(new ApiError('lost action response',0,'',true));
    const lookup=vi.spyOn(gameAPI,'findBlackjackAction').mockRejectedValue(new ApiError('offline',0,'',true));
    const first=render(<MemoryRouter><GamePage client={client} userID="1" slug="blackjack"/></MemoryRouter>);
    await waitFor(()=>expect(screen.getByRole('button',{name:'Stand · 停牌'})).toBeEnabled());
    expect(screen.queryByRole('button',{name:/Deal ·/})).not.toBeInTheDocument();
    expect(screen.getByRole('img',{name:'庄家暗牌，尚未公开'})).toBeVisible();
    expect(screen.queryByRole('heading',{name:'固定规则'})).not.toBeInTheDocument();
    const rules=screen.getByRole('button',{name:'游戏规则'});rules.focus();fireEvent.click(rules);
    expect(screen.getByRole('dialog',{name:'游戏规则'})).toHaveTextContent('最多 4 手');
    fireEvent(screen.getByRole('dialog'),new Event('cancel',{bubbles:true,cancelable:true}));expect(rules).toHaveFocus();
    fireEvent.click(screen.getByRole('button',{name:'公平验证'}));
    expect(within(screen.getByRole('dialog')).getByLabelText('Client Seed')).toBeDisabled();
    fireEvent.click(screen.getByRole('button',{name:'关闭对话框'}));
    fireEvent.click(screen.getByRole('button',{name:'Stand · 停牌'}));
    await waitFor(()=>expect(sessionStorage.getItem(gameAPI.blackjackActionStorage('1'))).not.toBeNull());
    const original=JSON.parse(sessionStorage.getItem(gameAPI.blackjackActionStorage('1'))!);
    expect(request.mock.calls[0][2]).toMatchObject({action_type:'STAND',hand_id:id,expected_round_version:'1'});
    expect(screen.queryByRole('button',{name:/核对本次行动|重试原行动|核对本局/})).not.toBeInTheDocument();
    expect(screen.getByRole('button',{name:'Hit · 要牌'})).toBeDisabled();
    await waitFor(()=>expect(lookup).toHaveBeenCalledWith(client,original),{timeout:2500});
    expect(screen.getByRole('img',{name:'庄家暗牌，尚未公开'})).toBeVisible();
    expect(sessionStorage.getItem(gameAPI.blackjackActionStorage('1'))).not.toBeNull();
    first.unmount();lookup.mockResolvedValue(active);
    const second=render(<MemoryRouter><GamePage client={client} userID="1" slug="blackjack"/></MemoryRouter>);
    await waitFor(()=>expect(sessionStorage.getItem(gameAPI.blackjackActionStorage('1'))).toBeNull());
    expect(screen.getByRole('button',{name:'Hit · 要牌'})).toBeEnabled();
    expect(request.mock.calls.filter(c=>c[1]==='POST')).toHaveLength(1);
    second.unmount();sessionStorage.setItem(gameAPI.blackjackActionStorage('1'),JSON.stringify(original));
    lookup.mockResolvedValue(null);
    render(<MemoryRouter><GamePage client={client} userID="1" slug="blackjack"/></MemoryRouter>);
    await waitFor(()=>expect(sessionStorage.getItem(gameAPI.blackjackActionStorage('1'))).toBeNull());
    expect(screen.getByRole('button',{name:'Hit · 要牌'})).toBeEnabled();
    expect(screen.queryByRole('button',{name:/核对本次行动|重试原行动/})).not.toBeInTheDocument();
    expect(request.mock.calls.filter(c=>c[1]==='POST')).toHaveLength(1);

});
it('publishes commitment before manual wager, locks double click, then displays durable result',async()=>{
    let resolve!:(value:GameRound)=>void;
    const create=vi.spyOn(gameAPI,'createGame').mockReturnValue(new Promise(r=>resolve=r));
    const view=show();await screen.findByText('可用筹码');expect(create).not.toHaveBeenCalled();
    expect(await screen.findByRole('img',{name:'星月骰盅，仅在首次开局前展示'})).toBeVisible();
    expect(screen.queryByText(hash)).not.toBeInTheDocument();
    expect(screen.queryByRole('heading',{name:'规则与奖励'})).not.toBeInTheDocument();
    const rulesButton=screen.getByRole('button',{name:'规则与奖励'});rulesButton.focus();fireEvent.click(rulesButton);
    expect(screen.getByRole('heading',{name:'规则与奖励'})).toBeVisible();
    expect(screen.queryByText('理论返还率')).not.toBeInTheDocument();
    fireEvent.click(screen.getByRole('button',{name:'关闭对话框'}));
    expect(rulesButton).toHaveFocus();
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument();
    fireEvent.click(screen.getByRole('button',{name:'公平验证'}));
    expect(within(screen.getByRole('dialog',{name:'公平验证'})).getByText(hash)).toBeVisible();
    expect(screen.queryByRole('button',{name:'验证本局'})).not.toBeInTheDocument();
    fireEvent.click(screen.getByRole('button',{name:'关闭对话框'}));
    fireEvent.click(screen.getByRole('radio',{name:/小/}));
    fireEvent.click(screen.getByRole('button',{name:'掷骰'}));
    expect(screen.queryByRole('img',{name:'星月骰盅，仅在首次开局前展示'})).not.toBeInTheDocument();
    expect(screen.getByLabelText('三颗骰子正在翻滚，等待落定')).toHaveClass('is-rolling');
    expect(create).toHaveBeenCalledTimes(1);
    expect(screen.getByLabelText('基础下注（筹码）')).toBeDisabled();
    expect(create.mock.calls[0][2].input).toEqual({type:'DICE',wager:'10',choice:'SMALL'});
    vi.mocked(gameAPI.readGameBootstrap).mockResolvedValue({...bootstrap,latest_round:result,available_units:result.balance_after_units});
    resolve(result);
    await waitFor(()=>expect(screen.getByRole('button',{name:'落定中…'})).toBeDisabled());
    expect(screen.queryByLabelText('本局结果')).not.toBeInTheDocument();
    await waitFor(()=>expect(screen.getByLabelText('本局结果')).toHaveTextContent('净赢'),{timeout:2500});
    expect(screen.getByLabelText('骰子点数 2、3、4，合计 9 点')).not.toHaveClass('is-rolling');
    expect(within(screen.getByLabelText('本局结果')).getByText('+10')).toBeVisible();
    expect(create).toHaveBeenCalledTimes(1);expect(sessionStorage.getItem(gameAPI.pendingStorage('1','dice'))).toBeNull();
    view.unmount();show();
    await screen.findByLabelText('骰子点数 2、3、4，合计 9 点');
    expect(screen.queryByRole('img',{name:'星月骰盅，仅在首次开局前展示'})).not.toBeInTheDocument();
    vi.stubGlobal('matchMedia',vi.fn(()=>({matches:true})));
    try {
        fireEvent.click(screen.getByRole('button',{name:'掷骰'}));
        await waitFor(()=>expect(screen.getByRole('button',{name:'掷骰'})).toBeEnabled());
        expect(create).toHaveBeenCalledTimes(2);
        expect(screen.getByLabelText('骰子点数 2、3、4，合计 9 点')).not.toHaveClass('is-rolling');
        expect(screen.queryByRole('img',{name:'星月骰盅，仅在首次开局前展示'})).not.toBeInTheDocument();
    } finally { vi.unstubAllGlobals(); }
    cleanup();
    const capped:GameRound={...result,balance_after_units:'502500000',economic_policy_version:'economy-cap-v1',economy_settlement:{policy_version:'economy-cap-v1',policy_hash:hash,gross_payout_units:'10000000',credited_payout_units:'7500000',withheld_units:'2500000',actual_net_units:'2500000'}};
    expect(()=>gameAPI.parseRound(capped)).not.toThrow();
    expect(()=>gameAPI.parseRound({...capped,economy_settlement:{...capped.economy_settlement,credited_payout_units:'1'}})).toThrow();
    render(<MemoryRouter><RoundReceipt round={capped}/></MemoryRouter>);
    for(const label of ['原规则派彩','实际到账','封顶未入账'])expect(screen.getByText(label)).toBeVisible();
    expect(screen.getByLabelText('经济结算回执')).toHaveTextContent('20');expect(screen.getByLabelText('经济结算回执')).toHaveTextContent('15');expect(screen.getByLabelText('经济结算回执')).toHaveTextContent('5');
});
it('unknown HTTP outcome reconciles automatically, survives refresh and never repeats the POST',async()=>{
    const create=vi.spyOn(gameAPI,'createGame').mockRejectedValue(new ApiError('lost response',0,'',true));
    let recover!:(value:GameRound)=>void;
    const find=vi.spyOn(gameAPI,'findPendingGame').mockRejectedValueOnce(new ApiError('offline',0,'',true)).mockImplementationOnce(()=>new Promise(resolve=>{recover=resolve})).mockResolvedValue(result);
    const first=show();await screen.findByRole('button',{name:'掷骰'});
    vi.useFakeTimers();
    try {
        fireEvent.click(screen.getByRole('radio',{name:/^大/}));
        await act(async()=>{fireEvent.click(screen.getByRole('button',{name:'掷骰'}));});
        const stored=sessionStorage.getItem(gameAPI.pendingStorage('1','dice'))!;
        expect(stored).toContain('commitment');
        expect(screen.queryByText('有一笔下注等待核对，新下注已暂停。')).not.toBeInTheDocument();
        expect(screen.queryByRole('button',{name:/核对本局|使用原请求重试/})).not.toBeInTheDocument();
        expect(screen.getByLabelText('基础下注（筹码）')).toBeDisabled();
        await act(async()=>{await vi.advanceTimersByTimeAsync(1000);});
        expect(find).toHaveBeenCalledTimes(1);
        expect(sessionStorage.getItem(gameAPI.pendingStorage('1','dice'))).toBe(stored);
        await act(async()=>{await vi.advanceTimersByTimeAsync(1999);});
        expect(find).toHaveBeenCalledTimes(1);
        await act(async()=>{fireEvent(window,new Event('online'));});
        expect(find).toHaveBeenCalledTimes(2);
        await act(async()=>{await vi.advanceTimersByTimeAsync(30000);});
        expect(find).toHaveBeenCalledTimes(2); // No overlapping recovery reads.
        expect(find.mock.calls.every(call=>call[2]===JSON.parse(stored).key)).toBe(true);
        vi.mocked(gameAPI.readGameBootstrap).mockResolvedValue({...bootstrap,latest_round:result});
        await act(async()=>{recover(result);});
        expect(screen.getByLabelText('本局结果')).toHaveTextContent('净赢');
        expect(sessionStorage.getItem(gameAPI.pendingStorage('1','dice'))).toBeNull();
        expect(create).toHaveBeenCalledTimes(1);
        first.unmount();
        sessionStorage.setItem(gameAPI.pendingStorage('1','dice'),stored);
        let restored!:ReturnType<typeof show>;
        await act(async()=>{restored=show();});
        expect(find).toHaveBeenCalledTimes(3);
        expect(sessionStorage.getItem(gameAPI.pendingStorage('1','dice'))).toBeNull();
        restored.unmount();
        // The server's by-key read shares the create lock: null definitively means not accepted,
        // even if another tab has since rotated the commitment. Never resubmit the old wager.
        sessionStorage.setItem(gameAPI.pendingStorage('1','dice'),stored);
        find.mockResolvedValue(null);
        vi.mocked(gameAPI.readGameBootstrap).mockResolvedValue({...bootstrap,next_commitment:{...bootstrap.next_commitment!,id}});
        await act(async()=>{restored=show();});
        expect(sessionStorage.getItem(gameAPI.pendingStorage('1','dice'))).toBeNull();
        expect(screen.getByRole('button',{name:'掷骰'})).toBeEnabled();
        expect(within(screen.getByLabelText('下注控制台')).getByText('本次操作未受理，没有新增扣款。')).toBeVisible();
        expect(screen.queryByRole('alert')).not.toBeInTheDocument();
        expect(create).toHaveBeenCalledTimes(1);
        restored.unmount();
        await act(async()=>{await vi.advanceTimersByTimeAsync(60000);});
        expect(find).toHaveBeenCalledTimes(4);
    } finally {vi.useRealTimers();}
});
it('unlocks an unaccepted pending blackjack deal when bootstrap still owns its commitment',async()=>{
    const pending={key:'01993200-0000-7000-8000-000000000003',commitment,input:{type:'BLACKJACK' as const,initial_wager:'100'}};
    sessionStorage.setItem(gameAPI.pendingStorage('1','blackjack'),JSON.stringify(pending));
    vi.spyOn(gameAPI,'findPendingGame').mockResolvedValue(null);
    vi.mocked(gameAPI.readGameBootstrap).mockResolvedValue({...bootstrap,game:{...bootstrap.game,slug:'blackjack',config:undefined},available_units:'200000000'});
    render(<MemoryRouter><GamePage client={client} userID="1" slug="blackjack"/></MemoryRouter>);
    await waitFor(()=>expect(sessionStorage.getItem(gameAPI.pendingStorage('1','blackjack'))).toBeNull());
    expect(screen.getByRole('button',{name:'Deal · 100 筹码'})).toBeEnabled();
    expect(screen.getByText('服务器确认原下注未受理，已解除锁定。')).toBeVisible();
});
it('refuses invalid or unaffordable wagers without calling create while keeping a settled blackjack wager editable',async()=>{
    expect(gameAPI.wagerCost('35467687124','SINGLE','slot')).not.toBeNull();
    expect(gameAPI.wagerCost('35467687125','SINGLE','slot')).toBeNull();
    const create=vi.spyOn(gameAPI,'createGame');const dice=show();await screen.findByRole('button',{name:'掷骰'});
    for(const value of ['9','10.5','-10','1e2','1001']) {
        fireEvent.change(screen.getByLabelText('基础下注（筹码）'),{target:{value}});
        expect(screen.getByRole('button',{name:'掷骰'})).toBeDisabled();
    }
    dice.unmount();
    const settled={...result,game:'blackjack',input:{type:'BLACKJACK',initial_wager:'500'},total_stake_units:'250000000',total_payout_units:'0',net_change_units:'-250000000',common_result:'LOSS',balance_before_units:'300000000',balance_after_units:'50000000',dice:undefined,blackjack:{phase:'SETTLED',round_version:'2',active_hand_id:'',hands:[{hand_id:id,hand_index:0,cards:[7,20],stake_units:'250000000',hand_state:'BUST',value:{hard_total:26,best_total:26,is_soft:false},is_natural:false,result:'BUST',payout_units:'0',net_change_units:'-250000000'}],dealer_cards:[4,5],dealer_revealed:true,dealer_total:{hard_total:11,best_total:21,is_soft:true},legal_actions:[],last_player_action_at:'2026-09-06T10:00:00Z',auto_resolve_at:'2026-09-07T10:00:00Z',total_stake_units:'250000000',total_payout_units:'0',net_change_units:'-250000000',result_class:'LOSS'}} as GameRound;
    vi.mocked(gameAPI.readGameBootstrap).mockResolvedValue({...bootstrap,game:{...bootstrap.game,slug:'blackjack',config:undefined},available_units:'50000000',latest_round:settled});
    render(<MemoryRouter><GamePage client={client} userID="1" slug="blackjack"/></MemoryRouter>);
    const input=await screen.findByLabelText('初始下注 · 筹码');
    await waitFor(()=>expect(input).toHaveValue('500'));
    expect(input).toBeEnabled();expect(screen.getByRole('button',{name:'Deal · 500 筹码'})).toBeDisabled();
    fireEvent.change(input,{target:{value:'9'}});
    expect(input).toBeEnabled();expect(screen.getByRole('button',{name:'Deal · — 筹码'})).toBeDisabled();
    fireEvent.change(input,{target:{value:'100'}});
    expect(input).toBeEnabled();expect(screen.getByRole('button',{name:'Deal · 100 筹码'})).toBeEnabled();
    expect(create).not.toHaveBeenCalled();
});
it('keeps the pre-purchase scratch balance visible until reveal completes',async()=>{
    vi.spyOn(HTMLCanvasElement.prototype,'getContext').mockReturnValue(null);
    const scratch={...result,game:'scratch',input:{type:'SCRATCH',wager:'100'},total_stake_units:'50000000',total_payout_units:'0',net_change_units:'-50000000',common_result:'LOSS',balance_before_units:'500000000',balance_after_units:'450000000',dice:undefined,scratch:{tier:'LOSS',cells:Array.from({length:9},()=>({symbol:'P1',matching:false})),reward:{cost_multiplier:'1',payout_multiplier:'0',outcome:'LOSS'}}} as GameRound;
    const completed={...scratch,presentation_completed_at:'2026-09-06T10:01:00Z'};
    vi.mocked(gameAPI.readGameBootstrap).mockResolvedValueOnce({...bootstrap,game:{...bootstrap.game,slug:'scratch',config:undefined},available_units:'450000000',latest_round:scratch,scratch_presentation_blocker:scratch,effective_entry_action:'RESUME',next_commitment:null}).mockResolvedValue({...bootstrap,game:{...bootstrap.game,slug:'scratch',config:undefined},available_units:'450000000',latest_round:completed});
    vi.spyOn(client,'request').mockResolvedValue(completed);
    render(<MemoryRouter><GamePage client={client} userID="1" slug="scratch"/></MemoryRouter>);
    const balance=()=>screen.getByText('可用筹码').parentElement!;
    await waitFor(()=>expect(within(balance()).getByText('1,000')).toBeVisible());
    expect(within(balance()).queryByText('900')).not.toBeInTheDocument();
    expect(screen.getByRole('img',{name:'未揭晓涂层'})).toBeVisible();
    expect(screen.queryByRole('img',{name:'赤铜果实'})).not.toBeInTheDocument();
    expect(screen.getByRole('button',{name:'购买刮刮卡'})).toBeDisabled();
    expect(screen.queryByLabelText('本局结果')).not.toBeInTheDocument();
    fireEvent.click(screen.getByRole('button',{name:'公平验证'}));
    expect(screen.getByRole('dialog',{name:'公平验证'})).toBeVisible();
    expect(screen.queryByRole('heading',{name:'复算本局'})).not.toBeInTheDocument();
    expect(screen.queryByRole('button',{name:'验证本局'})).not.toBeInTheDocument();
    expect(within(screen.getByRole('dialog')).queryByText(/900/)).not.toBeInTheDocument();
    fireEvent.click(screen.getByRole('button',{name:'关闭对话框'}));
    fireEvent.click(screen.getByRole('button',{name:'立即揭晓'}));
    await waitFor(()=>expect(within(balance()).getByText('900')).toBeVisible());
    expect(screen.getAllByRole('img',{name:'赤铜果实'})).toHaveLength(9);
    expect(screen.queryByRole('img',{name:'未揭晓涂层'})).not.toBeInTheDocument();
    expect(client.request).toHaveBeenCalledWith(`/api/v1/game-rounds/${id}/actions`,'POST',expect.objectContaining({action_type:'SCRATCH_REVEAL_COMPLETE'}),{'X-CSRF-Token':hash});
    expect(screen.getByRole('button',{name:'购买刮刮卡'})).toBeEnabled();
    fireEvent.click(screen.getByRole('button',{name:'公平验证'}));
    expect(screen.getByRole('button',{name:'验证本局'})).toBeEnabled();
    fireEvent.click(screen.getByRole('button',{name:'关闭对话框'}));
});
it('disables each quick amount by its total cost, including tenfold',async()=>{
    const summonBoot={...bootstrap,game:{...bootstrap.game,slug:'summon',config:{...bootstrap.game.config!,prizes:[{tier:'T0',multiplier:0,weight:50000},{tier:'T5',multiplier:100,weight:50000}]}},available_units:'1500000000'};
    vi.mocked(gameAPI.readGameBootstrap).mockResolvedValue(summonBoot);
    const view=render(<MemoryRouter><GamePage client={client} userID="1" slug="summon"/></MemoryRouter>);
    await screen.findByLabelText('基础下注（筹码）');
    await waitFor(()=>expect(screen.getByRole('button',{name:'1000'})).toBeEnabled());
    fireEvent.click(screen.getByRole('radio',{name:'十连召唤 · 10 抽'}));
    expect(screen.getByRole('button',{name:'100'})).toBeEnabled();
    expect(screen.getByRole('button',{name:'500'})).toBeDisabled();
    expect(screen.getByRole('button',{name:'1000'})).toBeDisabled();
    expect(screen.queryByRole('table',{name:'完整奖励表'})).not.toBeInTheDocument();
    fireEvent.click(screen.getByRole('button',{name:'规则与奖励'}));
    const rewards=within(screen.getByRole('dialog')).getByRole('table',{name:'完整奖励表'});
    expect(within(rewards).getAllByRole('columnheader').map(cell=>cell.textContent)).toEqual(['等级','总派彩倍数']);
    expect(within(rewards).getByRole('row',{name:'T5 ×100'})).toBeVisible();
    expect(within(screen.getByRole('dialog')).getByText('固定卡面 · 0—5 星')).toBeVisible();
    fireEvent.click(screen.getByRole('button',{name:'关闭对话框'}));
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument();
    expect(screen.getByRole('img',{name:'待召唤的灵基卡背'})).toBeVisible();
    expect(screen.queryByRole('img',{name:'阿尔托莉雅·卡斯特'})).not.toBeInTheDocument();
    // Reuse the existing round and this case's prize values; art must not select a result.
    const create=vi.spyOn(gameAPI,'createGame').mockImplementation(async(_client,_slug,request)=>{
        const next={...result,game:'summon',dice:undefined,input:request.input,summon:{mode:'TENFOLD',highest_tier:'T5',draws:Array.from({length:10},(_,i)=>({index:i+1,tier:summonBoot.game.config.prizes[i%2].tier,multiplier:String(summonBoot.game.config.prizes[i%2].multiplier)}))}} as GameRound;
        vi.mocked(gameAPI.readGameBootstrap).mockResolvedValue({...summonBoot,latest_round:next});
        return next;
    });
    fireEvent.click(screen.getByRole('button',{name:'十连召唤 · 100 筹码'}));
    const skip=await screen.findByRole('button',{name:'全部揭晓 · 跳过演出'});
    expect(screen.queryByRole('img',{name:'阿尔托莉雅·卡斯特'})).not.toBeInTheDocument();
    fireEvent.click(skip);
    const cards=within(screen.getByRole('list',{name:'本轮召唤结果'})).getAllByRole('listitem');
    expect(cards).toHaveLength(10);
    for(let i=0;i<cards.length;i++){
        expect(cards[i]).toHaveTextContent(`第 ${i+1} 抽`);
        expect(within(cards[i]).getByRole('img',{name:i%2?'阿尔托莉雅·卡斯特':'安哥拉曼纽'})).toBeVisible();
        expect(within(cards[i]).getByLabelText(i%2?'5 星':'0 星')).toBeVisible();
        expect(cards[i]).toHaveTextContent(i%2?'×100':'×0');
    }
    expect(create).toHaveBeenCalledTimes(1);
    expect(create.mock.calls[0][2].input).toEqual({type:'SUMMON',base_wager:'10',mode:'TENFOLD'});
    expect(screen.getByRole('list',{name:'本轮召唤结果'})).toHaveClass('is-complete');
    expect(screen.getByText('本轮 10 抽已揭晓 · 倍率以本局结果为准。')).toHaveFocus();
    fireEvent.error(within(cards[1]).getByRole('img',{name:'阿尔托莉雅·卡斯特'}));
    expect(cards[1]).toHaveTextContent('阿尔托莉雅·卡斯特');
    expect(cards[1]).toHaveTextContent('T5');
    expect(cards[1]).toHaveTextContent('×100');
    const refresh=screen.getByRole('button',{name:'刷新恢复'});
    fireEvent.click(refresh);
    await waitFor(()=>expect(refresh).toBeEnabled());
    expect(screen.getByRole('list',{name:'本轮召唤结果'})).toHaveClass('is-complete');
    expect(screen.queryByRole('button',{name:'全部揭晓 · 跳过演出'})).not.toBeInTheDocument();
    expect(create).toHaveBeenCalledTimes(1);
    view.unmount();
    const restored=render(<MemoryRouter><GamePage client={client} userID="1" slug="summon"/></MemoryRouter>);
    expect(await screen.findByRole('list',{name:'本轮召唤结果'})).toHaveClass('is-complete');
    expect(screen.queryByRole('button',{name:'全部揭晓 · 跳过演出'})).not.toBeInTheDocument();
    restored.unmount();vi.mocked(gameAPI.readGameBootstrap).mockResolvedValue(summonBoot);
    vi.stubGlobal('matchMedia',vi.fn(()=>({matches:true})));
    try {
        render(<MemoryRouter><GamePage client={client} userID="1" slug="summon"/></MemoryRouter>);
        await screen.findByRole('img',{name:'待召唤的灵基卡背'});
        fireEvent.click(screen.getByRole('radio',{name:'十连召唤 · 10 抽'}));
        fireEvent.click(screen.getByRole('button',{name:'十连召唤 · 100 筹码'}));
        await waitFor(()=>expect(screen.getByRole('list',{name:'本轮召唤结果'})).toHaveClass('is-complete'));
        expect(screen.queryByRole('button',{name:'全部揭晓 · 跳过演出'})).not.toBeInTheDocument();
    } finally {vi.unstubAllGlobals();}
});
it('restores last durable wager on first entry without overwriting a live edit',async()=>{
    vi.mocked(gameAPI.readGameBootstrap).mockResolvedValue({...bootstrap,latest_round:{...result,input:{type:'DICE',wager:'100',choice:'SMALL'}}});
    show();await waitFor(()=>expect(screen.getByLabelText('基础下注（筹码）')).toHaveValue('100'));
    expect(screen.getByRole('radio',{name:/小/})).toBeChecked();
    fireEvent.change(screen.getByLabelText('基础下注（筹码）'),{target:{value:'50'}});
    fireEvent.click(screen.getByRole('button',{name:'刷新恢复'}));
    await waitFor(()=>expect(gameAPI.readGameBootstrap).toHaveBeenCalledTimes(2));
    expect(screen.getByLabelText('基础下注（筹码）')).toHaveValue('50');
});
