import { render, screen, waitFor, fireEvent, act } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import { expect, it, vi } from 'vitest';
import { App } from './App';
import { failed, fixtureClient } from './m1-test-fixtures';

const { mountGuangxi } = vi.hoisted(() => ({ mountGuangxi: vi.fn() }));
vi.mock('./guangxi-runtime', () => ({ mountGuangxi }));

it('keeps guangxi movable, persistent and non-blocking across lifecycle changes', async () => {
    // Only the WebGL boundary is mocked; these assertions exercise the real Home/component.
    const key = 'guangxi-mascot:v1';
    const media = new EventTarget();
    let reduced = false;
    Object.defineProperty(media, 'matches', { get: () => reduced });
    vi.stubGlobal('matchMedia', () => media);
    vi.stubGlobal('innerWidth', 1200);
    vi.stubGlobal('innerHeight', 800);
    vi.stubGlobal('requestIdleCallback', undefined);
    vi.stubGlobal('PointerEvent', class extends MouseEvent {
        pointerId: number; isPrimary = true;
        constructor(type: string, init: PointerEventInit) { super(type, init); this.pointerId = init.pointerId ?? 1; }
    });
    const visibility = vi.spyOn(document, 'visibilityState', 'get').mockReturnValue('visible');
    const readyState = vi.spyOn(document, 'readyState', 'get').mockReturnValue('complete');
    const instances: { setActive: ReturnType<typeof vi.fn>; resize: ReturnType<typeof vi.fn>; dispose: ReturnType<typeof vi.fn> }[] = [];
    mountGuangxi.mockImplementation(async () => {
        const instance = { setActive: vi.fn(), resize: vi.fn(), dispose: vi.fn() };
        instances.push(instance);
        return instance;
    });
    const { client } = fixtureClient(() => new Promise<Response>(() => {}));
    const open = () => render(<MemoryRouter initialEntries={['/']}><App client={client} /></MemoryRouter>);
    const handle = () => screen.getByRole('button', { name: '拖动广喜娘' });
    const widget = () => screen.getByLabelText('广喜娘');
    const stored = () => JSON.parse(localStorage.getItem(key)!);
    const idle = async () => { await act(async () => { await vi.advanceTimersByTimeAsync(300); }); };
    const drag = (x: number, y: number, cancel = false) => {
        const button = handle();
        button.setPointerCapture = vi.fn();
        button.hasPointerCapture = () => true;
        button.releasePointerCapture = vi.fn();
        fireEvent.pointerDown(button, { pointerId: 1, button: 0, clientX: 50, clientY: 50 });
        fireEvent.pointerMove(button, { pointerId: 1, clientX: 50 + x, clientY: 50 + y });
        fireEvent(button, new PointerEvent(cancel ? 'pointercancel' : 'pointerup', { bubbles: true, pointerId: 1 }));
    };
    let view: ReturnType<typeof render> | undefined;
    localStorage.removeItem(key);
    vi.useFakeTimers();
    try {
        view = open();
        expect(handle()).toBeVisible();
        expect(widget()).toHaveStyle({ left: '16px', bottom: '16px' });
        expect(screen.getByRole('heading', { level: 1 })).toHaveTextContent('在月光下');
        expect(screen.getByRole('link', { name: 'Discord 登录' })).toHaveAttribute('href', '/sign-in');
        await idle();
        expect(mountGuangxi).toHaveBeenCalledTimes(1);
        drag(100, -50);
        expect(stored()).toEqual({ version: 1, collapsed: false, position: { left: 116, bottom: 66 } });
        view.unmount();
        expect(instances[0].dispose).toHaveBeenCalledTimes(1);
        view = open();
        expect(widget()).toHaveStyle({ left: '116px', bottom: '66px' });
        drag(9999, -9999);
        expect(stored().position).toEqual({ left: 984, bottom: 436 });
        vi.stubGlobal('innerWidth', 320);
        vi.stubGlobal('innerHeight', 480);
        fireEvent(window, new Event('resize'));
        expect(stored().position).toEqual({ left: 104, bottom: 116 });
        vi.stubGlobal('innerWidth', 1200);
        vi.stubGlobal('innerHeight', 800);
        fireEvent(window, new Event('resize'));
        fireEvent.click(screen.getByRole('button', { name: '恢复左下角' }));
        expect(stored().position).toBeNull();
        fireEvent.keyDown(handle(), { key: 'ArrowRight' });
        fireEvent.keyDown(handle(), { key: 'ArrowUp', shiftKey: true });
        expect(stored().position).toEqual({ left: 26, bottom: 56 });
        drag(10, 0, true);
        fireEvent.pointerMove(handle(), { pointerId: 1, clientX: 900, clientY: 900 });
        expect(widget()).toHaveStyle({ left: '36px', bottom: '56px' });
        const storageFailure = vi.spyOn(Storage.prototype, 'setItem').mockImplementation(() => { throw new Error('storage disabled'); });
        fireEvent.click(screen.getByRole('button', { name: '收起广喜娘' }));
        expect(screen.getByRole('button', { name: '展开广喜娘' })).toBeVisible();
        fireEvent.click(screen.getByRole('button', { name: '展开广喜娘' }));
        storageFailure.mockRestore();
        await idle();
        const current = instances.at(-1)!;
        visibility.mockReturnValue('hidden');
        fireEvent(document, new Event('visibilitychange'));
        expect(current.setActive).toHaveBeenLastCalledWith(false);
        visibility.mockReturnValue('visible');
        fireEvent(document, new Event('visibilitychange'));
        expect(current.setActive).toHaveBeenLastCalledWith(true);
        reduced = true;
        act(() => media.dispatchEvent(new Event('change')));
        expect(current.setActive).toHaveBeenLastCalledWith(false);
        expect(widget()).toHaveAttribute('data-mode', 'static');
        view.unmount();
        localStorage.setItem(key, '{broken');
        view = open();
        expect(widget()).toHaveStyle({ left: '16px', bottom: '16px' });
        const callsBefore = mountGuangxi.mock.calls.length;
        await idle();
        expect(mountGuangxi).toHaveBeenCalledTimes(callsBefore);
        view.unmount();
        reduced = false;
        localStorage.removeItem(key);
        vi.stubGlobal('innerWidth', 390);
        view = open();
        expect(screen.getByRole('button', { name: '展开广喜娘' })).toBeVisible();
        await idle();
        expect(mountGuangxi).toHaveBeenCalledTimes(callsBefore);
        let finish!: (value: typeof current) => void;
        mountGuangxi.mockReturnValueOnce(new Promise(resolve => { finish = resolve; }));
        fireEvent.click(screen.getByRole('button', { name: '展开广喜娘' }));
        await idle();
        const pendingSignal = mountGuangxi.mock.calls.at(-1)![1] as AbortSignal;
        view.unmount();
        expect(pendingSignal.aborted).toBe(true);
        const late = { setActive: vi.fn(), resize: vi.fn(), dispose: vi.fn() };
        await act(async () => finish(late));
        expect(late.dispose).toHaveBeenCalledTimes(1);
        mountGuangxi.mockRejectedValueOnce(new Error('WebGL failed'));
        view = open();
        await idle();
        expect(widget()).toHaveAttribute('data-mode', 'failed');
        expect(handle()).toBeVisible();
        expect(screen.getByRole('heading', { level: 1 })).toHaveTextContent('在月光下');
        expect(screen.getByRole('link', { name: 'Discord 登录' })).toBeVisible();
        fireEvent.error(view.container.querySelector('.guangxi-art img')!);
        expect(handle()).toBeVisible();
        view.unmount();
        mountGuangxi.mockReturnValueOnce(new Promise(() => {}));
        view = open();
        await idle();
        const timedOutSignal = mountGuangxi.mock.calls.at(-1)![1] as AbortSignal;
        await act(async () => { await vi.advanceTimersByTimeAsync(15_000); });
        expect(timedOutSignal.aborted).toBe(true);
        expect(widget()).toHaveAttribute('data-mode', 'failed');
        fireEvent.click(screen.getByRole('button', { name: '收起广喜娘' }));
        expect(screen.getByRole('button', { name: '展开广喜娘' })).toBeVisible();
    } finally {
        view?.unmount();
        localStorage.removeItem(key);
        vi.useRealTimers();
        vi.unstubAllGlobals();
        visibility.mockRestore();
        readyState.mockRestore();
        mountGuangxi.mockReset();
    }
});

it('renders the public home immediately while session bootstrap is unresolved', () => {
    const { client } = fixtureClient(() => new Promise<Response>(() => {}));
    render(<MemoryRouter initialEntries={['/']}><App client={client} /></MemoryRouter>);
    expect(screen.getByRole('heading', { level: 1 })).toHaveTextContent('在月光下');
    expect(screen.getByRole('link', { name: 'Discord 登录' })).toHaveAttribute('href', '/sign-in');
    expect(screen.queryByText('从这里，走向你的下一站')).not.toBeInTheDocument();
});
it.each(['guest', 'failure'])('keeps / public after %s session verification', async state => {
    const { client, fetcher } = fixtureClient(() => state === 'guest' ? new Response(JSON.stringify({ success: false }), { status: 401 }) : failed());
    render(<MemoryRouter initialEntries={['/']}><App client={client} /></MemoryRouter>);
    await waitFor(() => expect(client.getSnapshot().ready).toBe(true));
    expect(screen.getByRole('heading', { level: 1 })).toHaveTextContent('在月光下');
    expect(fetcher.mock.calls.map(c => c[0])).toEqual(['/api/user/auth/refresh']);
    expect(screen.queryByLabelText('密码')).not.toBeInTheDocument();
});
it('enhances the same home for a signed-in user without loading personal business data', async () => {
    const { client, fetcher } = fixtureClient();
    render(<MemoryRouter initialEntries={['/']}><App client={client} /></MemoryRouter>);
    expect(await screen.findByRole('link', { name: '返回指挥台' })).toHaveAttribute('href', '/dashboard');
    expect(screen.getByRole('heading', { level: 1 })).toHaveTextContent('在月光下');
    expect(fetcher.mock.calls.every(c => c[0].startsWith('/api/user/'))).toBe(true);
    expect(screen.queryByText(/今日已领取|今日待领取|在线人数|热门榜|服务正常/)).not.toBeInTheDocument();
    expect(screen.queryByRole('link', {name:/探索娱乐沙龙/})).not.toBeInTheDocument();
    expect(screen.queryByRole('link', {name:'Discord 登录'})).not.toBeInTheDocument();
});
it('keeps the hero content usable if the decorative image fails', async () => {
    const { client } = fixtureClient(() => failed());
    const view = render(<MemoryRouter initialEntries={['/']}><App client={client} /></MemoryRouter>);
    const art = view.container.querySelector('img');
    expect(art).not.toBeNull();
    fireEvent.error(art!);
    expect(screen.getByRole('heading', { level: 1 })).toHaveTextContent('在月光下');
    expect(screen.getByRole('link', { name: 'Discord 登录' })).toBeVisible();
});
it('opens the reviewed public catalog to guests without native group or model reads', async () => {
    const { client, fetcher } = fixtureClient(() => new Response(JSON.stringify({ success: false }), { status: 401 }));
    render(<MemoryRouter initialEntries={['/models']}><App client={client} /></MemoryRouter>);
    await waitFor(() => expect(client.getSnapshot().ready).toBe(true));
    expect(screen.getByRole('heading', { level: 1 })).toHaveTextContent('模型工房');
    expect(fetcher.mock.calls.some(c => c[0] === '/platform/v1/models?group_by=family')).toBe(true);
    expect(fetcher.mock.calls.some(c => c[0].includes('/api/user/models') || c[0].endsWith('/groups'))).toBe(false);
    expect(screen.queryByLabelText('密码')).not.toBeInTheDocument();
});
