import { useEffect, useRef, useState, type FormEvent } from 'react';
import { Link } from 'react-router-dom';
import { ApiClient, ApiError } from './api';
import { Alert, Brand, Empty, Modal, useResource } from './ui';
import { announcementError, announcementOps, announcementStates, announcementTime, announcementTypes, placementLabels, type Acknowledgement, type AnnouncementCommand, type AnnouncementContent, type AnnouncementPreview, type AnnouncementPrincipal, type AnnouncementResult, type OpsAnnouncement, type Placement } from './announcement-api';
import './announcements.css';

const emptyContent = (): AnnouncementContent => ({ title: '', type: 'SYSTEM', visibility: 'PUBLIC', body_markdown: '', acknowledgements: [] });
const localTime = (iso?: string | null) => new Date(new Date(iso || Date.now()).getTime() + 8 * 3600000).toISOString().slice(0, 19);
const utcTime = (value: string) => { const date = new Date(value + '+08:00'); if (!value || !Number.isFinite(date.getTime())) throw new Error('请填写有效的上海时间。'); return date.toISOString(); };
const actionLabels: Record<string, string> = { PUBLISH: '立即发布', SCHEDULE: '预约发布', WITHDRAW: '撤回公告', ARCHIVE: '归档公告', RE_NOTIFY: '重新通知', UPDATE_CONTENT_ONLY: '更新正文', UPDATE_PLACEMENTS: '调整展示渠道' };
type Pending = { command: AnnouncementCommand; preview?: AnnouncementPreview; uncertain: boolean };
export function OpsAnnouncements({ client }: { client: ApiClient }) {
    const resource = useResource(() => client.request<{ principal: AnnouncementPrincipal; items: OpsAnnouncement[] }>(announcementOps).catch(e => { throw new Error(announcementError(e)); }), [client]);
    const [principal, setPrincipal] = useState<AnnouncementPrincipal | null>(null); const [item, setItem] = useState<OpsAnnouncement | null>(null); const [editing, setEditing] = useState(false);
    const [content, setContent] = useState<AnnouncementContent>(emptyContent); const [placements, setPlacements] = useState<Placement[]>([]); const [publishAt, setPublishAt] = useState(localTime); const [visibleFrom, setVisibleFrom] = useState(localTime); const [until, setUntil] = useState(''); const [reason, setReason] = useState('');
    const [html, setHTML] = useState(''); const [previewMode, setPreviewMode] = useState('desktop'); const [pending, setPending] = useState<Pending | null>(null); const [busy, setBusy] = useState(false); const lock = useRef(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
    const [unloadedResult, setUnloadedResult] = useState<AnnouncementResult | null>(null);
    useEffect(() => { document.title = '公告运营 · Chaldea Platform'; }, []);
    useEffect(() => { if (resource.data) setPrincipal(resource.data.principal); else if (resource.error) setPrincipal(null); }, [resource.data, resource.error]);
    const canWrite = !!principal?.permissions.includes('announcements.write'); const canPublish = !!principal?.permissions.includes('announcements.publish');
    function select(next: OpsAnnouncement | null) {
        setItem(next); setEditing(true); setContent(next ? structuredClone(next.content) : emptyContent()); setPlacements(next?.placements || []); setPublishAt(localTime(next?.publish_at)); setVisibleFrom(localTime(next?.visible_from)); setUntil(next?.visible_until ? localTime(next.visible_until) : ''); setReason(''); setHTML(next?.sanitized_html || ''); setError('');
    }
    async function loadItem(id: string) { const value = await client.request<{ principal: AnnouncementPrincipal; item: OpsAnnouncement }>(announcementOps + '/' + id); setPrincipal(value.principal); select(value.item); setUnloadedResult(null); }
    async function perform(run: () => Promise<void>) { if (lock.current) return; lock.current = true; setBusy(true); setError(''); setNotice(''); try { await run(); } catch (e) { setError(announcementError(e)); } finally { lock.current = false; setBusy(false); } }
    async function execute(next: Pending) {
        setPending(next);
        let result: AnnouncementResult;
        try {
            result = await client.request<AnnouncementResult>(announcementOps + '/execute', 'POST', { command: next.command, preview_id: next.preview?.preview_id || '', confirmed: !!next.preview });
            if (!result || !/^[0-9a-f-]{36}$/i.test(result.announcement_id) || !Number.isSafeInteger(result.version) || !result.operation_id) throw new ApiError('操作响应不完整，结果尚未确认。请使用同一操作编号重试。', 0, '', true);
        } catch (e) {
            if (e instanceof ApiError && e.uncertain) setPending({ ...next, uncertain: true }); else setPending(null);
            throw e;
        }
        // A confirmed write stays confirmed even when the following read is unavailable.
        setPending(null); setUnloadedResult(result); setNotice('操作已保存。编号：' + result.operation_id);
        try { await loadItem(result.announcement_id); resource.reload(); }
        catch (e) { setError('详情暂时无法刷新，请重新读取已保存公告。' + announcementError(e)); }
    }
    function command(action: string): AnnouncementCommand {
        if (!principal) throw new Error('请重新读取运营权限。');
        const c: AnnouncementCommand = { operation_id: crypto.randomUUID(), authz_epoch: principal.authz_epoch, announcement_id: item?.announcement_id || '', expected_version: item?.version || 0, action, reason: reason.trim() };
        if (action === 'SAVE' || action === 'UPDATE_CONTENT_ONLY') c.content = structuredClone(content);
        if (action === 'PUBLISH' || action === 'SCHEDULE') { c.publish_at = utcTime(publishAt); c.visible_from = utcTime(visibleFrom); if (until) c.visible_until = utcTime(until); c.placements = placements; }
        if (action === 'UPDATE_PLACEMENTS') c.placements = placements;
        return c;
    }
    function act(action: string) { void perform(async () => { const c = command(action); if (action === 'SAVE') await execute({ command: c, uncertain: false }); else { const preview = await client.request<AnnouncementPreview>(announcementOps + '/prepare', 'POST', { command: c }); setPending({ command: c, preview, uncertain: false }); } }); }
    function save(event: FormEvent) { event.preventDefault(); act(item && item.state !== 'DRAFT' ? 'UPDATE_CONTENT_ONLY' : 'SAVE'); }
    function patchContent(patch: Partial<AnnouncementContent>) { setContent(c => ({ ...c, ...patch })); setHTML(''); }
    function updateAck(index: number, patch: Partial<Acknowledgement>) { patchContent({ acknowledgements: content.acknowledgements.map((entry, i) => i === index ? { ...entry, ...patch } : entry) }); }
    function changeType(type: AnnouncementContent['type']) { patchContent({ type, acknowledgements: type === 'ACKNOWLEDGEMENTS' ? content.acknowledgements : [] }); if (!item && type === 'ACKNOWLEDGEMENTS') setPlacements([{ placement: 'PINNED_LIST', manual_order: 0 }, { placement: 'ENTRY_POPUP', manual_order: 0 }]); }
    return <div className='announcement-ops'><a href='#ops-content' className='skip-link'>跳至运营内容</a><aside className='announcement-ops-sidebar'><Link to='/' className='brand'><Brand /></Link><p className='eyebrow'>OPERATIONS</p><Link to='/ops/announcements' aria-current='page'>公告管理</Link><Link to='/announcements'>查看公共公告 ↗</Link></aside><div className='announcement-ops-workspace'><header className='announcement-ops-top'><span>站点 · {location.host}</span><Link to='/'>返回用户站点</Link><span>{principal ? `${principal.base_role} · ${principal.user_id}` : '核验运营权限'}</span></header><main id='ops-content' tabIndex={-1}><header className='page-heading'><div><p className='eyebrow'>CONTENT / ANNOUNCEMENTS</p><h1>公告运营</h1><p>草拟内容，核对展示范围，然后发布。</p></div><div className='announcement-actions'><button disabled={busy || !!pending || !!unloadedResult} onClick={resource.reload}>刷新权限与列表</button>{canWrite && <button className='primary' disabled={busy || !!pending || !!unloadedResult} onClick={() => select(null)}>新建公告</button>}</div></header>
        {resource.loading && <p role='status'>正在读取公告运营数据…</p>}{resource.error && <Alert>{resource.error}</Alert>}{error && <Alert>{error}</Alert>}{notice && <p role='status' className='announcement-operation-receipt'>{notice}</p>}
        {pending?.uncertain && <Alert>操作结果尚未确认。请保留此页，使用同一编号核对结果。<code>{pending.command.operation_id}</code><button disabled={busy} onClick={() => void perform(() => execute(pending))}>重试同一操作</button></Alert>}
        {unloadedResult && <div className='announcement-confirmed-read' role='status'><p>写入已确认，公告编号：{unloadedResult.announcement_id}。详情暂未读取。</p><button disabled={busy} onClick={() => void perform(() => loadItem(unloadedResult.announcement_id))}>重新读取已保存公告</button></div>}
        {resource.data && <section className='announcement-ops-list' aria-label='公告运营列表'><div className='announcement-ops-list-heading'><h2>公告状态</h2><span className='hint'>最近更新的 100 条</span></div>{resource.data.items.length ? <div className='table-scroll' role='region' aria-label='公告状态表格，可横向滚动' tabIndex={0}><table><thead><tr><th>公告</th><th>状态</th><th>版本</th><th>发布时间</th><th>操作</th></tr></thead><tbody>{resource.data.items.map(a => <tr key={a.announcement_id}><td><strong>{a.title}</strong><small>{announcementTypes[a.type]}</small></td><td>{a.withdrawn_at ? '已撤回' : announcementStates[a.state]}</td><td>内容 {a.content_version} / 通知 {a.notification_revision}</td><td>{a.publish_at ? announcementTime(a.publish_at) : '未安排'}</td><td><button disabled={busy || !!pending || !!unloadedResult} onClick={() => void perform(() => loadItem(a.announcement_id))}>打开</button></td></tr>)}</tbody></table></div> : <Empty title='还没有公告草稿'>创建一条真实公告后，再选择发布时间与展示渠道。</Empty>}</section>}
        {editing && principal && <section className='announcement-editor' aria-label='公告编辑器'><header><h2>{item ? '编辑公告' : '新公告草稿'}</h2><p className='hint'>{item ? `当前内容版本 ${item.content_version}，通知版本 ${item.notification_revision}。${item.withdrawn_at ? '公告已经撤回，保留历史供核对。' : ''}` : '保存草稿后可预约或发布。'}</p></header><form onSubmit={save}><fieldset disabled={!canWrite || busy || !!pending || !!unloadedResult || !!item?.withdrawn_at || item?.state === 'ARCHIVED' || item?.state === 'EXPIRED'}><div className='announcement-editor-fields'><label className='announcement-wide'>公告标题<input value={content.title} onChange={e => patchContent({ title: e.target.value })} maxLength={160} required /></label><label>公告类别<select value={content.type} onChange={e => changeType(e.target.value as AnnouncementContent['type'])}>{Object.entries(announcementTypes).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label>可见范围<select value={content.visibility} onChange={e => patchContent({ visibility: e.target.value as AnnouncementContent['visibility'] })}><option value='PUBLIC'>公开</option><option value='AUTHENTICATED'>登录用户</option></select></label><label className='announcement-wide'>公告正文<textarea rows={12} value={content.body_markdown} onChange={e => patchContent({ body_markdown: e.target.value })} maxLength={32768} required placeholder={'## 公告内容\n\n在这里写下需要发布的消息。'} /></label></div><p className='hint'>支持二至四级标题、列表、引用、代码与 HTTPS 链接。图片、原始 HTML 和自定义样式不可使用。</p>
        {content.type === 'ACKNOWLEDGEMENTS' && <section className='announcement-ack-editor'><h3>公开致谢名单</h3><p className='hint'>只填写已获同意公开的名字与内容；没有名单时可保持为空。</p>{content.acknowledgements.map((a, i) => <fieldset key={i}><legend>致谢条目 {i + 1}</legend><label>显示名称<input value={a.display_name} onChange={e => updateAck(i, { display_name: e.target.value })} maxLength={120} required disabled={a.anonymous} /></label><label>分组<input value={a.group_name} onChange={e => updateAck(i, { group_name: e.target.value })} maxLength={120} /></label><label>公开链接<input type='url' value={a.external_link} onChange={e => updateAck(i, { external_link: e.target.value })} disabled={a.anonymous} placeholder='https://' /></label><label>致谢说明<textarea value={a.acknowledgement_note} onChange={e => updateAck(i, { acknowledgement_note: e.target.value })} maxLength={2000} /></label><label className='announcement-check'><input type='checkbox' checked={a.anonymous} onChange={e => updateAck(i, { anonymous: e.target.checked, display_name: e.target.checked ? '匿名贡献者' : '', external_link: '' })} />匿名展示</label><label className='announcement-check'><input type='checkbox' checked={!!a.consent_attested} onChange={e => updateAck(i, { consent_attested: e.target.checked })} required />已确认上述信息可公开</label><button type='button' onClick={() => patchContent({ acknowledgements: content.acknowledgements.filter((_, n) => n !== i).map((entry, n) => ({ ...entry, manual_order: n })) })}>移除此条目</button></fieldset>)}<button type='button' disabled={content.acknowledgements.length >= 100} onClick={() => patchContent({ acknowledgements: [...content.acknowledgements, { display_name: '', external_link: '', acknowledgement_note: '', group_name: '', manual_order: content.acknowledgements.length, anonymous: false, consent_attested: false }] })}>添加致谢条目</button></section>}
        <div className='announcement-actions'><button type='button' onClick={() => void perform(async () => { const result = await client.request<{ sanitized_html: string }>(announcementOps + '/render-preview', 'POST', { content }); setHTML(result.sanitized_html); })}>净化预览</button><button type='submit' className='primary' disabled={!!item && item.state !== 'DRAFT' && !canPublish}>{item && item.state !== 'DRAFT' ? '预览正文更新影响' : '保存草稿'}</button></div></fieldset></form>
        {html && <section className='announcement-editor-preview'><div><h3>正文预览</h3><label>预览版式<select value={previewMode} onChange={e => setPreviewMode(e.target.value)}><option value='desktop'>电脑</option><option value='mobile'>手机</option><option value='entry'>入口弹窗</option></select></label></div><div className={'announcement-preview-canvas ' + previewMode}><div className='announcement-body' dangerouslySetInnerHTML={{ __html: html }} /></div></section>}
        {item && canPublish && !item.withdrawn_at && <fieldset className='announcement-publication' disabled={busy || !!pending || !!unloadedResult}><legend>发布与通知</legend>{['DRAFT', 'SCHEDULED'].includes(item.state) && <><div className='announcement-editor-fields'><label>发布时间（上海）<input type='datetime-local' step='1' value={publishAt} onChange={e => setPublishAt(e.target.value)} /></label><label>开始展示（上海）<input type='datetime-local' step='1' value={visibleFrom} onChange={e => setVisibleFrom(e.target.value)} /></label><label>结束展示（上海，可留空）<input type='datetime-local' step='1' value={until} onChange={e => setUntil(e.target.value)} /></label></div></>}{['DRAFT', 'SCHEDULED', 'PUBLISHED'].includes(item.state) && <><div className='announcement-placements'>{Object.entries(placementLabels).map(([key, label]) => <label className='announcement-check' key={key}><input type='checkbox' checked={placements.some(p => p.placement === key)} onChange={e => setPlacements(old => e.target.checked ? [...old, { placement: key, manual_order: 0 }] : old.filter(p => p.placement !== key))} />{label}</label>)}</div>{placements.some(p => p.placement === 'PINNED_LIST') && <label>置顶顺序<input type='number' min={0} max={1000000} value={placements.find(p => p.placement === 'PINNED_LIST')!.manual_order} onChange={e => setPlacements(old => old.map(p => p.placement === 'PINNED_LIST' ? { ...p, manual_order: Number(e.target.value) } : p))} /></label>}</>}
        <label>操作原因<textarea value={reason} onChange={e => setReason(e.target.value)} maxLength={1000} rows={2} placeholder='撤回或重新通知时，请说明原因。' /></label><div className='announcement-actions'>{['DRAFT', 'SCHEDULED'].includes(item.state) && <><button className='primary' onClick={() => act('PUBLISH')}>发布公告</button><button onClick={() => act('SCHEDULE')}>预约发布</button></>}{item.state === 'PUBLISHED' && <><button onClick={() => act('UPDATE_PLACEMENTS')}>预览渠道调整影响</button><button onClick={() => act('RE_NOTIFY')}>重新通知</button></>}{item.state !== 'DRAFT' && <button onClick={() => act('WITHDRAW')}>撤回公告</button>}{!['DRAFT', 'ARCHIVED'].includes(item.state) && <button onClick={() => act('ARCHIVE')}>归档公告</button>}</div></fieldset>}
        {item?.first_published_at && !item.withdrawn_at && <p><Link to={'/announcements/' + item.announcement_id + (['EXPIRED', 'ARCHIVED'].includes(item.state) ? '?archive=true' : '')}>查看用户侧公告 ↗</Link></p>}
        </section>}
        {pending?.preview && !pending.uncertain && <div className='announcement-overlay'><Modal title='核对公告操作影响' busy={busy} onClose={() => setPending(null)}><p>{pending.preview.impact.effect}</p><dl className='announcement-impact'><div><dt>公告</dt><dd>{pending.preview.impact.title}</dd></div><div><dt>操作</dt><dd>{actionLabels[pending.command.action]}</dd></div><div><dt>可见范围</dt><dd>{pending.preview.impact.visibility === 'PUBLIC' ? '公开' : '登录用户'}</dd></div><div><dt>通知版本</dt><dd>{pending.preview.impact.notification_revision}</dd></div><div><dt>当前已读账户</dt><dd>{pending.preview.impact.read_accounts}</dd></div><div><dt>展示窗口</dt><dd>{announcementTime(pending.preview.impact.visible_from)} — {announcementTime(pending.preview.impact.visible_until)}</dd></div><div><dt>展示渠道</dt><dd>{pending.preview.impact.placements.map(p => placementLabels[p.placement]).join('、') || '仅公告列表与详情'}</dd></div></dl><p className='hint'>预览有效至 {announcementTime(pending.preview.expires_at)}。确认后按本次预览执行。</p><div className='announcement-actions'><button className='primary' disabled={busy} onClick={() => void perform(() => execute(pending))}>确认执行</button><button disabled={busy} onClick={() => setPending(null)}>返回编辑</button></div></Modal></div>}
    </main></div></div>;
}
