import { withReadyAccessGate } from './m1-test-fixtures';
import { fireEvent, render, screen, waitFor, within } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import { expect, it, vi } from 'vitest';
import { App } from './App';
import { ApiClient } from './api';
const user = { id:1,username:'test',display_name:'Test',role:1 };
const empty = { initialized:false,user_id:'1',wallets:[],scope:'LOCAL_WALLETS_ONLY',total_assets:null };
const full = { ...empty,initialized:true,wallets:[{asset:'RESERVE_API_CREDIT',balance_units:'9007199254740993',amount:'18014398509.481986',ledger_seq:'1',version:'1'},{asset:'AVAILABLE_CHIPS',balance_units:'0',amount:'0',ledger_seq:'0',version:'0'}] };
const ledger = {items:[],has_more:false,next_after_seq:null};
const entry = {id:'entry-1',transaction_id:'tx-1',user_id:'1',asset:'RESERVE_API_CREDIT',ledger_seq:'1',wallet_version:'1',entry_type:'credit',biz_type:'fixture',biz_id:'biz-1',delta_units:'1',balance_before_units:'0',balance_after_units:'1',delta_amount:'0.000002',balance_after_amount:'0.000002',created_at:'2026-09-05T00:00:00Z'};
const ok = (data:unknown) => new Response(JSON.stringify({success:true,data}));
function setup(respond?: (path:string,init?:RequestInit) => Response | Promise<Response> | undefined) {
 const f=vi.fn(async(p:string,init?:RequestInit)=>{const custom=respond?.(p,init);if(custom) return custom;if(p.includes('/refresh'))return ok({access_token:'memory',access_expires_at:9999999999,session:{sid:'sid'},user});if(p==='/api/user/self')return ok(user);if(p==='/platform/v1/wallet')return ok(empty);if(p.startsWith('/platform/v1/wallet/ledger'))return ok(ledger);return ok({items:[],total:0,page:1,page_size:10});});
 const c=new ApiClient(withReadyAccessGate(f));return {f,c,...render(<MemoryRouter initialEntries={['/wallet']}><App client={c}/></MemoryRouter>)};
}
it('GET never initializes; explicit POST sends empty JSON with native auth and reloads',async()=>{let initialized=false;const {f}=setup((p)=>{if(p==='/platform/v1/wallet')return ok(initialized?full:empty);if(p.endsWith('/initialize')){initialized=true;return ok(full);}});await screen.findByText('尚未初始化钱包');expect(f.mock.calls.some(c=>c[0].endsWith('/initialize'))).toBe(false);const button=screen.getByRole('button',{name:'初始化零余额钱包'});fireEvent.click(button);fireEvent.click(button);await screen.findByText('18014398509.481986');const posts=f.mock.calls.filter(c=>c[0].endsWith('/initialize'));expect(posts).toHaveLength(1);expect(posts[0][1]?.method).toBe('POST');expect(posts[0][1]?.body).toBe('{}');const headers=new Headers(posts[0][1]?.headers);expect(headers.get('Authorization')).toBe('Bearer memory');expect(headers.get('New-Api-User')).toBe('1');expect(headers.get('X-Auth-Session')).toBe('sid');expect(headers.get('Content-Type')).toBe('application/json');expect(screen.queryByRole('button',{name:'初始化零余额钱包'})).not.toBeInTheDocument();await screen.findByText('暂无资产流水');});
it('locks ambiguous init until successful explicit refresh and never retries POST automatically',async()=>{let readsFail=false;const {f}=setup(p=>{if(p.endsWith('/initialize'))return Promise.reject(new Error('lost'));if(p==='/platform/v1/wallet'&&readsFail)return new Response('',{status:503});});fireEvent.click(await screen.findByRole('button',{name:'初始化零余额钱包'}));await screen.findByText(/初始化结果尚未确认/);expect(screen.getByRole('button',{name:'初始化零余额钱包'})).toBeDisabled();expect(f.mock.calls.filter(c=>c[0]==='/platform/v1/wallet')).toHaveLength(1);readsFail=true;fireEvent.click(screen.getByRole('button',{name:'刷新钱包'}));await screen.findByText(/当前未展示余额|服务响应格式异常/);expect(screen.queryByRole('button',{name:'初始化零余额钱包'})).not.toBeInTheDocument();readsFail=false;fireEvent.click(screen.getByRole('button',{name:'刷新钱包'}));await waitFor(()=>expect(screen.getByRole('button',{name:'初始化零余额钱包'})).toBeEnabled());expect(f.mock.calls.filter(c=>c[0].endsWith('/initialize'))).toHaveLength(1);});
it('a 403 is visible without globally logging out or fabricating balances',async()=>{const {c}=setup(p=>p==='/platform/v1/wallet'?new Response(JSON.stringify({success:false,code:'WALLET_FORBIDDEN',message:'钱包暂不可访问'}),{status:403}):undefined);await screen.findByText(/钱包暂不可访问/);expect(c.getSnapshot().user?.id).toBe(1);expect(screen.queryByLabelText('平台本地钱包余额')).not.toBeInTheDocument();});
it('missing amount does not render zero and refresh recovers',async()=>{let broken=true;setup(p=>p==='/platform/v1/wallet'?ok(broken?{...full,wallets:[{...full.wallets[0],amount:undefined},full.wallets[1]]}:full):undefined);await screen.findByText(/钱包响应格式异常/);expect(screen.queryByLabelText('平台本地钱包余额')).not.toBeInTheDocument();broken=false;fireEvent.click(screen.getByRole('button',{name:'刷新钱包'}));await screen.findByText('18014398509.481986');});
it('cursor paging renders signed exact amounts and asset switching drops late prior-asset responses',async()=>{let resolve!:(r:Response)=>void;const {f}=setup(p=>{if(p==='/platform/v1/wallet')return ok(full);if(p.includes('asset=RESERVE_API_CREDIT&after_seq=0'))return ok({items:[entry],has_more:true,next_after_seq:'1'});if(p.includes('asset=RESERVE_API_CREDIT&after_seq=1'))return new Promise<Response>(r=>resolve=r);});await screen.findByText('+0.000002');expect(screen.getByText('+0.000002').closest('tr')?.querySelector('time')).toHaveAttribute('dateTime',entry.created_at);fireEvent.click(screen.getByRole('button',{name:'下一页流水'}));await waitFor(()=>expect(f.mock.calls.some(c=>c[0].includes('after_seq=1&limit=20'))).toBe(true));fireEvent.change(screen.getByLabelText('流水资产'),{target:{value:'AVAILABLE_CHIPS'}});await screen.findByText('暂无资产流水');resolve(ok({items:[{...entry,id:'entry-2',ledger_seq:'2',delta_amount:'0.000004',delta_units:'2',balance_after_units:'2',balance_after_amount:'0.000004'}],has_more:false,next_after_seq:null}));await waitFor(()=>expect(f.mock.calls.some(c=>c[0].includes('asset=AVAILABLE_CHIPS&after_seq=0&limit=20'))).toBe(true));expect(screen.queryByText('+0.000004')).not.toBeInTheDocument();expect(screen.getByRole('button',{name:'下一页流水'})).toBeDisabled();});
it('late initialization cannot repopulate wallet after leaving the page',async()=>{let resolve!:(r:Response)=>void;setup(p=>p.endsWith('/initialize')?new Promise<Response>(r=>resolve=r):undefined);fireEvent.click(await screen.findByRole('button',{name:'初始化零余额钱包'}));fireEvent.click(within(screen.getByRole('navigation',{name:'主导航'})).getByRole('link',{name:/指挥台/}));await screen.findByRole('heading',{name:'指挥台',level:1});resolve(ok(full));expect(screen.queryByText('18014398509.481986')).not.toBeInTheDocument();});
it('late wallet GET cannot restore session or balances after logout',async()=>{let resolve!:(r:Response)=>void;const {c,f}=setup(p=>p==='/platform/v1/wallet'?new Promise<Response>(r=>resolve=r):undefined);await waitFor(()=>expect(f.mock.calls.some(c=>c[0]==='/platform/v1/wallet')).toBe(true));fireEvent.click(screen.getByRole('button',{name:'账户菜单'}));fireEvent.click(screen.getByRole('button',{name:'退出登录'}));await screen.findByRole('button',{name:/登录控制台/});resolve(ok(full));await waitFor(()=>expect(c.getSnapshot().user).toBeNull());expect(screen.queryByText('18014398509.481986')).not.toBeInTheDocument();});
it('user changes replace wallet scope and discard prior user GET completion',async()=>{let resolve!:(r:Response)=>void;let account='1';const {c,f}=setup(p=>{if(p==='/api/user/login'){account='2';return ok({access_token:'second',access_expires_at:9999999999,session:{sid:'second'},user:{...user,id:2}});}if(p==='/platform/v1/wallet')return account==='1'?new Promise<Response>(r=>resolve=r):ok({...empty,user_id:'2'});});await waitFor(()=>expect(f.mock.calls.some(c=>c[0]==='/platform/v1/wallet')).toBe(true));await c.login('second','password');await screen.findByText('尚未初始化钱包');resolve(ok(full));await waitFor(()=>expect(c.getSnapshot().user?.id).toBe(2));expect(screen.queryByText('18014398509.481986')).not.toBeInTheDocument();});
it('late initialize result is discarded after logout',async()=>{let resolve!:(r:Response)=>void;const {c}=setup(p=>p.endsWith('/initialize')?new Promise<Response>(r=>resolve=r):undefined);fireEvent.click(await screen.findByRole('button',{name:'初始化零余额钱包'}));fireEvent.click(screen.getByRole('button',{name:'账户菜单'}));fireEvent.click(screen.getByRole('button',{name:'退出登录'}));await screen.findByRole('button',{name:/登录控制台/});resolve(ok(full));await waitFor(()=>expect(c.getSnapshot().user).toBeNull());expect(screen.queryByText('18014398509.481986')).not.toBeInTheDocument();});
