import { withReadyAccessGate } from './m1-test-fixtures';
import { render, screen, fireEvent, waitFor, within } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import { it, expect, vi } from 'vitest';
import { App } from './App';
import { ApiClient } from './api';
const user = { id: 1, username: 'test', display_name: 'Test', role: 100, group: 'team' };
const ok = (data?: unknown) => new Response(JSON.stringify({ success: true, data }));
const channel = { id: 7, name: 'My channel', type: 1, status: 1, models: 'alpha', group: 'team', base_url: 'http://127.0.0.1:9000', model_mapping: '', setting: '{"proxy":"preserve"}', header_override: '{"Host":"preserve"}' };
const list = { items: [channel], total: 1, page: 1, page_size: 10 };
function setup(path: string, role = 100, respond?: (path: string, init?: RequestInit) => Response | Promise<Response> | undefined) {
 const f = vi.fn(async (p: string, init?: RequestInit) => { const custom = respond?.(p, init); if (custom) return custom; if (p.includes('/refresh')) return ok({ access_token: 'memory', access_expires_at: 9999999999, session: { sid: 'sid' }, user: { ...user, role } }); if (p === '/api/user/self') return ok({ ...user, role }); if (p.endsWith('/groups')) return ok({ team: { ratio: 1, desc: 'Team' }, another: { ratio: 2, desc: 'Another' } }); if (p.includes('/models?group=team')) return ok(['alpha', 'beta']); if (p.includes('/models?group=another')) return ok(['gamma']); if (p.startsWith('/api/channel/')) return ok(list); return ok({ items: [], total: 0, page: 1, page_size: 10 }); });
 const c = new ApiClient(withReadyAccessGate(f)); const view = render(<MemoryRouter initialEntries={[path]}><App client={c}/></MemoryRouter>); return { f, c, ...view };
}
it('keeps public discovery independent from the private playground group reader', async () => { const {f,c}=setup('/models'); await waitFor(()=>expect(c.getSnapshot().ready).toBe(true)); expect(screen.getByRole('heading',{level:1})).toHaveTextContent('找到合适的模型'); expect(screen.queryByLabelText('分组')).not.toBeInTheDocument(); expect(f.mock.calls.some(c=>c[0].endsWith('/groups')||c[0].includes('/models?group='))).toBe(false); });
it('resets model when group changes and rejects stale query model', async () => { setup('/playground?model=missing&group=team'); await screen.findByRole('option', { name: 'alpha' }); expect(screen.getByLabelText('模型')).toHaveValue('alpha'); fireEvent.change(screen.getByLabelText('分组'), { target: { value: 'another' } }); await screen.findByRole('option', { name: 'gamma' }); expect(screen.getByLabelText('模型')).toHaveValue('gamma'); });
it('sends once, renders escaped output and clears on navigation without storing content', async () => {
 const storage = vi.spyOn(Storage.prototype, 'setItem'); let resolve!: (r: Response) => void;
 const { f } = setup('/playground?model=alpha&group=team', 1, p => p === '/pg/chat/completions' ? new Promise<Response>(r => resolve = r) : undefined);
 await screen.findByRole('option', { name: 'alpha' }); fireEvent.change(screen.getByLabelText('提示词'), { target: { value: 'private prompt' } }); const send = screen.getByRole('button', { name: '发送' }); fireEvent.click(send); fireEvent.click(send);
 await waitFor(() => expect(f.mock.calls.filter(c => c[0] === '/pg/chat/completions')).toHaveLength(1));
 resolve(new Response('data: {"choices":[{"delta":{"content":"<script>secret</script>","reasoning_content":"thinking"}}]}\n\ndata: [DONE]\n\n', { headers: { 'Content-Type': 'text/event-stream' } }));
 expect(await screen.findByText('<script>secret</script>')).toBeVisible(); expect(document.querySelector('script')).toBeNull(); await screen.findByText('已完成'); expect(storage).not.toHaveBeenCalled();
 fireEvent.click(within(screen.getByRole('navigation', { name: '主导航' })).getByRole('link', { name: /模型目录/ })); await screen.findByText(/找到合适的模型/); expect(screen.queryByText('<script>secret</script>')).not.toBeInTheDocument();
 fireEvent.click(screen.getByRole('link', { name: /文本测试/ })); expect(await screen.findByLabelText('提示词')).toHaveValue(''); storage.mockRestore();
});
it('aborts request when leaving playground', async () => { let signal: AbortSignal | null | undefined; setup('/playground', 1, (p, init) => { if (p !== '/pg/chat/completions') return; signal = init?.signal; return new Promise<Response>((_, reject) => signal?.addEventListener('abort', () => reject(new DOMException('aborted', 'AbortError')))); }); await screen.findByRole('option', { name: 'alpha' }); fireEvent.change(screen.getByLabelText('提示词'), { target: { value: 'hello' } }); fireEvent.click(screen.getByRole('button', { name: '发送' })); await waitFor(() => expect(signal).toBeTruthy()); fireEvent.click(within(screen.getByRole('navigation', { name: '主导航' })).getByRole('link', { name: /模型目录/ })); await waitFor(() => expect(signal?.aborted).toBe(true)); });
it('role gates admin route and sensitive controls', async () => { const { unmount } = setup('/admin/channels', 1); await screen.findByText('需要管理员权限'); expect(screen.queryByRole('link', { name: /渠道管理/ })).not.toBeInTheDocument(); unmount(); setup('/admin/channels', 10); await screen.findByText('My channel'); expect(screen.queryByRole('button', { name: '新建渠道' })).not.toBeInTheDocument(); expect(screen.queryByRole('button', { name: '编辑' })).not.toBeInTheDocument(); expect(screen.getByRole('button', { name: '停用' })).toBeVisible(); });
it('patches explicit fields only, never resends blank key, preserves advanced config and confirms native status POST', async () => { const { f } = setup('/admin/channels'); fireEvent.click(await screen.findByRole('button', { name: '编辑' })); expect(screen.getByLabelText('新上游密钥（留空保留）')).toHaveAttribute('type', 'password'); fireEvent.change(screen.getByLabelText('渠道名称'), { target: { value: 'Renamed' } }); fireEvent.click(screen.getByRole('button', { name: '保存渠道' })); await waitFor(() => expect(f.mock.calls.some(c => c[1]?.method === 'PUT')).toBe(true)); const put = f.mock.calls.find(c => c[1]?.method === 'PUT')!; const body = JSON.parse(String(put[1]?.body)); expect(body).toEqual({ id: 7, name: 'Renamed', base_url: channel.base_url, models: 'alpha', group: 'team', model_mapping: '' }); for (const field of ['key','status','setting','header_override']) expect(body).not.toHaveProperty(field);
 fireEvent.click(await screen.findByRole('button', { name: '停用' })); expect(f.mock.calls.some(c => c[0].endsWith('/status'))).toBe(false); fireEvent.click(screen.getByRole('button', { name: '确认停用' })); await waitFor(() => expect(f.mock.calls.some(c => c[0] === '/api/channel/7/status')).toBe(true)); const status = f.mock.calls.find(c => c[0].endsWith('/status'))!; expect(status[1]?.method).toBe('POST'); expect(JSON.parse(String(status[1]?.body))).toEqual({ status: 2 }); });
it('locks uncertain channel writes until successful explicit refresh, hides upstream secrets', async () => { const { f } = setup('/admin/channels',100,(p,init) => p.endsWith('/status') && init?.method === 'POST' ? new Response(JSON.stringify({ success: false, message: 'secret-key' }), { status: 502 }) : undefined); fireEvent.click(await screen.findByRole('button',{name:'停用'})); fireEvent.click(screen.getByRole('button',{name:'确认停用'})); await screen.findByText(/操作结果尚未确认/); expect(screen.queryByText('secret-key')).not.toBeInTheDocument(); fireEvent.click(screen.getByRole('button',{name:'关闭对话框'})); expect(screen.getByRole('button',{name:'停用'})).toBeDisabled(); fireEvent.click(screen.getByRole('button',{name:'刷新列表'})); await waitFor(() => expect(screen.getByRole('button',{name:'停用'})).not.toBeDisabled()); expect(f.mock.calls.filter(c => c[0].endsWith('/status'))).toHaveLength(1); });
it('preserves the private playground empty state with an admin link', async () => { setup('/playground',100,p => p.includes('/models?') ? ok(null) : undefined); await screen.findByText('当前分组暂无可用模型'); expect(screen.getByRole('link',{name:'配置渠道'})).toHaveAttribute('href','/admin/channels'); });

it('creates only the native basic envelope and clears the password after saving', async () => { const {f}=setup('/admin/channels'); fireEvent.click(await screen.findByRole('button',{name:'新建渠道'})); await waitFor(()=>expect(screen.getByLabelText('渠道分组（逗号分隔）')).toHaveValue('team')); fireEvent.change(screen.getByLabelText('渠道名称'),{target:{value:'Created'}}); fireEvent.change(screen.getByLabelText('基础 URL'),{target:{value:'http://127.0.0.1:9000'}}); fireEvent.change(screen.getByLabelText('模型 ID（逗号分隔）'),{target:{value:'alpha'}}); fireEvent.change(screen.getByLabelText('模型映射 JSON（可选）'),{target:{value:'{"alpha":"actual"}'}}); fireEvent.change(screen.getByLabelText('上游密钥'),{target:{value:'synthetic-key'}}); expect(screen.getByLabelText('上游密钥')).toHaveAttribute('autocomplete','off'); fireEvent.click(screen.getByRole('button',{name:'确认创建渠道'})); await waitFor(()=>expect(f.mock.calls.some(c=>c[0]==='/api/channel/'&&c[1]?.method==='POST')).toBe(true)); const call=f.mock.calls.find(c=>c[0]==='/api/channel/'&&c[1]?.method==='POST')!; expect(JSON.parse(String(call[1]?.body))).toEqual({mode:'single',multi_key_mode:'',batch_add_set_key_prefix_2_name:false,channel:{type:1,name:'Created',base_url:'http://127.0.0.1:9000',models:'alpha',group:'team',model_mapping:'{"alpha":"actual"}',key:'synthetic-key',status:1}}); await waitFor(()=>expect(screen.queryByLabelText('上游密钥')).not.toBeInTheDocument()); expect(f.mock.calls.some(c=>c[0].endsWith('/key'))).toBe(false); });
it('validates channel URL credentials and mapping without sending a mutation', async () => { const {f}=setup('/admin/channels'); fireEvent.click(await screen.findByRole('button',{name:'编辑'})); fireEvent.change(screen.getByLabelText('基础 URL'),{target:{value:'https://user:password@example.test'}}); fireEvent.click(screen.getByRole('button',{name:'保存渠道'})); await screen.findByText(/基础 URL 仅接受/); expect(f.mock.calls.some(c=>c[1]?.method==='PUT')).toBe(false); fireEvent.change(screen.getByLabelText('基础 URL'),{target:{value:'https://example.test'}}); fireEvent.change(screen.getByLabelText('模型映射 JSON（可选）'),{target:{value:'{"alpha":7}'}}); fireEvent.click(screen.getByRole('button',{name:'保存渠道'})); await screen.findByText('模型映射应为值全部是字符串的 JSON 对象。'); expect(f.mock.calls.some(c=>c[1]?.method==='PUT')).toBe(false); });
it('preserves private playground retries with the selected group', async () => { let failed=true; const {f}=setup('/playground',1,p=>p.includes('/models?')&&failed?new Response(JSON.stringify({success:false,message:'模型读取失败'})):undefined); await screen.findByText('模型读取失败'); failed=false; fireEvent.click(screen.getByRole('button',{name:'重新加载'})); await screen.findByRole('option',{name:'alpha'}); expect(f.mock.calls.filter(c=>c[0].includes('/models?')).every(c=>c[0].endsWith('group=team'))).toBe(true); });
it('keeps failed list refresh from unlocking an uncertain channel write', async () => { let failList=false; setup('/admin/channels',100,(p,init)=>{if(p.endsWith('/status')) {failList=true;return new Response('',{status:502});} if(p.startsWith('/api/channel/?')&&failList) return new Response(JSON.stringify({success:false}),{status:503});}); fireEvent.click(await screen.findByRole('button',{name:'停用'}));fireEvent.click(screen.getByRole('button',{name:'确认停用'}));await screen.findByText(/操作结果尚未确认/);fireEvent.click(screen.getByRole('button',{name:'关闭对话框'}));fireEvent.click(screen.getByRole('button',{name:'刷新列表'}));await screen.findByRole('button',{name:'重新加载'});expect(screen.getByRole('button',{name:'新建渠道'})).toBeDisabled(); });
it('lists non-type1 channels with no editor and paginates native results', async () => { const {f}=setup('/admin/channels',100,p=>p.startsWith('/api/channel/?')?ok({...list,total:11,items:[{...channel,type:8}]}):undefined); await screen.findByText('My channel'); expect(screen.queryByRole('button',{name:'编辑'})).not.toBeInTheDocument(); fireEvent.click(screen.getByRole('button',{name:'下一页'}));await waitFor(()=>expect(f.mock.calls.some(c=>c[0]==='/api/channel/?p=2&page_size=10&id_sort=true')).toBe(true)); });
