import { it, expect, vi } from 'vitest';
import { ApiClient } from './api';
const user = { id: 1, username: 'test', display_name: 'Test', role: 100, group: 'team' };
const bundle = { access_token: 'memory', access_expires_at: 9999999999, session: { sid: 'sid' }, user };
const ok = (data?: unknown) => new Response(JSON.stringify({ success: true, data }));
const input = { model: 'text-model', group: 'team', prompt: 'Hello', maxTokens: 256 };
function sse(text: string, size = 1) { const bytes = new TextEncoder().encode(text); return new Response(new ReadableStream({ start(c) { for (let i = 0; i < bytes.length; i += size) c.enqueue(bytes.slice(i, i + size)); c.close(); } }), { headers: { 'Content-Type': 'text/event-stream' } }); }
async function setup(response: Response) { const f = vi.fn().mockResolvedValueOnce(ok(bundle)).mockResolvedValueOnce(response); const c = new ApiClient(f); await c.login('a', 'b'); return { c, f }; }
it('streams segmented CRLF and UTF8, reasoning, usage-only events and DONE with exact native body', async () => {
 const { c, f } = await setup(sse(': keepalive\r\n\r\ndata: {"choices":[{"delta":{"reasoning_content":"想"}}]}\r\n\r\ndata: {"choices":[{"delta":{"content":"你好 <b>x</b>"}}]}\r\n\r\ndata: {"choices":[],"usage":{"prompt_tokens":2,"completion_tokens":3,"total_tokens":5}}\r\n\r\ndata: [DONE]\r\n\r\n'));
 const update = vi.fn(); const result = await c.playground(input, new AbortController().signal, update);
 expect(result.text).toBe('你好 <b>x</b>'); expect(result.reasoning).toBe('想'); expect(result.usage?.total_tokens).toBe(5); expect(update).toHaveBeenCalled();
 expect(f.mock.calls[1][0]).toBe('/pg/chat/completions'); expect(JSON.parse(f.mock.calls[1][1].body)).toEqual({ model: 'text-model', group: 'team', messages: [{ role: 'user', content: 'Hello' }], max_tokens: 256, stream: true });
 expect(new Headers(f.mock.calls[1][1].headers).get('X-Auth-Session')).toBe('sid');
});
it('distinguishes premature EOF from successful complete', async () => { const { c } = await setup(sse('data: {"choices":[{"delta":{"content":"partial"},"finish_reason":"stop"}]}\n\n')); await expect(c.playground(input, new AbortController().signal, vi.fn())).rejects.toMatchObject({ code: 'STREAM_EOF' }); });
it.each([401,403,503])('never replays model POST on %s and hides upstream text', async status => { const { c, f } = await setup(new Response(JSON.stringify({ error: { message: 'secret-upstream-key', code: 'upstream_error' } }), { status })); await expect(c.playground(input, new AbortController().signal, vi.fn())).rejects.not.toThrow('secret-upstream-key'); expect(f).toHaveBeenCalledTimes(2); expect(Boolean(c.getSnapshot().user)).toBe(status !== 401); });
it('aborts a pending stream and ignores later chunks', async () => { let controller!: ReadableStreamDefaultController<Uint8Array>; const response = new Response(new ReadableStream({ start(c) { controller = c; } }), { headers: { 'Content-Type': 'text/event-stream' } }); const { c } = await setup(response); const abort = new AbortController(); const update = vi.fn(); const promise = c.playground(input, abort.signal, update); await Promise.resolve(); abort.abort(); await expect(promise).rejects.toMatchObject({ code: 'ABORTED' }); expect(update).not.toHaveBeenCalled(); expect(() => controller.enqueue(new Uint8Array())).toThrow(); });
it('bounds stream input and rejects embedded errors without secret disclosure', async () => { const { c } = await setup(sse('data: {"error":{"message":"secret"}}\n\n', 100)); await expect(c.playground(input, new AbortController().signal, vi.fn())).rejects.not.toThrow('secret'); const large = await setup(sse('data: ' + 'x'.repeat(1048577), 65536)); await expect(large.c.playground(input, new AbortController().signal, vi.fn())).rejects.toMatchObject({ code: 'STREAM_LIMIT' }); });
it('validates actual groups/models and preserves user group', async () => { const { c, f } = await setup(ok({ team: { ratio: 1, desc: 'Team' } })); expect(c.getSnapshot().user?.group).toBe('team'); expect(await c.groups()).toEqual({ team: { ratio: 1, desc: 'Team' } }); f.mockResolvedValueOnce(ok(null)); expect(await c.models('team & x')).toEqual([]); expect(f.mock.lastCall?.[0]).toBe('/api/user/models?group=team%20%26%20x'); f.mockResolvedValueOnce(ok([1])); await expect(c.models('team')).rejects.toThrow(); });
it('accepts bounded native JSON text result when a server does not stream', async () => { const { c } = await setup(new Response(JSON.stringify({ choices: [{ message: { content: 'text', reasoning_content: 'reason' } }], usage: { total_tokens: 4, completion_tokens: -1 } }), { headers: { 'Content-Type': 'application/json' } })); const result = await c.playground(input, new AbortController().signal, vi.fn()); expect(result).toEqual({ text: 'text', reasoning: 'reason', usage: { total_tokens: 4 } }); });
it('refreshes an expired session before exactly one model POST', async () => { const f = vi.fn().mockResolvedValueOnce(ok({ ...bundle, access_expires_at: 1 })).mockResolvedValueOnce(ok(bundle)).mockResolvedValueOnce(sse('data: [DONE]\n\n')); const c = new ApiClient(f); await c.login('a','b'); await c.playground(input,new AbortController().signal,vi.fn()); expect(f.mock.calls.map(c => c[0])).toEqual(['/api/user/login','/api/user/auth/refresh','/pg/chat/completions']); });
it('rejects invalid token budgets and oversized prompts before any model request', async () => { const { c, f } = await setup(sse('data: [DONE]\n\n')); for(const value of [0,1.5,4097]) await expect(c.playground({...input,maxTokens:value},new AbortController().signal,vi.fn())).rejects.toThrow(); await expect(c.playground({...input,prompt:'a'.repeat(16001)},new AbortController().signal,vi.fn())).rejects.toThrow(); expect(f).toHaveBeenCalledTimes(1); });
it('logout aborts a stream without restoring its session or publishing late output', async () => { let controller!: ReadableStreamDefaultController<Uint8Array>; const { c, f } = await setup(new Response(new ReadableStream({start(c){controller=c;}}), {headers:{'Content-Type':'text/event-stream'}})); const update=vi.fn(); const promise=c.playground(input,new AbortController().signal,update); const rejection=expect(promise).rejects.toMatchObject({code:'ABORTED'}); await Promise.resolve(); f.mockResolvedValueOnce(ok()); await c.logout(); await rejection; expect(update).not.toHaveBeenCalled(); expect(c.getSnapshot().user).toBeNull(); expect(()=>controller.enqueue(new Uint8Array())).toThrow(); });
it('five minute timeout is a failure, not a successful finish', async () => { vi.useFakeTimers(); try { const {c}=await setup(new Response(new ReadableStream(),{headers:{'Content-Type':'text/event-stream'}})); const promise=c.playground(input,new AbortController().signal,vi.fn()); const rejection=expect(promise).rejects.toMatchObject({code:'STREAM_TIMEOUT'}); await vi.advanceTimersByTimeAsync(300000); await rejection; } finally { vi.useRealTimers(); } });
